### ISSUE TITLE
Missing text in all labels or symbols (Qt 6.8.0)

### ISSUE THREAD

**Issue by aisuneko** [ra3xdh/qucs_s#1002]
All texts present in the schematics, including symbol labels, diagram markers and wire labels (except axis labels on diagrams) are not rendered properly, shown as blanks missing on the screen:
![image](https://github.com/user-attachments/assets/e7af3055-1776-4abf-842d-71a0bc5c331d)

Clicking on and selecting text boxes in certain labels might reveal the text within, but they seem to be transparent and are not actually rendered on the screen. Right clicking on these hidden text labels might show a "fake" popup menu with its color the same as the schematic background but unable to interact with.
![image](https://github.com/user-attachments/assets/88f2c2dc-2ba5-476e-ac9b-576f21951e96)

Terminal will be spammed with lots of `Warning: The requested buffer size is too big, ignoring (:0, )` messages when launched from the command line.
Qucs-S 24.3.0, Arch Linux, Qt 6.8.0

**Comment by ra3xdh** [comment]
We are aware about this problem. It is related to bug in Qt itself. Wait for merging #995 for the solution.

**Comment by ra3xdh** [comment]
Fixed by #995
