### ISSUE TITLE
Diode appearance don't change when setting the "symbol" property

### ISSUE THREAD

**Issue by ProtonTheFox** [ra3xdh/qucs_s#1004]
Problem
=======

I've noticed that changing the variant of the diode symbol does not change its appearance anymore:

![image](https://github.com/user-attachments/assets/08b2aa48-d716-4456-a43a-52b376e3d0d7)

I recall it used to be working correctly in the previous versions, so something could have been broken somewhere.

The other components don't seem to be affected by this problem, here are the capacitor and a buffer gate for instance:

![image](https://github.com/user-attachments/assets/c7411b95-b0a9-4ccb-a22c-2042b0c6824e)

Setup
=====

OS : Kubuntu 24.04.1 LTS
Qucs-S version : 24.3.2 (from .deb)
Qt version : 6.4.2

**Comment by ra3xdh** [comment]
Fixed by #1006
