### ISSUE TITLE
Subcircuits node names are not made unique with ng-spice

### ISSUE THREAD

**Issue by Rmano** [ra3xdh/qucs_s#1007]
Hi --- this is a quite complex thing to explain, so please bear with me...

The following project, opened with qucs 24.3.2 on a Manjaro system, with `ngspice-43`, behave in a very strange way. 
 
[strangesub_prj.zip](https://github.com/user-attachments/files/17446808/strangesub_prj.zip)

Notice that the project has the "LT" compatibility flag on.

I downloaded the INA826 library from the TI site; this is a very popular instrumentation amplifier. It works ok "as is" in LTspice (under Windows or Wine in Linux). If I use it directly in my circuit by picking it like this:

![image](https://github.com/user-attachments/assets/5f9e68b3-3e52-4092-b13d-983459d157ed)

it does not work at all: my results are the following: 

![image](https://github.com/user-attachments/assets/eb323a4c-77c8-4628-8bdc-b33100dcd66f)

As you can see, the amplifier is basically dead.

Now, I edited the text `.lib` file and changed all the occurrences of "GND" to "VSS" with a simple global search and replace, and to avoid clashes, I changed the name of the device to INA826E. And now...

![Screenshot from 2024-10-19 18-15-19](https://github.com/user-attachments/assets/52ee1d78-d011-49f7-86ec-5adff4d5cd91)

It works flawlessly!!! So basically, the subcircuit node named "GND" is conflated with the external "GND" node name...

So this seems to be an encapsulation problem, and  I do not know if the problem is in `qucs-s` or in `ngspice`.  Node names in the subcircuit should be private, don't they? At least, they behave in the LTspice app.

**Comment by tomhajjar** [comment]
One of the schematics is missing the device.

![2024-10-19_125053](https://github.com/user-attachments/assets/8c184adf-e7e4-4102-a831-dbf2608c785e)

**Comment by Rmano** [comment]
You're right. Forgot to make save/all before creating the zip... I have re-loaded it above. Thanks and sorry for the problem...

**Comment by tomhajjar** [comment]
I created a new project for you. It will also show you how to make sub-circuits and symbols.

There are v1 and v1.1 of the Spice model INA826 and you modified v1. I tested all 3 versions. I didn't dig into which model works under ngspice. The cleaned up project will make it easier for @ra3xdh to make a judgement.

The v1.1 model tests the same as v1.  I assume your modified v1e model works. 

The v1.1 model is supposed to be less "cluttered". It removed a number of unused sub-circuits. The pin order is totally different.

![2024-10-19_142817](https://github.com/user-attachments/assets/f7ccd247-e48b-434f-bc67-35ad0c2ebcd5)
![2024-10-19_142757](https://github.com/user-attachments/assets/e9749c52-197b-4572-9458-f58e6009a193)
![2024-10-19_142736](https://github.com/user-attachments/assets/1d0bffa3-6bf1-4f72-9227-2b22a61a875e)

[OpAmp_INA826_prj.zip](https://github.com/user-attachments/files/17446897/OpAmp_INA826_prj.zip)

**Comment by Rmano** [comment]
Very nice, thanks! Is there a tutorial somewhere on how did you do it? I tried but got stuck... even if I authored a simple tutorial for QUCS subcircuits (see attached), I got lost when trying to integrate the external libraries ... 

[ampli_qucs_tut.pdf](https://github.com/user-attachments/files/17446974/ampli_qucs_tut.pdf)

BTW, if this could be of interest for the documentation project, I'll be happy to contribute (adapting to qucs-s, that is, with also spice simulation).

**Comment by tomhajjar** [comment]
Your tutorial is a start. 

It's easier for beginners to make sub-circuits from manufacturer Spice models if one looks at the many examples I posted in the Discussion area or examples included in the Qucs-S distribution. Finding Spice models compatible with ngspice is the most difficult thing. There is no guarantee a model that woks in LTspice or PSpice will work in ngspice. The ngspice guys can help determine if a model can be altered to work in ngspice or a modification to ngspice is justified.

I also posted Symbol examples that you can copy-paste into your subcircuit. I generally copy an existing symbol from the symbol examples into "symbols_blank.sch" and clean it up prior to placing it into the sub-circuit.

**Comment by ra3xdh** [comment]
The Qucs-S doesn't apply any conversion to SPICE files attached via *Spice Library Device* and only checks if it contains .SUBCKT header. The specified file is included in .INCLUDE statement as is. It seems to be a problem of Ngspice. The GND may be a reserved keyword at some conditions. A minimal example reproducing this problem is required.

**Comment by Rmano** [comment]
> The Qucs-S doesn't apply any conversion to SPICE files attached via _Spice Library Device_ and only checks if it contains .SUBCKT header. The specified file is included in .INCLUDE statement as is. It seems to be a problem of Ngspice. The GND may be a reserved keyword at some conditions. A minimal example reproducing this problem is required.

Yes --- it seems that the GND symbol and name is global: https://www.reddit.com/r/AskElectronics/comments/sf6d66/ltspice_how_to_create_subcircuit_with_gnd_pin/ , so the bug is in the subcircuit specification (or maybe there is some strange version of SPICE where that doesn't happen).

Thanks
