### ISSUE TITLE
Adding new devices to existing Libraries

### ISSUE THREAD

**Issue by tomhajjar** [ra3xdh/qucs_s#1010]
In reference to #1007
@rmano @csrabak

I created INA826 for SpiceOpamp.lib. I got warnings but the device seems to work. You can decide if the warnings are relevant. 

1) Once again I accidently used "SPICE library device" instead of "SPICE netlist" so sub-circuits worked but the Library device didn't. I found my error by looking at the Library with a text editor and saw no Spice info.

2) When new library is made you must close/reopen Qucs-S to access it. Can this be resolved?

3) This could be used as an example/tutorial how to add devices to existing Libraries. There are many pitfalls to creating, editing Libraries or adding devices that would trip up a User. The revised Create Library utility is better than the original but could be improved.

![2024-10-20_124152](https://github.com/user-attachments/assets/07703ec0-8e70-4d7f-84bd-e4e1b481482c)
![2024-10-20_111458](https://github.com/user-attachments/assets/567d579a-12b1-49ec-b41a-d83ab2e9599d)
![2024-10-20_110146](https://github.com/user-attachments/assets/ff18129c-ad58-4faa-8e09-b4df0844f39b)
![2024-10-20_110735](https://github.com/user-attachments/assets/f35d44e4-bc0d-4f3e-a9b4-4e066e343f8c)

[OpAmp_INA826_lib_prj.zip](https://github.com/user-attachments/files/17450828/OpAmp_INA826_lib_prj.zip)

**Comment by Rmano** [comment]
The result seems correct, but what I pointed out in #1007 is that it should not needed to change the name of the `.lib` node from "GND" to "VSS"--- or am I wrong? I mean, the node names should be "insulated" by the external connections, no? 

I'll try to check this model. The warnings are a bit scary... they are not there in #1007 in the circuit that works.

**Comment by ra3xdh** [comment]
> This could be used as an example/tutorial how to add devices to existing Libraries. 

This guide about libraries and subcircuits needs a translation: https://habr.com/ru/articles/805963/ See #554 Unfortunately nobody helps with rewrite the documentation. 

> When new library is made you must close/reopen Qucs-S to access it. Can this be resolved

I will look what could be done.

**Comment by Rmano** [comment]
> This guide about libraries and subcircuits needs a translation: https://habr.com/ru/articles/805963/ See #554 Unfortunately nobody helps with rewrite the documentation.

I know zero of russian, but google can autotranslate the thing and I can volunteer (with a bit of patience, I have not a lot of time on my hand --- fortunately later circuitikz seems to be quite quiet) to adapt it. 

Is there a framework/style/master document to adhere to? I've looked at #554 but it seems a bit confused. Should the documentation be written in LaTeX (no problem, I'll be happy to do it).

**Comment by ra3xdh** [comment]
The repository for documentation is here: https://github.com/ra3xdh/qucs_s_docs/ This link could be found in #554 There is no style guide. It uses standard `report` style. I have also created Overleaf project for Windows users: https://www.overleaf.com/project/65ed52fbd51e0623f11e285a So one can contribute ti the documentation without Github account.

**Comment by Rmano** [comment]
I do not  see those warning... and it seems to work well with mixed supplies and saturations.

But with two INA826 I have this warning:

     Warning: redefinition of .subckt ina826, ignored

Ah, this should be called AmpInstr --- it's an instrumentation amplifier, not an OpAmp 😉

![image](https://github.com/user-attachments/assets/2c8acd7c-f2e9-477e-b9cf-4a64434fe464)

**Comment by tomhajjar** [comment]
The warnings are for the subcircuit made using "SPICE netlist".

"Warning: redefinition"
ngspice doesn't like the spice file name to be the same as the internal device name. It doesn't cause problems. This goes away if you change either the file name or internal .SUBCKT name.

If you look at the attached library, it's called Instrumentation Amplifier

**Comment by ra3xdh** [comment]
The library tree update after adding a new library implemented by #1027
