### ISSUE TITLE
Simulation console screen position

### ISSUE THREAD

**Issue by tomhajjar** [ra3xdh/qucs_s#1012]
I realize this is a trivial Issue but can the Simulation console screen position be adjustable so I can see the plots without having to close or move the pop-up? Too many times I miss a subtle change in a plot/data because the plot is obscured. I know there is no optimum position. Another option is to have the pop-up size "minimized" unless a button is clicked to restore it's original size.

![2024-10-21_104601](https://github.com/user-attachments/assets/b1638319-0cad-4830-b85e-4411e3d4efba)

**Comment by ra3xdh** [comment]
It's better to let the system window manager to control the dialog windows position. The manual setting of window position has many disadvantages. Also wait unit #235 will be implemented. This will remove the *Simulation console* window and redirect all messages to the dock.

**Comment by ra3xdh** [comment]
@ainst , Yes, you may open a PR
