### ISSUE TITLE
Potentiometer value not normalized

### ISSUE THREAD

**Issue by csrabak** [ra3xdh/qucs_s#1013]
After expending half an hour with some friends I've discovered that the issue revolved around a value definition in the potentiometer component when used with Ngspice (I've not tested other simulation engines).

In a nutshell, for all lumped components Qucs-S when exporting to the netlist to be analysed by Ngspice, "joins" the SI multiplier to the component value, i. e., if we put "22 k" for a resistor, in the netlist it will exported as `22k` and so on.

However, when the potentiomenter value is exported for the equations as function of the cursor rotation the export does not do this _joining_ and a very hard-to-find bug in the simulation ensues[^1].

So I suggest the same procedure could be used for the values of this component, so the "principle of least surprise" can be considered in the Qucs-S interface.

[^1]: At least for me, so bear with. . .

**Comment by ra3xdh** [comment]
Fixed by #1014
