### ISSUE TITLE
Trans Simulation says it ran to full 10 sec but doesn't

### ISSUE THREAD

**Issue by tomhajjar** [ra3xdh/qucs_s#1017]
Testing out an old EDN Design Idea. Seeing if thermal analysis can be added to any circuit using standard BJT Spice device models.

I'm running two Trans simulations:

If TR1=300usec and TR2=3sec, TR1/TR2 Simulations look OK.
If TR1=300usec and TR2=10sec, TR1 Simulation looks OK. TR2 simulation is wrong.

TR2=4sec works but TR2=5sec doesn't work...

![2024-10-24_113148](https://github.com/user-attachments/assets/e3a43fb6-03ef-4db6-83eb-6fa749b40801)
![2024-10-24_113008](https://github.com/user-attachments/assets/f03092a7-0a26-4ed9-a96b-fdfbbb193c1f)

[Amp_BJT_thermal_prj.zip](https://github.com/user-attachments/files/17509501/Amp_BJT_thermal_prj.zip)

**Comment by ivandi69** [comment]
It works fine. You have to decrease the step (or increase the number of points). Adding .OPTION INTERP reduces the dataset size. Here is the result with tstep=2ms:
![image](https://github.com/user-attachments/assets/e4ead998-0aa9-4c61-8d67-ce653ea03def)

**Comment by tomhajjar** [comment]
Something wrong with my syntax...
Can you send file?

![2024-10-24_133642](https://github.com/user-attachments/assets/76c7a368-71e6-4b29-a07d-5450bafc2cb7)

**Comment by tomhajjar** [comment]
I'm getting strange plots for a similar circuit. The Tj2 plot for the PNP changes wildly with #points. Attached are for 5,000 and 6,000 points. 

![2024-10-24_141152](https://github.com/user-attachments/assets/8bced99d-7863-44ed-8a10-7f241d29fea5)
![2024-10-24_141017](https://github.com/user-attachments/assets/81ad6acd-c029-4a01-b6d1-352c2169ee76)

[BJT_thermal_prj.zip](https://github.com/user-attachments/files/17511157/BJT_thermal_prj.zip)

**Comment by ivandi69** [comment]
Step 50us. Using KLU as Direct Linear Solver:
![image](https://github.com/user-attachments/assets/c4767d49-885e-4524-9af7-ea7744b6c4c7)
![image](https://github.com/user-attachments/assets/5a216dc9-a299-4b3b-b573-616158a86e5f)

**Comment by tomhajjar** [comment]
I don't see KLU...
![2024-10-24_161729](https://github.com/user-attachments/assets/ca9d9e6c-6c43-4fe9-885a-06b6c8a4ac5f)
