### ISSUE TITLE
Diode symbol for Schottky is actually US symbol for Zener 

### ISSUE THREAD

**Issue by tomhajjar** [ra3xdh/qucs_s#1024]
Since the Blue Diode symbol assignment has been fixed it's a good time to mention the symbol used for a 'IEC" Schottky is actually the US symbol for a Zener... 
[schematic_symbols.zip](https://github.com/user-attachments/files/17525601/schematic_symbols.zip)

**Comment by ra3xdh** [comment]
Diode symbol fixed by #1027
