### ISSUE TITLE
Tabular diagram (table) issues - properties only accessible through double-click

### ISSUE THREAD

**Issue by njascgil** [ra3xdh/qucs_s#1033]
Using the latest continuous build of Qucs-S, I noticed that the tabular diagram properties are only accessible through double-click and not through the right-click menu (in the case of the cartesian diagram, both methods work as expected).

Additionally I would like to ask if there's any way to modify value order in these tabular diagrams, other than removing values and re-adding them by the desired order. Thanks!

**Comment by ra3xdh** [comment]
> I noticed that the tabular diagram properties are only accessible through double-click 

Yes, I confirm the problem. The RMB than click on "Edit properties" do nothing for Tabular diagram.

> Additionally I would like to ask if there's any way to modify value order in these tabular diagrams

There is no way to reorder data columns in tabular diagram. You have to delete the data and add it again.

**Comment by ra3xdh** [comment]
Fixed by #1035
