### ISSUE TITLE
Warning: QIODevice::write (QProcess): device not open

### ISSUE THREAD

**Issue by yurivict** [ra3xdh/qucs_s#104]
This warning is printed when new project is created.

**Comment by ra3xdh** [comment]
Yes, I see the same warning message on Linux too. I will provide a fix soon.

**Comment by ra3xdh** [comment]
This warning should not affect the projects operation and simulation.

**Comment by ra3xdh** [comment]
The warning came from octave process. Fixed by https://github.com/ra3xdh/qucs_s/commit/c13c8445efb760570ae5acc98b93518753e01e8b Closing
