### ISSUE TITLE
Are the Icon Arrows inverted on some of the Red and Blue Current sources?

### ISSUE THREAD

**Issue by tomhajjar** [ra3xdh/qucs_s#1040]
Are the Icon Arrows inverted on some of the Red and Blue Current sources?

![2024-11-02_130247](https://github.com/user-attachments/assets/755899b4-823b-4b89-8704-eb7dd9a687d7)

[I_kick.zip](https://github.com/user-attachments/files/17607741/I_kick.zip)

**Comment by tomhajjar** [comment]
No constancy for the arrows.

![2024-11-02_141109](https://github.com/user-attachments/assets/18b03cf7-5e21-46a9-bcf9-59d80d4c8ae7)

[I _Source_test.zip](https://github.com/user-attachments/files/17607914/I._Source_test.zip)

**Comment by ra3xdh** [comment]
The sources polarity fixed by #1059
