### ISSUE TITLE
Please add FreeBSD to installation instructions

### ISSUE THREAD

**Issue by yurivict** [ra3xdh/qucs_s#105]
Installation instructions are [here](https://ra3xdh.github.io/#inst).

To install on FreeBSD: ```pkg install qucs-s```

[port commit record](https://cgit.freebsd.org/ports/commit/?id=7609fce6eb9f4ad90a9e871dca3dc8add86c64ce)
[FreshPorts record](https://www.freshports.org/cad/qucs-s/)

**Comment by ra3xdh** [comment]
Thanks for providing the package! I will update the website and add the FreeBSD to the list of supported platforms.

**Comment by ra3xdh** [comment]
I have updated the FreeBSD installation instructions at the website. Check the https://ra3xdh.github.io/

**Comment by yurivict** [comment]
The second method ```pkg install qucs-s``` is recommended because it is faster.
It probably should be listed first.
