### ISSUE TITLE
Pulse source doesn't generate signal

### ISSUE THREAD

**Issue by yurivict** [ra3xdh/qucs_s#106]
I am trying this example that contains a PULSE source:
[double-mosfet-example.sch.txt](https://github.com/Qucs/qucs-s/files/9074404/double-mosfet-example.sch.txt)

However, there is no pulse in the simulation:
![image](https://user-images.githubusercontent.com/271906/178051493-e4224045-15e1-454a-ada2-8f73c392a504.png)

Version: 0.0.24
FreeBSD 13.1

**Comment by ra3xdh** [comment]
The pulse source by itself works as expected. There is a convergence issue with Ngspice. The simulator log shows "timestep too small" error.

**Comment by yurivict** [comment]
This is strange because the example was taken almost verbatim from the ngspice [example on their page](https://ngspice.sourceforge.io/ngspice-tutorial.html)

Is Qucs-S able to save the project in SPICE format to run it outside Qucs-S?
I couldn't find the "Export as SPICE" menu item.

**Comment by yurivict** [comment]
"Save Netlist" option exists on the Simulate page.

I'll report this to Ngspuce.

Thanks for your help!

**Comment by yurivict** [comment]
https://sourceforge.net/p/ngspice/bugs/595/

**Comment by ra3xdh** [comment]
Ngspice the most probably has no bug. You are using wrong transistor in this circuit. The BSP171 MOSFET is designed for 12V operation and for microsecond range. When I am replacing the power source and pulse duration the circuit begins to operate correctly. See the attached screenshot.
![image](https://user-images.githubusercontent.com/4920080/178093145-ee4b0d45-137e-4ac2-b35c-d824193af718.png)
