### ISSUE TITLE
Unicode characters aren't displayed properly on the 'About Qucs' screen

### ISSUE THREAD

**Issue by yurivict** [ra3xdh/qucs_s#107]
![image](https://user-images.githubusercontent.com/271906/178061983-9a018c6f-f029-42e1-81b0-250e31aa175d.png)

Version: 0.0.24
FreeBSD 13.1

**Comment by ra3xdh** [comment]
I confirm this. There is something wrong with the `QLabel` HTML content.

**Comment by ra3xdh** [comment]
Fixed by https://github.com/ra3xdh/qucs_s/commit/7970e5a70f398f3e1d2e0d949c3155252bebe8f1 Closing.
![image](https://user-images.githubusercontent.com/4920080/178093829-d3567be6-7ecc-41c5-b8ad-b7f8d36307d2.png)
