### ISSUE TITLE
When resistor's resistance is specified with space - ngspice fails

### ISSUE THREAD

**Issue by yurivict** [ra3xdh/qucs_s#108]
```6.8 k``` causes this failure:
```
Ngspice started...
warning, can't find model 'k' from line
    r1 whitenoise _net1 6.8 k
    Simulation interrupted due to error!
```

```6.8k``` works.

You might want to allow a single space optionally in the dialog box, but you should always remove it when writing SPICE.

**Comment by ra3xdh** [comment]
What resistor are you using? There are two types of resistors in Qucs-S. Blue resistor is Qucs device and spaces are allowed in the resistance value for it. The red resistors use exact SPICE syntax. According SPICE specification the model may follow after the resistance value. So the spaces before unit for the red resistors are not allowed intentionally.

**Comment by yurivict** [comment]
Red resistor is used.
