### ISSUE TITLE
Simulation window for the qucsator backend closes immediately not allowing to see the results

### ISSUE THREAD

**Issue by yurivict** [ra3xdh/qucs_s#110]
Other backends don't suffer from this problem.

**Comment by ra3xdh** [comment]
This behavior is inherited from Qucs (old Qt4 version). Probably it could be redesigned for Qucs-S.

**Comment by ra3xdh** [comment]
Fixed by https://github.com/ra3xdh/qucs_s/commit/775bdb0815ed3915580c11a4ef571384380eb142 Now all simulation dialogs have unified behavior and don't close after the simulation is finished.
