### ISSUE TITLE
Library with User selectable parameters

### ISSUE THREAD

**Issue by tomhajjar** [ra3xdh/qucs_s#1101]
I'm trying to make a Library but I'm having issues adding User selectable parameters to a "Spice netlist" device.  I searched but can't find any example of doing this. Adding User selectable parameters to a "Spice library" device works BUT they can't be made into a Qucs Library.

First device is a PBRS 7 generator. Long term goal is to add  "Systems Analysis" capabilities to Qucs-S. This will also add value to Ideal.lib and Xanalogue.lib which I doubt many use.

![2024-11-27_204129](https://github.com/user-attachments/assets/4b6b5e16-5a5b-4b03-9b9f-75e34eb02ef2)
![2024-11-27_204322](https://github.com/user-attachments/assets/511adecd-1d65-4cb5-97d1-8fcca2abcd4b)
![2024-11-27_213542](https://github.com/user-attachments/assets/dc9c1091-4421-4d8c-a590-7d2840365d08)
![2024-11-27_213522](https://github.com/user-attachments/assets/d6d40d30-5a2e-4db9-81e1-640502157dc9)

[PBRS7_subcircuit.zip](https://github.com/user-attachments/files/17942044/PBRS7_subcircuit.zip)

**Comment by ra3xdh** [comment]
I am aware about this limitation. SpiceFile device doesn't support parameters. The `.PARAM` will have no effect in this case. Wait until the SpiceLibComp extensions #944 will be implemented. There is no workaround.

**Comment by tomhajjar** [comment]
Presently under the "Qucs way" of making sub-circuits, User definable parameters MUST be on both the schematic sub-circuit and symbol sections. AFAIK on schematic param=param and on symbol param=value.

Will this be the "new" method as well?

![2024-11-28_104834](https://github.com/user-attachments/assets/f9207cb0-ce9e-4145-9dcb-2a6203835b5a)
![2024-11-28_104855](https://github.com/user-attachments/assets/d272cc7e-1915-4c62-bafb-b97b5fcc22a4)
![2024-11-28_104914](https://github.com/user-attachments/assets/f53073b3-09a0-4c5f-a191-1c77fb3df83a)

[Parameter_Passing_prj.zip](https://github.com/user-attachments/files/17950085/Parameter_Passing_prj.zip)
