### ISSUE TITLE
Sub-Circuit Pin Names once chosen cannot be easily changed

### ISSUE THREAD

**Issue by tomhajjar** [ra3xdh/qucs_s#1104]
While making a Spice library sub-circuit, I found once a Pin name is chosen, the text "case" cannot be easily changed.

I have to play "games" to say change Pin 1 from "DD" to "dD". Select "D", backspace, enter "d", Apply/Enter doesn't work.

I have to select the Pin, select "D", backspace, save, select the Pin again, enter "d" and save.

So it takes 2x the edits to change the 6 Pins.

![2024-11-30_111402](https://github.com/user-attachments/assets/004fc7c5-1372-4899-83e0-042e32d2e87d)
![2024-11-30_113549](https://github.com/user-attachments/assets/3f1b3523-076a-4c7f-87cc-8caf033706bc)

[XSPICE_PLL_prj.zip](https://github.com/user-attachments/files/17966054/XSPICE_PLL_prj.zip)

**Comment by ra3xdh** [comment]
The pins names are registry independent. The registry has no effect in SPICE and this was done to prevent assign the same name for two pins.
