### ISSUE TITLE
Projects with Libraries Stopped working after update

### ISSUE THREAD

**Issue by tomhajjar** [ra3xdh/qucs_s#1111]
The Digital Library "74HCng_gates.lib" modified by Holger using XSPICE to work in ngspice is only "partially" working after an update. Only the 1st item in the Library, 74HC00 still gets "processed" properly by "Spice library" but all others don't get assigned a Spice library "symbol". Oddly all sub-circuits previously made still work even missing the Spice library symbol but you can't make new sub-circuits.

All the PSpice Digital Libraries have the similar structure/syntax of the .SUBCKT line like this BUT don't use XPICE entries. I have to check them. Normally I make stand-alone models for each device as you requested.
.SUBCKT 74HC00  in1 in2 out  NVCC NVGND  vcc1={vcc} tripdt1={tripdt}

![2024-12-03_082013](https://github.com/user-attachments/assets/d3602e45-fbe2-4f41-9c41-c17fe7fe4f46)
![2024-12-03_082154](https://github.com/user-attachments/assets/4647c21b-07c1-4b48-8a91-4651cec2705e)
![2024-12-03_082047](https://github.com/user-attachments/assets/d9fb2998-8b65-457e-8893-305de29edb15)
![2024-12-03_082128](https://github.com/user-attachments/assets/9ae91482-0c60-4823-a4b8-d6128f58f7d2)

[Digital_Analog_Mixed_prj.zip](https://github.com/user-attachments/files/17993639/Digital_Analog_Mixed_prj.zip)

**Comment by tomhajjar** [comment]
Attached is a MOSFET with thermal project I did last month that now doesn't work. Unlike above where previously made sub-circuits still work, none work in this project.

![2024-12-03_105517](https://github.com/user-attachments/assets/8d926aef-6410-4a5d-88e9-90642c617b20)
![2024-12-03_082154](https://github.com/user-attachments/assets/e0942dcd-652c-4add-b2af-859d75744637)

[MOSFET_Si_thermal_prj.zip](https://github.com/user-attachments/files/17995664/MOSFET_Si_thermal_prj.zip)

**Comment by tomhajjar** [comment]
Here is a GaN project using a device previously used in a KiCAD/ngspice example that doesn't work anymore.

I don't remember why I made a modified version of the GaN library...and why it works...

![2024-12-03_112043](https://github.com/user-attachments/assets/bda1427c-5eb7-4431-9049-59f3ac8aa4aa)
![2024-12-03_112021](https://github.com/user-attachments/assets/0c130c3c-1a94-4f74-be47-43835b87f66a)

[GaN_thermal_prj.zip](https://github.com/user-attachments/files/17995952/GaN_thermal_prj.zip)

**Comment by ra3xdh** [comment]
Fixed by #1113 This has appeared after #1074
