### ISSUE TITLE
CI Windows issues

### ISSUE THREAD

**Issue by ra3xdh** [ra3xdh/qucs_s#1114]
I have just noticed that the MSYS2 Windows target has been excluded from CI, but remains in deploy.yml. Also this target is marked as `continue-on-error` The MSYS2 Windows target (not MSVC) should be blocking. @dsm?

![image](https://github.com/user-attachments/assets/62561afd-cbf6-4399-9dd9-6be5c8cdaad6)

**Comment by dsm** [comment]
It says 7 succesful, I think windows build also there, I didn't remove it but yes continue-on-error should be remove. if you looked latest pr for this check, I've also checked and windows build already there.

**Comment by ra3xdh** [comment]
Yes, everything found. May be some web interface issue. Closing.

![image](https://github.com/user-attachments/assets/2ec74076-8c0b-4a79-8b59-3b20da546bfc)
