### ISSUE TITLE
Digital Subcircuits with pull-up/dn resistors or vcc/gnd connections

### ISSUE THREAD

**Issue by tomhajjar** [ra3xdh/qucs_s#1115]
@ra3xdh

I can't figure out how to make sub-circuits using the PSpice Digital libraries that have pull-up/dn resistors or vcc/gnd connections unless I add Pins for vcc/gnd to the sub-circuit so they can be connected in the main schematic. The vcc net or .PARAM vcc=5 entries didn't work. Making sub-circuits using PSpice Digital libraries with vcc/gnd pins looks odd since the devices themselves don't have a "physical" vcc/gnd...

My goal is to make a Library of higher-level digital devices.

![391555117-4849b102-d048-42ef-bd30-da9e902ed082](https://github.com/user-attachments/assets/7c7d8e14-d218-45b1-8226-6464667ea976)

![391555138-d36ad3dc-785f-4727-a78f-6c61942ae243](https://github.com/user-attachments/assets/05e84544-fe7a-41ee-ae20-4e81f0486048)

[PLL_CMOS_prj.zip](https://github.com/user-attachments/files/17997563/PLL_CMOS_prj.zip)

**Comment by tomhajjar** [comment]
@ra3xdh 

Adding a source to the subcircuit with U='vcc' seems to work. 

I haven't tried doing a pull-down. I assume a connection to ground would work.

![2024-12-12_224236](https://github.com/user-attachments/assets/a28353a9-60f4-443a-99d9-92e2104fa962)
![2024-12-12_224258](https://github.com/user-attachments/assets/6b20d6ef-b0e1-41f1-a473-e3e0dc3267ab)

**Comment by ra3xdh** [comment]
Closing as answered.
