### ISSUE TITLE
Deactivate/Activate Defaults

### ISSUE THREAD

**Issue by tomhajjar** [ra3xdh/qucs_s#1116]
ngspice sometimes complains when a component is Deactivated to "Green" status meaning 0 Ohms. 

Should 0 Ohms be set to the "new" ngspice min R of 1e-12?

**Comment by ra3xdh** [comment]
Yes, the value for shorted device could be corrected depending on simulator.

**Comment by ra3xdh** [comment]
Fixed by #1161
