### ISSUE TITLE
Adding more symbols to Spice library menu

### ISSUE THREAD

**Issue by tomhajjar** [ra3xdh/qucs_s#1119]
Can the Schottky diode symbol be added to the menu? SB5100 is a Schottky diode

![2024-12-04_105039](https://github.com/user-attachments/assets/ccd214e4-2336-4f61-b543-91410e3de2cd)

**Comment by ra3xdh** [comment]
Yes, I can upload additional symbols. Is this symbol in `schematic_symbols.sch`?

**Comment by tomhajjar** [comment]
Yes. 

The latest symbol files are not included with distribution. All have been updated and tagged with date.

![2024-12-04_105719](https://github.com/user-attachments/assets/6bedbae3-27f6-4d53-a3c3-ff1fcf827b1e)

[Symbol_Creation_prj.zip](https://github.com/user-attachments/files/18011020/Symbol_Creation_prj.zip)

**Comment by tomhajjar** [comment]
One requirement of "Blue" devices is the Reference Designation starts with a "fixed" Letter like "D" for the Diode and SHOULD have an underscore "_" at the end for device numbering. A new User wouldn't know this.

![2024-12-04_121445](https://github.com/user-attachments/assets/bf879750-bd64-4213-9832-de1943c05686)

[Rectifiers_prj.zip](https://github.com/user-attachments/files/18011894/Rectifiers_prj.zip)

**Comment by ra3xdh** [comment]
Fixed by #1161
