### ISSUE TITLE
Add background when rendering DC bias labels

### ISSUE THREAD

**Issue by jgardona** [ra3xdh/qucs_s#1121]
Hello, good morning.

Dc bias calculation doesnt render correctly the values in the circuit. The values are rendered abouve the circuit wires, and it hasnt a background color(maybe same color of the circuit windows? ). In the Ampmeter, the same issue also happens. 
I think, the way that qucs studio works would be fit.

Im using windows 11 64x and qucs 24.4.1

**Comment by ra3xdh** [comment]
Please submit a screenshot illustrating this issue. I didn't change the DC bias rendering in the recent release.

**Comment by jgardona** [comment]
> Please submit a screenshot illustrating this issue. I didn't change the DC bias rendering in the recent release.

I im doing it now. Must install again.

**Comment by jgardona** [comment]
Here it is:

in Qucs-S
![image](https://github.com/user-attachments/assets/6591d8d7-9a6f-4bf2-9aeb-241abb0b037a)

![image](https://github.com/user-attachments/assets/fec69a98-4d19-4683-a0b2-4d8c3d6f4f1b)


in Qucs Studio

![image](https://github.com/user-attachments/assets/97f21ac2-83a9-441a-8814-4049e8d2d501)

**Comment by ra3xdh** [comment]
It is a long known issue. Qucs-S and old Qucs always rendered DC bias in a such way. May be adding a background to the DC bias result will improve the readability. We will consider making this modification. QucsStudio is maintained by another developer and the source code has diverged from Qucs and Qucs-S a years ago.

**Comment by jgardona** [comment]
> It is a long known issue. Qucs-S and old Qucs always rendered DC bias in a such way. May be adding a background to the DC bias result will improve the readability. We will consider making this modification. QucsStudio is maintained by another developer and the source code has diverged from Qucs and Qucs-S a years ago.

Yep. Using a background color in font(I think the same as the background of the board), will definitelly improve the readability.

**Comment by dsm** [comment]
I made some changes if it's OK, I'll sent PR. I modified value 4 point precision(but can be set or adding settings.) and ex convert 1.33000mA to 1.33mA and 1.0000mA to 1mA

![image](https://github.com/user-attachments/assets/0b9cc4fd-21a6-43fa-be84-8e7b6e083868)

![image](https://github.com/user-attachments/assets/3e326199-deaf-4f0d-b85b-7002f304bb8c)

**Comment by ra3xdh** [comment]
It may be useful to introduce a setting named like *Transparent DC bias lables ON/OFF*.

**Comment by jgardona** [comment]
Its very good in my opinion. The colors are beautiful.

**Comment by dsm** [comment]
I tested, here is the result. Yes, we can add a transparency settings.
Before:
![image](https://github.com/user-attachments/assets/73309992-4784-4ff1-a616-fcace3263c27)

After:
![image](https://github.com/user-attachments/assets/fe3c1954-20df-4be3-b38d-64061c9cc944)

**Comment by jgardona** [comment]
Thats way more suitable to read.

**Comment by ra3xdh** [comment]
Fixed by #1130
