### ISSUE TITLE
Simulation ran amok and created a corrupted data file crashes Qucs-S

### ISSUE THREAD

**Issue by tomhajjar** [ra3xdh/qucs_s#1127]
A PLL simulation "10M_PLL_dosc_vco.sch" went amok and consumed all my PCs resources so I was forced to stop the simulation. It used up all 16GB of RAM and wrote a huge multi-GB file to spice4qucs. The resulting corrupted  "null" data file "10M_PLL_dosc_vco.dat.ngspice" crashes Qucs-S when the schematic is opened. 

Why the simulation runs amok I cannot say. I've made many changes to try and speed simulation including replacing the vco and 10M ref with simpler models.

Based on the DuSpice results showing the integrator hitting the "top" rail meaning no PLL lock so I made "10M_PLL_dosc_vco_180.sch" which flips input to phase comparator.  Under Qucs-S it ran for a very long time before Qucs-S crashed and closed. Under DuSpice the simulation ran in a reasonable time but the integrator hit the "bottom" rail again meaning no PLL lock. There are other issues in the design. The charge-pump section was just lashed together and may have issues. I haven't gotten answers to my questions.
https://sourceforge.net/p/ngspice/discussion/120973/thread/feab67cd8f/ 

I then "opened" the loop feeding the VCO with 2.5 volts. The simulation ran under DuSpice without issue but took an extremely long time under Qucs-S. Qucs-S spent more time writing it's huge data files (see attached) than DuSpice did running the simulation and plotting the results. I believe the ngspice simulation times are the same but DuSpice is an order of magnitude faster "processing" the "data" than Qucs-S.

All the netlists run under DuSpice finished in a reasonable time frame. The netlists "10M_PLL_dosc_vco_xxx.cir" "call" "VCO_dosc_5-15M.cir" and use the included .spiceinit. I made a narrow band VCO, 9-11MHz I haven't tried yet.

![2024-12-07_003817](https://github.com/user-attachments/assets/5e443973-c180-4fab-8acf-47b2789b641a)
![2024-12-07_101047](https://github.com/user-attachments/assets/709f8cd7-3f94-4ca7-a6dc-e20785d8af52)
![2024-12-07_101550](https://github.com/user-attachments/assets/402bafab-caaf-4b0d-8831-f7ef7e7b152f)
![2024-12-07_101337](https://github.com/user-attachments/assets/0311c180-4ff2-41db-ace8-65074bf45363)
![2024-12-07_095352](https://github.com/user-attachments/assets/34b5e512-3708-425b-a49c-a665bfabba47)
![2024-12-07_095930](https://github.com/user-attachments/assets/ccf43e8e-7007-46de-aedc-08704f5bfb0a)
![2024-12-07_103310](https://github.com/user-attachments/assets/b14f969b-ba5b-4e3f-9a97-85ac39593021)

**Comment by ivandi69** [comment]
You have to add .OPTION INTERP to reduce the dataset size. And you have to increase the number of points to have more details.
[10M_PLL_dosc_vco.sch.txt](https://github.com/user-attachments/files/18049382/10M_PLL_dosc_vco.sch.txt)

![image](https://github.com/user-attachments/assets/7fe8e279-02c4-4fef-aed1-b854796a0a98)

**Comment by tomhajjar** [comment]
The netlists sent to the DuSpice GUI don't have those changes. Do you know why the netlists work?

**Comment by ivandi69** [comment]
KLU is supposed to be faster. Sparse works fine too. The netlists work in Qucs-s too. Ngspice runs fine and produces a huge plot. Qucs-s needs a lot of resources to process that huge plot.

**Comment by tomhajjar** [comment]
Using DuSpice doesn't use up all 16GB of my RAM and crash. Qucs-S is using more RAM running the same simulation as DuSpice.  I have to use Task Manager to monitor resources and kill Qucs-S before I get a RAM warning.

For these PLL simulations:
After ngspice finishes, DuSpice plots almost immediately.
After ngspice finishes,  Qucs-S can take a huge amount of time writing from RAM to the HD before doing the plots.

**Comment by tomhajjar** [comment]
Made progress. I accidently set the VCO output to 1 instead of 5 volts. Also made a narrow-band VCO that is 10MHz at 2.5 volts. PLL is hunting and locking over a narrow range. The project is good enough to use as an example.

Will do more comparisons with DuSpice.

![2024-12-07_181941](https://github.com/user-attachments/assets/27dad2ba-ec59-4027-a985-30d31de2319c)

[PLL_CMOS_prj.zip](https://github.com/user-attachments/files/18050221/PLL_CMOS_prj.zip)

**Comment by ra3xdh** [comment]
The Qucs-S cannot look forward and predict the dataset size. It is on the user. This issue cannot be fixed on Qucs-S side.

**Comment by tomhajjar** [comment]
The issue was the netlist sent to DuSpice didn't have the same effect on my PC.

ngspice takes the same time to do the simulation using Qucs-S or DuSpice. It's after the ngspice is done. DuSpice handles large data files more efficiently. It doesn't take minutes to pot the data like Qucs-S.

As I made modifications to the PLL circuit, the data files got smaller.
