### ISSUE TITLE
Clock frequency using Qucs Rectangular Source versus Spice Pulse Source

### ISSUE THREAD

**Issue by tomhajjar** [ra3xdh/qucs_s#1132]
I made two clock sources. One using Qucs Rectangular Source and the other using Spice Pulse Source. I can't figure out why the one made with Qucs Rectangular Source generates the wrong frequency.

Since both use the Spice Pulse function why is the one I made using "Qucs" wrong? Is the mapping of Qucs parameters to Spice wrong or are my formulas wrong?

![2024-12-11_223503](https://github.com/user-attachments/assets/dbecda5d-6699-4da6-aa52-0ac22dadcacd)
![2024-12-11_223548](https://github.com/user-attachments/assets/acd5f266-0aa4-4d26-bbf2-571ae1134cb5)

[Waveforms_prj.zip](https://github.com/user-attachments/files/18105223/Waveforms_prj.zip)

**Comment by ra3xdh** [comment]
Everything is correct. The period for Qucs source is calculated as `PER=TH+TL+TR+TF`. If gives `2*0.5/1e7+1e-9+1e-9=1.02e-7` The calculation in the CIR file is different. Please fix your equations in the subcircuit to take into account TR and TF.

**Comment by tomhajjar** [comment]
Actually they were both wrong. I had to fix clock.cir as well...

![2024-12-12_111821](https://github.com/user-attachments/assets/29305834-f5a3-4a1a-910a-a92a10d6422d)

[Waveforms_prj.zip](https://github.com/user-attachments/files/18114485/Waveforms_prj.zip)
