### ISSUE TITLE
[feature suggestion] Interactive simulation

### ISSUE THREAD

**Issue by yurivict** [ra3xdh/qucs_s#114]
When the simulation is open the user should be able to click on any wire and this should seamlessly add simulation result for this wire to the simulation graph.

This is an intuitive way to explore circuits for users.

**Comment by ra3xdh** [comment]
MicroCAP has the similar feature called probing. The user can pick the wire with mouse click and plot the graph after the simulation. In principle it is possible to implement this feature in Qucs but at the current time I have more important tasks like #92, #94 and #97 So I can consider implementation of this only in the far future.
