### ISSUE TITLE
Add spiceinit to Windows distribution

### ISSUE THREAD

**Issue by Radvall** [ra3xdh/qucs_s#1140]
I tried to simulate the following circuit with the OpAMP LM358 from Libraries -> SpiceOpamp.

![circuit](https://github.com/user-attachments/assets/1a896df9-dac2-4d75-98e4-a128223fe40c)

For simulation I use Qucs-S-24.4.1 with ngspice installed from https://github.com/ra3xdh/qucs_s/releases/download/24.4.1/Qucs-S-24.4.1-setup.exe

The default path for ngspice is shown in the figure below:

![setup_sim_location](https://github.com/user-attachments/assets/27c68215-5a21-464c-8a06-95116a6b73f4)

I found an old discussion about ngspice's location on Windows here: https://sourceforge.net/p/ngspice/discussion/127605/thread/4c758f87/ and downloaded ngspice from sourceforge  and unpacked it in C:/Spice64/.

The circuit works as expected.

![works](https://github.com/user-attachments/assets/48052edf-c09f-444e-8b1a-db9c2536a0b0)

The executable location is shown in the figure below.

![setup_sim_location1](https://github.com/user-attachments/assets/04f3ad86-ee45-4c24-a8b8-026bc108a43a)

**Comment by dsm** [comment]
can you uninstall and install the latest continuous build and test is again please.

**Comment by dsm** [comment]
I found a problem I can provide a fix.

**Comment by dsm** [comment]
ngspice needs this file `"Spice64\share\ngspice\scripts\spinit"` but we didn't include `\share\ngspice\scripts\` folder to qucs-s I'll add this folder to release thanks.

**Comment by tomhajjar** [comment]
@Radvall 

The installation instructions for Windows are obsolete. I put ngspice in folders labeled by revision. I have multiple versions of ngspice installed and change the Simulator Settings for ngspice when I want to use a different version.

The use of .spiceinit in Windows should be done by placing the statement on the schematic. 

Alternatively a .spiceinit ASCII file can be placed in the ngspice bin folder or Windows User folder. Unfortunately that specific .spiceinit will be used every simulation which can cause some simulation to fails. I only put a .spiceinit in the ngspice bin folder when running ngspice outside of Qucs-S. I then delete it when done. 

![2024-12-16_081136](https://github.com/user-attachments/assets/70f6a77b-9cb5-4aba-9822-31f305036448)
![2024-12-16_080648](https://github.com/user-attachments/assets/c261f252-389f-4ed4-be1b-5758e21a4713)
![2024-12-16_081655](https://github.com/user-attachments/assets/fbe0d709-d051-4b13-aba6-b8df5925324d)

**Comment by dsm** [comment]
putting inside .spiceinit and sim should work.

```
if $?xspice_enabled
 codemodel ../lib/ngspice/spice2poly.cm
end
```

**Comment by tomhajjar** [comment]
Since .spicinit isn't needed for this Library, why was it brought up?

![2024-12-16_084254](https://github.com/user-attachments/assets/4696290d-18b8-4bc8-a218-fa7cb75facaf)

**Comment by dsm** [comment]
Error on line:
  a$poly$e.xop1.egnd %vd [ _net1 0 _net2 0 ] %vd ( xop1.99 0 ) a$poly$e.xop1.egnd
 MIF-ERROR - unable to find definition of model a$poly$e.xop1.egnd
    Simulation interrupted due to error!
    
    it gives this error

**Comment by dsm** [comment]
@tomhajjar in model file uses POLY(), if I am not wrong it depends Xspice

**Comment by tomhajjar** [comment]
I have multiple XSPICE projects and none need a .spiceinit. What am I missing?

**Comment by dsm** [comment]
can you remove spinit file in ngspice's share/scripts folder ?

**Comment by tomhajjar** [comment]
The only .spiceinit files in the Windows ngspice release are in the examples folder.

In Windows, .spiceinit is only used if placed in 3 directories, "working", User and ngspice\bin

**Comment by ra3xdh** [comment]
Fixed by #1141

**Comment by dsm** [comment]
@tomhajjar 

it uses this file if I remove this then sim failed.

![image](https://github.com/user-attachments/assets/ae6fb1ff-1cf3-4604-8682-84718fb572b8)

**Comment by tomhajjar** [comment]
So "spinit" not "spininit"

**Comment by dsm** [comment]
if ngspice don't find this file but you put .spiceinit in schematics. it gives this warning.

`Warning: can't find the initialization file spinit.`
