### ISSUE TITLE
Qucs-S won't allow single pin netlists unless a variable is on the .subckt line

### ISSUE THREAD

**Issue by tomhajjar** [ra3xdh/qucs_s#1142]
For Qucs to accept a device netlist with a single pin there must be "additional text" on the .subckt line

.subckt example1 1 2                ;OK
.subckt example2 1                   ;BAD
.subckt example3 1 Value=1     ;OK

I'm forced to add "dummy" pins to single pin netlist that don't connect to anything. If single pin netlist has a variable, Qucs accepts it and the sub-circuit works. 

This is especially true with XSPICE components with no ground or power pins. I'm forced to add a dummy pin or a variable that may never be changed.

**Comment by ra3xdh** [comment]
Could you submit a single pin netlist example for testing? Which device (*Spice File* or *Spice library Device*) are using with single pin device?

**Comment by tomhajjar** [comment]
Here are examples using netlists with an XSPICE code model to make subcircuits of "digital" pull-up/dn. I had to add a "dummy" pin because Qucs-S wouldn't accept the netlists with 1 pin. I probably could have added parameter passing but that seemed confusing.

[XSPICE_Digital_prj.zip](https://github.com/user-attachments/files/18269867/XSPICE_Digital_prj.zip)

Here is examples where single pin subcircuits work to make "analog" pull-up/dn. Qucs-S didn't care the subcircuits had 1 pin.

[Digital_LV_prj.zip](https://github.com/user-attachments/files/18269886/Digital_LV_prj.zip)

**Comment by ra3xdh** [comment]
Fixed by #1162
