### ISSUE TITLE
Tools cannot be launched

### ISSUE THREAD

**Issue by ra3xdh** [ra3xdh/qucs_s#1146]
The tools cannot be launched at some conditions. It may appear after #1124. The `QucsSettings::BinDir` needs a separator on the end, or its usage must be revised everywhere. The error message is following. It indicates the missing separator. @dsm, Please have a look. 

![image](https://github.com/user-attachments/assets/63f65b99-1ec7-4747-9c47-233efe330545)

**Comment by dsm** [comment]
Thanks I'll look at it.

**Comment by ra3xdh** [comment]
Fixed by #1147
