### ISSUE TITLE
Using Subcircuit Properties 'display in schematic' Issue

### ISSUE THREAD

**Issue by tomhajjar** [ra3xdh/qucs_s#1149]
Using Subcircuit Properties 'display in schematic'  check deletes all entries on line when Apply clicked

![2024-12-20_103541](https://github.com/user-attachments/assets/0ed38485-a9fe-4dd2-a8bd-1648bfa27570)

[Divider.zip](https://github.com/user-attachments/files/18212771/Divider.zip)

**Comment by ra3xdh** [comment]
I confirm this bug.

**Comment by ra3xdh** [comment]
Fixed by #1162
