### ISSUE TITLE
Inconsistent CR+LF/LF in cmake files

### ISSUE THREAD

**Issue by yarda** [ra3xdh/qucs_s#115]
E.g. the CMakeLists.txt in the main directory has CR+LF, the rest seems to have only LF.

qucs-s-0.0.24

**Comment by ra3xdh** [comment]
Fixed by https://github.com/ra3xdh/qucs_s/commit/184dae24cb897070fa0bde386d2e6150a46afc9a Now should be Unix line ending everywhere.
