### ISSUE TITLE
FFT in mixed signal Analysis

### ISSUE THREAD

**Issue by tomhajjar** [ra3xdh/qucs_s#1150]
Is there a way to do an FFT on a specific vector in without using a Nutmeg Script?

The Qucs-S FFT and Four analysis won't let you pick a specific vector so analysis fails when "digital" data is encountered.

PS

Analysis and Plotting of this circuit via DuSpice/ngspice takes maybe 30 seconds without INTERP while Qucs-S and my PC grind to a halt for minutes "processing" the same data AFTER ngspice is done. Using INTERP lessens the time a little but is still far slower than DuSpice. In some cases INTERP adds "artifacts" to the plots making them unusable.

Also Qucs-S becomes so sluggish it becomes unusable and I'm forced to close the schematic, delete it's data file and start over...

![2024-12-21_123728](https://github.com/user-attachments/assets/73793637-c7af-41e8-b9f9-d80e08a394b5)
![2024-12-21_123920](https://github.com/user-attachments/assets/71612f39-03af-402e-8933-d470771855de)

**Comment by gatk555** [comment]
I think part of the problem may be similar to #1138: the digital nodes cause ngspice to return a raw file that QUCS-S cannot parse.  And the sluggishness could be caused by ngspice eating all your system memory.  There may be a single fix for both: put "esave none" into a .control section of the the netlist.  Or "pre_esave none" you do not fully control the order of commands.

**Comment by tomhajjar** [comment]
What Qucs-S "Spice netlist section" function should I use for "esave none" or "pre_esave none"?

I use Task Manager to monitor resources and the biggest offender is Qucs-S. ngspice finishes "most" XSPICE mixed simulations in a reasonable time and then Qucs-S spends 10x more "processing" the data. If I use DuSpice there is no delay once ngspice has finished, plotting is immediate.

**Comment by ra3xdh** [comment]
Try to use the Nutmeg script simulation for this simulation type.
