### ISSUE TITLE
GNL Source Icon Arrow Wrong Direction

### ISSUE THREAD

**Issue by tomhajjar** [ra3xdh/qucs_s#1156]
The GNL Source Icon Arrow is Flipped

#1059 fixed most arrow issues

![2024-12-25_062407](https://github.com/user-attachments/assets/b1ddaa5d-8c07-48a7-ac9f-d13ae3b49fe7)

[Waveforms_prj.zip](https://github.com/user-attachments/files/18245683/Waveforms_prj.zip)

**Comment by ra3xdh** [comment]
Fixed by #1161.
