### ISSUE TITLE
Can be added inductor and capacitor non-ideal models ? 

### ISSUE THREAD

**Issue by dsm** [ra3xdh/qucs_s#1158]
Hi, LTspice has these options to adding easily non-ideal model parameters for inductors and capacitors to simulate frequency response more accurately. 

![image](https://github.com/user-attachments/assets/ccdd090c-0d20-4db0-9f84-f1a793b9197e)
![image](https://github.com/user-attachments/assets/cff31804-7136-4120-a7e6-075ff86a3dbf)

**Comment by ra3xdh** [comment]
It is already implemented a long time ago. There exists INDQ and CAPQ devices. The resistance is defined using the Q-factor which is more common for RF circuits analysis. See #143

**Comment by dsm** [comment]
Oh ok but is it possible to add non-file spice device to schematics?

**Comment by dsm** [comment]
@tomhajjar thanks for the example

**Comment by andresmmera** [comment]
You can download s-par and pspice data from Murata and Coilcraft sites.

I've collected some models here [1]. Take a look to [2] too, I have some examples there.




[1] https://rfdesigntools.pythonanywhere.com/libraries

[2] https://rfdesigntools.pythonanywhere.com/MurataRF_filter

**Comment by dsm** [comment]
@andresmmera thanks for the examples. I'll look into these.

**Comment by tomhajjar** [comment]
@andresmmera

Can you include some of the subcircuits used to make the libraries?

**Comment by andresmmera** [comment]
You can download the libraries from the links above.

I simply copied the pspice of the parts I needed from the vendor site and pasted that into a library.

**Comment by tomhajjar** [comment]
You didn't make a subcircuit for each device using "Spice netlist" and then use the Create Library function?

**Comment by tomhajjar** [comment]
I have a number of Libraries to make that use parameter passing (74xx, XSPICE analog/digital, PLL..etc) and it seems manually making the Libraries is the only option for now. Is there an example somewhere on how to do this? 

The thought of manually making hundreds of devices into Libraries is not pleasant....

**Comment by ra3xdh** [comment]
Closing as answered.
