### ISSUE TITLE
Crash if digital simulation contains subcircuit

### ISSUE THREAD

**Issue by tomhajjar** [ra3xdh/qucs_s#1166]
Should Qucs-S close even when in Qucsator mode?

[Digital_4bit_Adder_qucs_prj.zip](https://github.com/user-attachments/files/18276681/Digital_4bit_Adder_qucs_prj.zip)

**Comment by ra3xdh** [comment]
It is a bug. Fixed by #1167. This PR also contains the fixes related to wrong GHDL syntax.
