### ISSUE TITLE
PSpice VSWITCH function inside MOSFET model

### ISSUE THREAD

**Issue by tomhajjar** [ra3xdh/qucs_s#117]
I ran into issues trying to use some power MOSFET models. One issue is PSpice compatibility. What is the procedure in Qucs-S to command ngspice into PSpice compatibility?

**Comment by tomhajjar** [comment]
What is the way to pass "set ngbehavior=ps" to ngspice?

**Comment by tomhajjar** [comment]
Figured it out...

https://github.com/ra3xdh/qucs_s/pull/26

**Comment by ra3xdh** [comment]
Yes, the special spiceinit device is designed to pass some custom parameters to `.spiceinit` file.
