### ISSUE TITLE
[question] How to add transistors that aren't in the list?

### ISSUE THREAD

**Issue by yurivict** [ra3xdh/qucs_s#118]
I tried to add the ```2N5484``` transistor. It is quite common, but it doesn't appear in the list. How to add such transistor?

**Comment by ra3xdh** [comment]
You need to use `.MODEL` component. It could be found at the *Spice specific sections* group. This component could contain the SPICE modelcard.
![image](https://user-images.githubusercontent.com/4920080/179196948-10dfba93-a827-41db-b762-a2490fd3d5e0.png)

**Comment by yurivict** [comment]
This way there would be a lot of .MODEL elements in the schematics.

I think Qucs-S should contain the database of transistors like below, and should just allow the user to select it by the model:
![image](https://user-images.githubusercontent.com/271906/179346827-4ad47036-d9ec-4540-9468-ba1bf3e1ac44.png)

**Comment by ra3xdh** [comment]
> This way there would be a lot of .MODEL elements in the schematic.

This is done intentionally and allows to embed the models in schematic and to distribute schematic alone without the `*.lib` file.

> I think Qucs-S should contain the database of transistors like below, and should just allow the user to select it by the model:

If you don't like using models, You can use the `.INCLUDE` pseudo device instead. It contains reference to the model library.
![image](https://user-images.githubusercontent.com/4920080/179347002-a90cf988-c5d4-4868-879e-ac7b2f78f32b.png)

**Comment by yurivict** [comment]
You can include all models in the schematic without showing them in the window. This overcrowds the window.

**Comment by ra3xdh** [comment]
I have added a commit https://github.com/ra3xdh/qucs_s/commit/1ac7450f3ef8625d823fab48a814cf6da2c318a5 resolving this issue. Now all model lines except the first line containing model name are hidden when the model is dragged from the library.
![image](https://user-images.githubusercontent.com/4920080/184470979-ae70eda0-72d3-41b1-b78d-48bd51fe62b3.png)
