### ISSUE TITLE
Save .OP simulation result to dataset

### ISSUE THREAD

**Issue by tomhajjar** [ra3xdh/qucs_s#124]
Is there a reason Qucs-S won't do a simple DC operating point (.op)? Qucs does it and I assume ngspice will do it as well. 

If I add say a DC Parameter Sweep it does work.  

[Test_prj.zip](https://github.com/ra3xdh/qucs_s/files/9222783/Test_prj.zip)

**Comment by ra3xdh** [comment]
I know about this problem. Qucs-S currently supports only F8 mode to show the .OP result. The single DC simulation device has no effect and the operation point is not saved to the dataset. See also #3

**Comment by ra3xdh** [comment]
Combined with #3

**Comment by ra3xdh** [comment]
Fixed via #513
