### ISSUE TITLE
AC simulation: phase isn't provided?

### ISSUE THREAD

**Issue by denizzzka** [ra3xdh/qucs_s#125]
Hi,

it seems, qucs-s does not provides information about phase of value at specific frequency during AC simulation, so it cannot be displayed on the chart

ngspice driven by KiCAD does this, so I think here is just forgotten something

**Comment by ra3xdh** [comment]
It is not a bug. The AC simulation result is represented as the complex numbers (Re+j*Im) form by Ngspice. The KiCAD converts it to the Magnitude/Phase represenetation automatically. But Qucs-S preserves the complex number form to enable plotting of the curves on complex plane or Smith diagrams. You need to use the equations to extract the phase. See at the attached screenshot for example (the second equation). 
![image](https://user-images.githubusercontent.com/4920080/181877584-c28b9ea6-c668-48d8-a850-811c702374ca.png)

**Comment by denizzzka** [comment]
Thank you!
