### ISSUE TITLE
Spice FET symbols

### ISSUE THREAD

**Issue by tomhajjar** [ra3xdh/qucs_s#128]
Previously I asked about having the correct Spice symbols for N/P enhancement and depletion power MOSFETs with 3 pins, (D-G-S) to match up with Spice models provided by manufacturers. The symbols exist in the Qucs legacy library but don't lend themselves to using Include...libraries. 

Another issue is identifying the Source lead of the Spice symbols for N/P MOS and JFET. The old Qucs method added a slash on the Source pin. Am I to assume the text near the pin always means Source?

EDIT from @ra3xdh 

The following new symbols need to be added to resolve this issue and not to break backward compatibilty. I cannot introduce a new parameter for existing symbols because the *.sch may loose the backward compatibility:

- [x] NMOS 3-pin (X)
- [x] PMOS 3-pin (X)
- [x]  NMOS 4-pin (X)
- [x]  PMOS 4-pin (X)

And the existing symbols should be corrected:
 - [x] Add slash on source pin for JFET

![2022-08-04_223515](https://user-images.githubusercontent.com/102838604/182991031-da37e878-6037-4d6c-b5c9-4d53a32edefa.jpg)

**Comment by ra3xdh** [comment]
> Another issue is identifying the Source lead of the Spice symbols for N/P MOS and JFET

Yes, the source pin for the SPICE JFET is the pin with the "NJF/PJF" text. I can correct the symbol and add slash on source pin to unify the symbol view.

> The symbols exist in the Qucs legacy library but don't lend themselves to using Include...libraries

The symbols from libraries (*.lib) files is not related to the symbols on the left panel and cannot be directly used as the system symbols. It's need to add new devices to implement the 3-pin MOSFET. Another problem is that such MOSFETS are not represented as MOSFET device (M letter) but as subcircuit (X device). Also some PDK for IC design like Google Skywater may define the 4-pin MOSFETS as the subcircuit device (X),  It's need to define the following new symbols:

* NMOS/PMOS 3-pin letter X
* NMOS/PMOS 4-pin letter X

**Comment by ra3xdh** [comment]
I have added slash on source pin of the MOSFET symbols.
![image](https://user-images.githubusercontent.com/4920080/184477381-e02cb13e-5a28-4751-a0c6-3ab1fc14cab2.png)

**Comment by ra3xdh** [comment]
I have added all required MOSFETs by the commit https://github.com/ra3xdh/qucs_s/commit/aa8996e4971ba9daaa544e0ee63f7c40c425177c Now all combinations of 3/4pin M/X devices should be available. The attached screenshot illustrates the usage of the 3-pin MOSFET symbol for VDMOS device simulation according Ngspice manual.
![image](https://user-images.githubusercontent.com/4920080/184497571-5282c332-805c-407f-a0b6-b53d37b45b35.png)
![image](https://user-images.githubusercontent.com/4920080/184497642-89e28eea-c0a1-4023-ac15-b29685618314.png)

**Comment by tomhajjar** [comment]
So the added devices include both depletion and enhancement mode devices? 

Enhancement mode 3-terminal n/p power Mosfets most popular. 

Depletion mode 3-terminal n-channel power Mosfets have become common.

**Comment by ra3xdh** [comment]
I am not inclined to add a separate symbols for enhancement/depletion devices. Ngspice shares the same `.MODEL` syntax for both MOSFET types and some proprietary software also use the common symbol for all MOSFETs. If we add a separate symbol for depletion and enhancement devices there will be 16 symbols. This will overcrowd the components panel and may be misleading for users.
