### ISSUE TITLE
Library example stopped working

### ISSUE THREAD

**Issue by tomhajjar** [ra3xdh/qucs_s#136]
A library used in the online Help stopped "working" after one of the Qucs-S releases. On a whim I decided to get it working again. 

https://qucs-s-help.readthedocs.io/en/latest/RF.html

For whatever reason the library included 2 Temp coefficient variables yet did not use them in any calculations. I deleted any text with the following below and cleaned up the text in the menus. 

Tc1="0.0" Tc2="0.0" tnom="26.58" temp="26.58"
rmod (tc1={tc1} tc2={tc2} temp={temp})
.MODEL rmod r (tnom = {tnom})

Attached are the original files from the schematics/ngspice folder as well as the corrected ones. RFLumpedComponents.lib should go in user_lib. I didn't delete and replace the 2 parameter generating resistors in the original files since that requires redoing all the "nodes". Qucs won't allow copy and paste of multiple nodes.

[Qucs-S Resistor_RF-Models_prj.zip](https://github.com/ra3xdh/qucs_s/files/9355522/Qucs-S.Resistor_RF-Models_prj.zip)

![2022-08-16_204530](https://user-images.githubusercontent.com/102838604/185010714-c0d904c3-ab71-4c94-9be4-08944449019e.jpg)
![2022-08-16_204552](https://user-images.githubusercontent.com/102838604/185010716-7ffd9307-563e-48a8-a0b9-c8309b2455e1.jpg)

**Comment by ra3xdh** [comment]
Yes, the library and schematic on this example were desynchronized. I have uploaded an updated example based on your project.
