### ISSUE TITLE
"BJT" examples in schematic\ngspice folder

### ISSUE THREAD

**Issue by tomhajjar** [ra3xdh/qucs_s#137]
I tested and cleaned up the "BJT" examples in schematic\ngspice folder. 

All simulated as shown in the online Help except "BJT-noise.sch". 

The noise level are orders of magnitude higher than shown in the Help. Either I made a typo or something is wrong...

https://qucs-help.readthedocs.io/en/spice4qucs/ASim.html

[BJT_examples_ngspice.zip](https://github.com/ra3xdh/qucs_s/files/9365892/BJT_examples_ngspice.zip)
![2022-08-17_161850](https://user-images.githubusercontent.com/102838604/185237067-ce811326-a8fd-4bf5-905b-922d223a55ee.jpg)
![2022-08-17_161916](https://user-images.githubusercontent.com/102838604/185237070-8b8d0cfa-e51b-442e-8005-ddb9585364f0.jpg)

**Comment by ra3xdh** [comment]
Thanks for checking the BJT examples! I have also found that the model sweep syntax `T1.Bf` in `BJT_dc.sch` is broken. I have added a fix on the `current` branch. I will replace the examples in Qucs-S distribution to keep in up-to-date with the latest Ngspice. 

> The noise level are orders of magnitude higher than shown in the Help

I am obtaining the same values for `inoise` and `onoise`. The dataset produced by Ngspice is parsed correctly. The screenshot in the Help was taken from Ngspice verision 24 almost 7 years ago. Ngspice team has updated the noise simulation algorithm. And result may be different.

**Comment by tomhajjar** [comment]
Is BJT_dc_ngspice.sch working properly using the sweep parameter @mod2N2222A[BF]?

![2022-08-18_075938](https://user-images.githubusercontent.com/102838604/185389494-70d181fb-18a0-483c-9573-9353bcf6d7d9.jpg)

**Comment by tomhajjar** [comment]
I just noticed that I2 in BJT_dc.sch is backwards. Does this effect your comment? If I flip it, the plot looks like BJT_dc_ngspice.sch. 

![2022-08-18_081856](https://user-images.githubusercontent.com/102838604/185393604-73dacb7f-0ec2-4e17-8192-15ddc23459b1.jpg)

Is BJT_dc_ngspice.sch working properly using the sweep parameter "@mod2N2222A[BF]"? 

In another example for xyce in web Help, the parameter is "mod2N2222A[BF]". If I remove the "@" ngspice crashes. 

![2022-08-18_075938](https://user-images.githubusercontent.com/102838604/185393738-005cacf4-b661-48b7-bdf3-e74d2df12a73.jpg)

**Comment by tomhajjar** [comment]
Here is the xyce example. Can you explain why the online examples like below use a voltage source as the base drive?

![2022-08-18_082804](https://user-images.githubusercontent.com/102838604/185394844-9db0b5e8-94bb-4ee9-9a6a-70a418320e1d.jpg)

**Comment by ra3xdh** [comment]
> I just noticed that I2 in BJT_dc.sch is backwards. Does this effect your comment?

Yes, the current source polarity on this schematic was wrong. It outputs a proper IV-curve after the flipping the source.

> Is BJT_dc_ngspice.sch working properly using the sweep parameter "@mod2N2222A[BF]"?

Yes, this example is outdated. It requires the setting of the `SweepModel=True` parameter to work properly.

![image](https://user-images.githubusercontent.com/4920080/185396964-ff50b615-f44f-4a5c-b8c5-638928363aee.png)

> Here is the xyce example. Can you explain why the online examples like below use a voltage source as the base drive?

The circuit with voltage source is technically correct and will converge. But you need to set the current source to obtain the proper IV-curves family. I cannot explain the intention of the author of this example to include the voltage source instead of current source.

**Comment by ra3xdh** [comment]
> In another example for xyce in web Help, the parameter is "mod2N2222A[BF]". If I remove the "@" ngspice crashes.

The crash comes from Ngspice itself, not from Qucs-S GUI. If the `@` is removed the syntax of the `altermod` command become incorrect causing Ngspice error. Qucs-S cannot handle this automatically and prevent Ngspice crash.

**Comment by tomhajjar** [comment]
I changed SweepModel to true for BJT_dc.sch and BJT_dc_ngspice.sch. Only BJT_dc_ngspice.sch seems to give the correct output. Is T1.Bf in BJT_dc.sch still the wrong syntax? 


![2022-08-18_085215](https://user-images.githubusercontent.com/102838604/185399577-cdaad723-0cc5-49ba-b1f0-46eb64880df2.jpg)
![2022-08-18_085226](https://user-images.githubusercontent.com/102838604/185399586-be712ad6-b3d7-4d12-bac0-071bb3fb3054.jpg)

**Comment by ra3xdh** [comment]
> Is T1.Bf in BJT_dc.sch still the wrong syntax? What is the correct syntax?

The BJT_dc.sch schematic is affected by another bug. It's not possible to make it work with the `0.0.24` release. The fix will be available only in the next release. See my recent commit https://github.com/ra3xdh/qucs_s/commit/29a30058410ca09687097acb42c1795dae56081b

**Comment by tomhajjar** [comment]
It's odd BJT_dc.sch generates a plot with a single sweep for Bf=20 and not the default 200.


![2022-08-18_090204](https://user-images.githubusercontent.com/102838604/185403576-8e4e3b1b-f5f8-4d52-ae38-8ae0b8b948ba.jpg)
![2022-08-18_090217](https://user-images.githubusercontent.com/102838604/185403577-fa955494-9c9f-4bd0-9540-3edb546781b5.jpg)

**Comment by ra3xdh** [comment]
> It's odd BJT_dc.sch generates a plot with a single sweep for Bf=20 and not the default 200.

Your calculation is wrong. The collector current should be Ic=Ib*Bf=5e-6*200=1e-3 A as shown on the graph.

**Comment by tomhajjar** [comment]
Here is the latest and greatest. 

[BJT_examples_ngspice.zip](https://github.com/ra3xdh/qucs_s/files/9374297/BJT_examples_ngspice.zip)

**Comment by tomhajjar** [comment]
I got BJT_dc.sch to work, Since the netlist name for T1 passed to ngspice is actually QMOD_T1, I just used @QMOD_T1[BF]. 

Is there a reason Qucs appends a prefix onto every library model designator? I assume the prefix is different for every device type in the libraries. Won't this complicate your fix? 

![2022-08-18_094950](https://user-images.githubusercontent.com/102838604/185412779-3be50614-ef18-4bdf-8296-fa486af37d00.jpg)

[BJT_param_sweep_ngspice.zip](https://github.com/ra3xdh/qucs_s/files/9374437/BJT_param_sweep_ngspice.zip)

**Comment by ra3xdh** [comment]
> I got BJT_dc.sch to work, Since the netlist name for T1 passed to ngspice is actually QMOD_T1, I just used @QMOD_T1[BF]

Yes, this will work, but it is a hack and relies on internal Qucs-S netlister naming that is subject of change between the versions. And such example should not go to the documentation. The next release will provide a fix that will make the `Device.Param` syntax operational again.

> Is there a reason Qucs appends a prefix onto every library model designator?

The `@` prefix is required by Ngspice `altermod` command when swweping parameters inside the modelcard `.MODEL`. See the chapter 17.5.4 of the Ngspice manual for more details https://ngspice.sourceforge.io/docs/ngspice-html-manual/manual.xhtml#magicparlabel-24272 Everything comes from this fact that Ngspice has no `.SW` simulation type like Xyce and it's need to use hacks with `alter/altermod` and `while` loop to emulate the parameter sweep.

**Comment by ra3xdh** [comment]
I have updated BJT simulation examples based on your project. Closing this.
