### ISSUE TITLE
Add editor for symbol `*.sym` files

### ISSUE THREAD

**Issue by tomhajjar** [ra3xdh/qucs_s#147]
Any reason "Qucs" never had a Symbol editor? I have been "stealing" symbol sections out of other peoples schematics using a text editor or use symbols.sch from QucsStudio. Editing Qucs-S schematics using a text editor is not user friendly. 

On a side note, I complained how frustrating it was to make good looking transformers and coils using Elliptic Arc on the Qucs SourceForge forum. I was told to use a text editor to alter the Elliptic Arc parameters :-(.  I always give up and steal an inductor from symbols.sch which I got from QucsStudio.

https://sourceforge.net/p/qucs/discussion/311050/thread/b833231fb8/

[symbols.zip](https://github.com/ra3xdh/qucs_s/files/9456341/symbols.zip)

**Comment by tomhajjar** [comment]
Hmmmmm

https://sourceforge.net/p/qucs/mailman/message/35830246/

**Comment by ra3xdh** [comment]
Currently the symbol may be edited only for schematic (entered by F9). But there is no editor for `*.sym` files. The `*.sym` files are relatively new features and were added in Qucs-S. Basic Qt4 Qucs doesn't support symbol files and use only subcircuits. The editing of `*.sym` files is technically possible, but was not implemented due to lack of developers and time resources. Probably symbol editor may be added in the future.

**Comment by tomhajjar** [comment]
Maybe as a stop-gap provide groups of generic symbols in schematic form like I attached earlier. It sure speeds up subcircuit creation. I've been using this file for a long time. I plan on adding more symbols. Its time consuming to cut and paste symbols using a text editor. 

![2022-08-31_130223](https://user-images.githubusercontent.com/102838604/187737911-cb0a5a95-9918-4c4a-9854-2f2b9c53b0ca.jpg)

**Comment by tomhajjar** [comment]
These schematics with various symbols speeds up creating devices and subcircuits. Just copy and paste. 

[Symbol_creation_prj.zip](https://github.com/ra3xdh/qucs_s/files/12754554/Symbol_creation_prj.zip)

**Comment by ra3xdh** [comment]
@tomhajjar  I have uploaded your symbols into the `examples/symbols` subdirectory. I hope this will help other users to create their own subcircuits. Thanks for contribution!

**Comment by tomhajjar** [comment]
Updated the symbol files.

![2024-01-28_221028](https://github.com/ra3xdh/qucs_s/assets/102838604/b0cf1d7b-79a4-4cd8-8e6f-3984480d4eba)

[Symbol_creation_prj.zip](https://github.com/ra3xdh/qucs_s/files/14079253/Symbol_creation_prj.zip)

**Comment by ra3xdh** [comment]
The symbol file editing feature implemented by #700

**Comment by ra3xdh** [comment]
The solution provided by #700. Closing.
