### ISSUE TITLE
OpenSuse Tumbleweed package

### ISSUE THREAD

**Issue by alexpacini** [ra3xdh/qucs_s#15]
Hi,
could you provide also an opensuse package?
The rpm works just fine, but it would be cool to add directly the repo.
Is it possible to enable the build of opensuse packages in OBS?

**Comment by ra3xdh** [comment]
As far as I know the SPEC-files from CentOS/Fedora may not work for OpenSUSE. I have no virtual machine with OpenSUSE to check it now. If you provide me a valid SPEC, I will be able to add OpenSUSE in OBS.

**Comment by ra3xdh** [comment]
As far as I know OpenSUSE Thumbleweed doesn't contain the Qt4 libraries and the package cannot be built now. You may use the AppImage packages that could be run regardless system Qt version.
