### ISSUE TITLE
Ellipse Filling Style: garble text

### ISSUE THREAD

**Issue by tomhajjar** [ra3xdh/qucs_s#151]
Ellipse Filling Style, text is garbled in Win 10

![2022-09-11_171141](https://user-images.githubusercontent.com/102838604/189549052-d740eb3b-acfd-4a82-a48c-0e5a0b022bea.jpg)

**Comment by ra3xdh** [comment]
Yes, this bug has appeared after Qt5 porting. I will it soon.

**Comment by ra3xdh** [comment]
The layout in the fillingdialog.cpp has been fixed by https://github.com/ra3xdh/qucs_s/commit/94ef8ad21d1608a33ccc08becdbef827b7446e4f
![image](https://user-images.githubusercontent.com/4920080/189649284-0803587d-4e49-4c0f-9fa7-07baf655ce0e.png)
