### ISSUE TITLE
Deactivate doesn't work for Equations

### ISSUE THREAD

**Issue by tomhajjar** [ra3xdh/qucs_s#154]
In "porting" Qucs projects over to Qucs-S, it's helpful if Equations and components can be "Deactivated" instead of deleted. 

Qucs-S doesn't deactivate every function in Equations and ngspice either crashes or flags errors. This can also be an issue when you want to do comparisons between simulators.

EDIT from @ra3xdh: todo list for issue

- [x] Qucs equations cannot be disabled 

![2022-09-12_155307](https://user-images.githubusercontent.com/102838604/189743642-afb1c644-1ee9-4e2f-832f-3a773cff00ed.jpg)

**Comment by tomhajjar** [comment]
This project hasn't been ported to Qucs-S yet. I only replaced the Bias T, DC block and DC feed 

[Varactor Model_prj.zip](https://github.com/ra3xdh/qucs_s/files/9551397/Varactor.Model_prj.zip)

**Comment by ra3xdh** [comment]
Yes, I confirm the bug with equations. I have also noticed another problem with SP simulation. It cannot process single point sweep properly.

**Comment by ra3xdh** [comment]
I have fixed the equations problem, but the problem with single point simulation still remain.
