### ISSUE TITLE
ngspice 1 port S-parameter doesn't work

### ISSUE THREAD

**Issue by tomhajjar** [ra3xdh/qucs_s#155]
ngspice won't do single port S-parameter analysis (S11). Never a problem with Qucs. Is this to be expected?

![2022-09-14_204215](https://user-images.githubusercontent.com/102838604/190287208-85d6dd40-5b78-410b-8b70-64b22f1bda54.jpg)

**Comment by tomhajjar** [comment]
Qucs

![Qucs](https://user-images.githubusercontent.com/102838604/190287741-2b8ad83e-2795-401c-86f2-aeced16993c7.jpg)

**Comment by tomhajjar** [comment]
Left comment at ngspice support

**Comment by tomhajjar** [comment]
For now, measuring S11 using ngspice requires you to have two power sources and terminate the unused one.

Alessio is looking into it.

**Comment by ra3xdh** [comment]
Closing as not related to Qucs-S GUI. Waiting for solution in the Ngspice.
