### ISSUE TITLE
New 3 terminal MOSFETs

### ISSUE THREAD

**Issue by tomhajjar** [ra3xdh/qucs_s#158]
Shouldn't two of the new "3 pin" MOSFETs use the enhancement mode symbol? Is it redundant to offer 3/4 pin selections for these depletion mode devices when four, 4 pin depletion mode devices exist as well? Am I missing something?

What is the difference between the Spice "X" device versus an "M" device when both offer the same Properties? 

![2022-09-17_183613](https://user-images.githubusercontent.com/102838604/190878658-12eefed0-1b0c-4daf-8e1d-10c879c7e5cd.jpg)
![2022-09-18_093103](https://user-images.githubusercontent.com/102838604/190904873-662f7579-ea77-4044-8c7a-b2e3a2ec5f21.jpg)
![2022-09-18_093122](https://user-images.githubusercontent.com/102838604/190904879-f33e4e55-ddfa-49f4-b0ef-17d925263a11.jpg)

**Comment by ra3xdh** [comment]
> Shouldn't two of the new "3 pin" MOSFETs use the enhancement mode symbol?

I don't see a big issue here. Some other CADs are also using common symbol for both enhancement and depletion mode MOSFET devices. 

> What is the difference between the Spice "X" device versus an "M" device when both offer the same Properties?

The "X" device is mapped to SPICE entry `X` letter representing subcircuits. Some of PDKs for microelectronics design provide MOSFET models wrapped in subcircuit. The X MOSFET device is needed to support such libraries from PDKs.

**Comment by ra3xdh** [comment]
Assume this is resolved. Closing ticket.
