### ISSUE TITLE
Make revision of the examples

### ISSUE THREAD

**Issue by ra3xdh** [ra3xdh/qucs_s#162]
The examples from `examples` directory were made for Qucsator simulation kernel and may be incompatible with Qucs-S+Ngspice. Like `examples/resonance.sch` will not work work with Ngspice and produce cryptic error message. This may be misleading for new users. It's need to review all examples and move inconpatible with Ngspice to special `qucsator` subdirectory.   Another task is to add more examples.

- [x] Move Ngspice-incompatible examples elsewhere
- [x] Add new examples
- [x] Revise existing example schematic. Something may become outdated there

**Comment by tomhajjar** [comment]
I've segregated the examples into separate "schematic" folders under separate start folders for Qucs, Qucs-s and QucsStudio. "prj" folders are also segregated by qucs version. I have tested almost every schematic and project.  

![2022-09-20_222120](https://user-images.githubusercontent.com/102838604/191400018-5bdca874-526b-467b-b57f-703adb00e935.jpg)

**Comment by tomhajjar** [comment]
One of the issues I see with the examples is the non-descriptive names used for schematics. Unless there is a directory, no user is going to know what many of the circuits are. 

When I look for help trying to do something, I often use Grep looking for keywords in the examples folder. I then look at the example schematic hoping it will help. Since most of the examples are for "Qucs", it isn't as helpful as it could be.

**Comment by tomhajjar** [comment]
When "porting" Qucs schematics to Qucs-S, I'm slowed down by Qucs-S not generating any error messages. I don't know ngspice well enough to convert the two Parameter Sweeps used in Qucs to work for Qucs-S. Getting no error messages doesn't help.

![2022-09-21_125106](https://user-images.githubusercontent.com/102838604/191566157-a7296776-3d3d-4e76-b6e9-bfeed3b9009b.jpg)
![2022-09-21_125753](https://user-images.githubusercontent.com/102838604/191566174-95e14cf3-adaf-4e33-84f6-fc7eeac3d425.jpg)

[schematics-S.zip](https://github.com/ra3xdh/qucs_s/files/9618872/schematics-S.zip)

**Comment by tomhajjar** [comment]
There are a number of examples that use BJT with Substrate. Qucs-S doesn't support this device but I believe ngspice and xyce does.

**Comment by tomhajjar** [comment]
First cut at the revised examples. ngspice and xyce folders to follow

[schematics-S.zip](https://github.com/ra3xdh/qucs_s/files/9621906/schematics-S.zip)

**Comment by tomhajjar** [comment]
ngspice and xyce folders
[ngspice_xyce_schematics.zip](https://github.com/ra3xdh/qucs_s/files/9621907/ngspice_xyce_schematics.zip)

**Comment by ra3xdh** [comment]
Thank you @tomhajjar  I will sort the examples in the next few days and leave feedback. One remark: the `*.dat.*` files (datasets) must not be included in the Qucs-S distribution to avoid the bloating of the package. Only `*.sch` and `*.dpl` files should be indexed by git.

**Comment by tomhajjar** [comment]
I redid the xyce folder and added some files.

Qucs-S 1.0.0 still has issues with autoranging for xyce plots.

[xyce.zip](https://github.com/ra3xdh/qucs_s/files/9627723/xyce.zip)

**Comment by ra3xdh** [comment]
> When "porting" Qucs schematics to Qucs-S, I'm slowed down by Qucs-S not generating any error messag

Qucs-S doesn't generate error messages. It only shows the error messages from simulation kernel. Unfortunately Ngspice doesn't generate very verbose error messages and often it show only `no .plot no .print line` and nothing more. I cannot do anything with this. I can only prevent user from insertion of the incompatible device or equation. 

> Qucs can alter parameters of multiple components/sources with the same Parameter Sweep.

It is Ngspice generating no error messages but not Qucs-S. Ngspice doesn't support parameter sweep. And auto-generated Nutmeg script that emulates parameter sweep doesn't support sweeping two devices simultaneously. This schematic could be ported only using manual written Nutmeg scripting. More that two Parameter Sweep simulations referencing the same simulation is not allowed. I can perform the following actions to resolve this problem:

* Implement sweeping of more than one device if the device list is given like `R1;R2`
* Show warning if more that one Par.Sweep is referencing the same simulation

**Comment by ra3xdh** [comment]
> Qucs-S 1.0.0 still has issues with autoranging for xyce plots.

I didn't fix the auto-ranging issue #133 yet. Only 64-bit Windows version is affected.

**Comment by ra3xdh** [comment]
> There are a number of examples that use BJT with Substrate.

I will add these devices to Qucs-S soon. I have created a dedicated issue #164 .

**Comment by tomhajjar** [comment]
Are you rethinking having so many depletion mode fet symbols and no enhancement mode ones?

**Comment by ra3xdh** [comment]
I don't see any big issue with MOSFET look. The symbol view doesn't affect MOSFET operation, but only the component look. Many software use the common symbol for all MOSFETs. I can redraw the symbol, but it's a low priority task in my list.

**Comment by tomhajjar** [comment]
What is your reasoning for having X and M devices in the Main dock when X and M can be changed and the parameters are the same?

![2022-09-22_125647](https://user-images.githubusercontent.com/102838604/191807513-0d913857-f4b8-4f48-a917-b812869af399.jpg)

**Comment by ra3xdh** [comment]
These devices have different SPICE letter. The `X` device is represented as subcircuit and `M` device as represented as MOSFET device. PDK for microelectronics often provide libraries containing MOSFET models where MOSFET is represented as subcircuit. It make sense to have a special device for them.

**Comment by tomhajjar** [comment]
FYI
single_phase_transformer.sch
Transformer_opposite_coupling.sch
Transformer_positive_coupling.sch

All had the same issue. Subcircuits had errors L=L1=L1 when they should be L=L1 ...etc

**Comment by KAGVa** [comment]
> 

Hi, when you use the param_sweep.cpp and param_sweep.h from PR#169 you should now be able to sweep multiple parameters in a single sweep (only one type allowed), the syntax is
Param=R1;R2;R3
split with ";" - if you use different parameters like R1;C1 I don't know what happens (I haven't tried that)

**Comment by ra3xdh** [comment]
I have just pushed the revised examples tree to the specific branch https://github.com/ra3xdh/qucs_s/tree/revised_examples I am planning to merge this into the `current` branch soon. The legacy examples are moved to the `examples/qucsator` subdirectory now.

**Comment by ra3xdh** [comment]
> All had the same issue. Subcircuits had errors L=L1=L1 when they should be L=L1 ...etc

I have fixed this example by switching transformers to the library implementation from `Transformer.lib` These subcircuits were made when the library was not available, but the example was not updated later.

**Comment by ra3xdh** [comment]
The Qucs v1.0.0 contains the revised examples. The schematics were copied in the new tree. The binary files has been deleted from Git. Thanks @tomhajjar  for help! It remains a question regarding the inclusion of the examples from here https://github.com/tvrusso/Xyce_qucs-s_Examples/ But this issue may be closed as resolved.
