### ISSUE TITLE
Author name display problem in AppImage

### ISSUE THREAD

**Issue by erusyd** [ra3xdh/qucs_s#167]
![image](https://user-images.githubusercontent.com/1529102/191886494-8eecce34-f551-437e-afde-6cf31578b968.png)

I also installed qucs from ppa, it does not have this problem. I check the source code *qucs/dialogs/aboutdialog.cpp*, they are same
![image](https://user-images.githubusercontent.com/1529102/191886938-369d17ea-47f7-439a-bff5-4eb6997ad4c0.png)

**Comment by ra3xdh** [comment]
This issue has been fixed on the `current` branch. That's why you don't see it on `master` See also #107 The fix will be available in the next release.

**Comment by ra3xdh** [comment]
Closed as duplicate of #107
