### ISSUE TITLE
Measurement expressions and simulator expressions

### ISSUE THREAD

**Issue by alexpacini** [ra3xdh/qucs_s#17]
I am trying to do some simulations with the Xyce backhanded and using the Time2Freq() function but I have understood that all the expressions are simulator expressions, therefore they are passed to the simulator using the spice command, for example .param.
Being used to ADS I feel like it could be nice to separate the simulator equations to the measurement expressions, which should be independent of the simulator and working without the need of simulating again the entire circuit.
For example, just taking the dc component of the output seems complicated, while in ADS it is for example vout[0]

**Comment by ra3xdh** [comment]
Yes, the adding of an unified postprocessor for simulation data could be a good idea. It was discussed once at the Qucs mainline project. But it could be not implemented at this time slot. It is another subproject that will require a large amount of coding.
