### ISSUE TITLE
ngspice-38

### ISSUE THREAD

**Issue by holvo** [ra3xdh/qucs_s#174]
ngspice-38 is available. See
https://sourceforge.net/projects/ngspice/files/ng-spice-rework/38/
or
https://sourceforge.net/p/ngspice/ngspice/ci/master/tree/

**TODO** list

- [x] Add digital devices to Qucs-S #97

**Comment by ra3xdh** [comment]
Hello Holger! Thanks for the information. I will include at least the basic digital simulation features in the upcoming Qucs-S 1.0.0 release.

**Comment by ra3xdh** [comment]
The missing digital devices were added by #262 Closing this as completed.
