### ISSUE TITLE
How to disable Parameter Sweep; How to alter two parameters

### ISSUE THREAD

**Issue by tomhajjar** [ra3xdh/qucs_s#176]
Is there a reason a Parameter Sweep cannot be disabled? I have to delete the two sweeps to get ngspice to work.

A responder to one of the Issues mentioned that more than one parameter can be changed by specifying the parameters as R1;R2. 
I cannot find the comment to confirm. Is there a way to do it? ";" cannot be used in the parameter window

TODO list from @ra3xdh 
- [x] Fix disable of the parameter sweep
- [x] Remove validator from *Parameter* input filed in sweep properties dialog

![2022-10-30_224928](https://user-images.githubusercontent.com/102838604/198920820-5299321d-b918-4f6d-88f8-1aac4d1e00e8.jpg)
[diff1.zip](https://github.com/ra3xdh/qucs_s/files/9897627/diff1.zip)

**Comment by ra3xdh** [comment]
> Is there a reason a Parameter Sweep cannot be disabled?

Yes, I confirm this bug. Disabling parameter sweep doesn't work properly. 

> I cannot find the comment to confirm. Is there a way to do it? ";" 

This feature was added by #169 and merged in `master`. Yes, I confirm the problem with semicolon symbol in the input field. Some validator is installed for this dialog that prevents from entering semicolon symbol. As the workaround you may enter the parameter name directly on schematic. Just click on the component property and it become editable.

**Comment by ra3xdh** [comment]
After applying corrections the schematic could be simulated without error:
![image](https://user-images.githubusercontent.com/4920080/199001550-851d1fb3-22a2-4996-92cc-3552d51c6f14.png)

**Comment by ra3xdh** [comment]
I have fixed this bug on the `current` branch. There was a validator for Par.Sweep property holding the component name. The disabling of the Par.Sweep also should work properly now.

**Comment by tomhajjar** [comment]
I look forward to a newer Windows release so I can do more testing.

"As the workaround you may enter the parameter name directly on schematic. Just click on the component property and it become editable."

I don't understand this statement.

**Comment by ra3xdh** [comment]
> I don't understand this statement.

Al component properties are clickable. After you click the component property, you may edit it. Then press Enter to apply changes. This may be done not only for simulations but for all components. 
![click](https://user-images.githubusercontent.com/4920080/199023967-7e0c1592-e378-4e8e-a5dc-0ca1d315e4c4.png)

**Comment by tomhajjar** [comment]
A "feature" I never knew about. I only copied text from this field. 

Wouldn't this feature be more obvious if the editable field turned a different color like white?

**Comment by ra3xdh** [comment]
Closing issue as resolved.
