### ISSUE TITLE
Legacy Qucs equations versus Nutmeg (ngspice )

### ISSUE THREAD

**Issue by tomhajjar** [ra3xdh/qucs_s#179]
I have 700 Qucs schematics with Equation blocks that have been "ported" over to Qucs-S. The vast majority of Equation blocks worked without converting them to Nutmeg equations. The 3rd example uses v(Output) versus Output.v. 

Is there a way to know what Qucs functions don't work in Qucs-S (ngspice)?

The first three examples work but the last Equation block using "diff" does not. Trying to reconcile why it doesn't work when many other functions do. 

![2022-10-31_175702](https://user-images.githubusercontent.com/102838604/199119698-72bdcb2b-5353-4c92-b66e-e04b0a8ad1aa.jpg)

![2022-10-31_180231](https://user-images.githubusercontent.com/102838604/199119700-16bcde3f-8ac8-472a-96d9-a52408ca08c6.jpg)

![2022-10-31_212718](https://user-images.githubusercontent.com/102838604/199138763-b2d8f06f-4d29-4baf-9aa0-6bc0cffc9cf1.jpg)

![2022-10-31_190321](https://user-images.githubusercontent.com/102838604/199138229-a409ee53-071a-4d7a-af14-0ac99cb68014.jpg)

**Comment by ra3xdh** [comment]
Hello Tom. there is no list of Ngspice-incompatible functions. The documentation os lacking here. Qucs-S converts only node names (like `out.Vt` and `v(out)`), but not functions.  The `dB()` function is implemented in both simulators, but other functions may be not. Writing a converter for functions may be a complicated task. Simple translation of the functions name may be not sufficient here. Instead of writing a converter, I decided to prevent user from insertion a Qucs equation in schematic using Ngspice simulation. That's why I removed a Qucs equation button from the toolbar and replaced it with Nutmeg equation.

**Comment by tomhajjar** [comment]
"Qucs-S converts only node names (like out.Vt and v(out)), but not functions."

Converting names is only true for Qucs equations correct? I cannot use Qucs names in Nutmeg Equations. 

Adding to my confusion was both Qucs and ngspice don't list the full and truncated names that are allowed for functions. 

ph and phase are treated the same in ngspice, 

![Nutmeg](https://user-images.githubusercontent.com/102838604/199253504-883a3fd0-f1d6-44a7-9a8b-1d669f5eccfd.jpg)

**Comment by ra3xdh** [comment]
> Converting names is only true for Qucs equations correct? 

Qucs-S doesn't apply any preprocessing for Nutmeg equations. They are transfered to the simulator unchanged. Qucs node names must not be used when SPICE kernel is selected. 

> Does Qucs/ngspice list the full or truncated name allowed for every function?

Only `ph` is listed here https://ngspice.sourceforge.io/docs/ngspice-html-manual/manual.xhtml#magicparlabel-23827 The `phase` seems to be undocumented but works as expected.

**Comment by tomhajjar** [comment]
Holger pointed me in the right direction.  I also found an error in the Qucs-S Help. Qucs-S Help infers "log" is base 10 when it is base e. This error is on two locations in the Qucs-S Help. I haven't dug into Operator differences. 

![Nutmeg](https://user-images.githubusercontent.com/102838604/199533165-74f86441-65b6-41bb-9b82-e17e9ad9daa1.jpg)

[ngspice Function names.zip](https://github.com/ra3xdh/qucs_s/files/9921890/ngspice.Function.names.zip)

**Comment by ra3xdh** [comment]
I have added a list of the most frequently used Nutmeg functions to the Qucs-S tutorial. This should prevent similar questions in the future. Closing this issue as resolved.
![image](https://user-images.githubusercontent.com/4920080/222902158-08138c3a-4a93-496b-9ebe-c2f68fc11bc0.png)

**Comment by tomhajjar** [comment]
As I stated above, ngspice allows multiple acronyms and usage for the same function and some are the same as used in Qucs Equations. 

Also causing confusion:

"log"="ln" ;natural log
"log10"; Log base 10

page 106 ngspice 39 manual:
Exponential and logarithmic: exp, ln, log, log10 (ln, log with base e, log10 with base10)
