### ISSUE TITLE
Parameter Sweep Failed

### ISSUE THREAD

**Issue by sabb1r** [ra3xdh/qucs_s#18]
<p>While doing parameter sweep the following simulation error are thrown:</p>
<p><code>
line 8: checker error, extraneous property `SweepModel' is invalid in `SW:SW1'
line 8: checker error, no such variable `false' used in a `SW:SW1' property
</code></p>

I am using QUCS 0.0.19 on Ubuntu 18.04.

I have attached my circuit for illustrating what i was doing.

![qucs](https://user-images.githubusercontent.com/39703545/49024129-fddf0100-f1c2-11e8-93d9-6a67311cba1b.png)

**Comment by ra3xdh** [comment]
It is not a bug. This may appear when you are trying to open Qucs-S schematic with "simple" Qucs. You need to edit the *.sch file with the text editor and remove the invalid property. Then you will be able to open and simulate it with Qucs.
