### ISSUE TITLE
Dual monitor initial size wrong

### ISSUE THREAD

**Issue by dsm** [ra3xdh/qucs_s#185]
Initial launch size of the app cover two monitor maybe change the initial app size calculation

**Comment by ra3xdh** [comment]
I cannot reproduce this issue using the Kubuntu 22.04+KDE5.92 The Qucs-S window positioned correctly on the main monitor. Seems to be WM-dependent.

**Comment by ra3xdh** [comment]
I have tried different OS and hardware and still cannot reproduce this. Closing as cannot reproduce.
