### ISSUE TITLE
Qucsator not working

### ISSUE THREAD

**Issue by tomhajjar** [ra3xdh/qucs_s#188]
I haven't used qucsator.exe with Qucs-S in a very long time. I tried today and cannot get it to work. I tried Qucs-S 0.0.24 and 1.0.0 with qucsator.exe from Qucs 0.0.19 and 0.0.20. File works in Qucs and Qucs-S using ngspice. 

qucsator.exe in Qucs 0.0.19 is 99K
qucsator.exe in Qucs 0.0.20 is 566K, over 5x larger.

Is there something obvious I did wrong? 

![2022-11-23_142732](https://user-images.githubusercontent.com/102838604/203631355-08d78aad-d30a-4751-ae97-e6f0cb0c016a.jpg)
![2022-11-23_143223](https://user-images.githubusercontent.com/102838604/203631894-e7806fb8-cd1e-44f8-8ac5-fe17cbc6f88f.jpg)

[2N3055-switch.zip](https://github.com/ra3xdh/qucs_s/files/10078540/2N3055-switch.zip)

**Comment by tomhajjar** [comment]
It works if Qucs is installed and change the setting to point to qucsator.exe.

![2022-11-24_085002](https://user-images.githubusercontent.com/102838604/203800643-a8056830-1db2-4abf-9cf8-49b9151095e6.jpg)

**Comment by ra3xdh** [comment]
Yes, this is expected behavior. The reasons are explained above. You cannot move `qucsator.exe` elsewhere without providing a matching DLLs version. The DLLs from Qucs-S distribution has the same name, but are different from Qt4 Qucs distribution.

**Comment by tomhajjar** [comment]
Qucs development is diverging yet again. One group is pushing Gnucsator but they are providing no assistance to Windows users to get it. In addition there are no details of the shortcomings of using Gnucsator.

**Comment by ra3xdh** [comment]
gnuscator is a wrapper for Gnucap simulation kernel that provides Qucsator-compatible syntax. It could be used as the direct replacement for qucsator engine. I didn't try gnuscator with Qucs-S but in principle it should operate if one specify executable name pointing to gnucsator. Gnuscator is also not actively developed. I see long (2-3 months) pauses between the commits.

**Comment by ra3xdh** [comment]
I assume the issue with qucsator launch on Windows platform has been resolved and the ticket could be closed.
