### ISSUE TITLE
Add variable sweep support using the alterparam command

### ISSUE THREAD

**Issue by ra3xdh** [ra3xdh/qucs_s#189]
Ngspice has added `alterparam` command in the recent versions https://ngspice.sourceforge.io/docs/ngspice-html-manual/manual.xhtml#magicparlabel-24765 This command allows to modify the variable defined in `.PARAM` section. This could be used to implement variable parameter sweet that is currently not supported by Qucs-S+Ngspice.

**Comment by ra3xdh** [comment]
I have added a basic support for `alterparam` on`current` branch. This makes possible sweeping variables with Qucs-S+Ngspice. Qucs-S recognizes variables automatically and apply appropriate command. See attached screenshot for example.
![image](https://user-images.githubusercontent.com/4920080/204153823-958428a4-8553-47ed-8b4b-7ab39f379ab3.png)

**Comment by 0range0range** [comment]
I tried the same circuit as in the picture on Windows and I have a question regarding plotting.
If I sweep parameter by name, then when I plot multiple curves for each parameter valuer appear. 
But, if I sweep something defined in `.param`, then although resulting datasets are the same, when I select to plot `v(out)` for example - only curve corresponding to the first parameter value appears on the plot.

How to plot for multiple parameter values, defined with `.param`?

**Comment by ra3xdh** [comment]
Closing this. The feature expected in the upcoming v1.0.1 release.
