### ISSUE TITLE
Inductor & L Inductor

### ISSUE THREAD

**Issue by hlwhite** [ra3xdh/qucs_s#19]
The Inductor symbol cannot be connected to other symbol vertically, for instance to Capacitor.
![inductor](https://user-images.githubusercontent.com/22722628/49425741-7eac8700-f7d9-11e8-9a67-a964b9e9fbb6.PNG)
.
And the L Inductor symbol cannot be connected to other symbol horizontally, for instance to Capacitor
![linductor](https://user-images.githubusercontent.com/22722628/49425766-88ce8580-f7d9-11e8-8b47-fd858e23cf3b.PNG)

**Comment by ra3xdh** [comment]
The problem is inherited from mainline Qucs, it can appear time-to-time. There is an open issue https://github.com/Qucs/qucs/issues/539 and possible solution.
