### ISSUE TITLE
ngspice op amp model clipping not working correctly

### ISSUE THREAD

**Issue by cactorium** [ra3xdh/qucs_s#20]
Hello! It looks like the op amp clipping isn't working correctly during saturation, at least using the ngspice backend. It seems to do this weird thing where the output gets stuck to the voltage rails instead of returning to normal operation. Also the op amp seems to saturate in the wrong direction somehow; when the clipping starts it jumps to the positive rail instead of saturating on the negative one. Oddly enough, the clipping seems to work correctly if I flip the positive and negative inputs, and the op amp works when it's not clipping with the inputs plugged in either way. Maybe the netlist generator has the two inputs mixed up or something? I've attached a simple test circuit below:

[test.zip](https://github.com/ra3xdh/qucs_s/files/2688208/test.zip)

**Comment by ra3xdh** [comment]
Yes, this is a bug in netlister. Waiting for #27 for fix.

**Comment by ra3xdh** [comment]
Fixed by #27
