### ISSUE TITLE
Interface scaling

### ISSUE THREAD

**Issue by Architect0rr** [ra3xdh/qucs_s#200]
I've a monitor 3200x2000 and each element is so small

Is there an option to scale the whole program interface?

Linux Mint

**Comment by ra3xdh** [comment]
No, there is no way to add manual scaling in the application settings. The Qt5 applications should support HiDPI resolution automatically and use system scaling setting for interface fonts etc. No problems with Qucs-S were observed using FullHD displays with system 150% scaling with KDE.  Unfortunately I have no suitable hardware to debug this issue. It is impossible to reproduce it using virtual machine.

**Comment by Architect0rr** [comment]
Hm, it seems I've solved it with
`QT_AUTO_SCREEN_SCALE_FACTOR=1`
