### ISSUE TITLE
Symbol lines shifting off "grid" when rotated

### ISSUE THREAD

**Issue by tomhajjar** [ra3xdh/qucs_s#203]
When creating symbols for components, if you cut or copy a symbol AND rotate the symbol while pasting, the lines drawn on an angle will shift off the "grid". Attached shows shifting caused by rotate left x2. Mirroring a symbol doesn't seem to cause issues.

Attached is an update on the symbols.sch I created. It is very useful when making new symbols.

In the past I asked if Rotate Right could be added. It can save a lot of time as well as minimize shifting off grid.

![2023-01-05_151142](https://user-images.githubusercontent.com/102838604/210871445-9088554b-1db1-4afc-ad10-6632efd3c8a8.jpg)

[schematic_symbols.zip](https://github.com/ra3xdh/qucs_s/files/10355342/schematic_symbols.zip)

**Comment by ra3xdh** [comment]
This issue is impossible to fix without redesign of the schematic rendering system that is based now on the custom widget. It's need to implement the support of the groups of the graphics primitives that is not straightforward task for the current schematic renderer implementation. Closing this.

**Comment by tomhajjar** [comment]
Adding Rotate Right would help. The more consequtive  rotates, the greater the chance of segments "jumping" off grid. 

Mirroring does not cause issues.
