### ISSUE TITLE
Update CMake build system

### ISSUE THREAD

**Issue by ra3xdh** [ra3xdh/qucs_s#216]
The build system relies on CMake2.8 syntax inherited from old Qucs. New versions of the CMake contain a lot of useful features. The build system should be revised and updated.  The minimal supported version should be CMake 3.18 from Ubuntu18.04.

**Comment by ra3xdh** [comment]
See #217

**Comment by dsm** [comment]
added msvc build support any improvement need, it'll be added to list.

**Comment by ra3xdh** [comment]
CMake build system update has been done with #217 Closing this as resolved.
