### ISSUE TITLE
uic option for .tran simulation

### ISSUE THREAD

**Issue by cznwhale** [ra3xdh/qucs_s#226]
Please add the possibility to use initial conditions in a transient analysis.
For this, it is required to add an option in the TRAN simulations block that would put "uic" text in the .tran command

**TODO** list

- [ ] Add a hint in the `InitalDC` option description that is mapped to `UIC`

**Comment by ra3xdh** [comment]
Everything is already implemented. The *Initial DC=yes* option adds the UIC condition to the transient analysis. It could be combined with `.IC` virtual device. 
![image](https://user-images.githubusercontent.com/4920080/220140341-427b5103-1825-4466-8ae1-86f56af8a081.png)
![image](https://user-images.githubusercontent.com/4920080/220140776-37bdbef6-d1a0-4b7b-9a02-a55282b0cb31.png)

**Comment by cznwhale** [comment]
Hi,
Thank you for the fast response. I confirm that putting initialDC=no will put "uic" on the .tran line.

**Comment by pavel-kirienko** [comment]
I also stumbled upon this. Would it not be better to reflect this option in the docs in a more explicit manner?

**Comment by ra3xdh** [comment]
@pavel-kirienko Currently we don't have a person assigned specially for the documentation. I am writing a new tutorial for Qucs-S but the progress is slow. Don't expect a fast update here. I can update the `InitialDC` option description in the simulation device properties to specify explicitly that is mapped to the `UIC` option.

**Comment by ra3xdh** [comment]
I have added a TODO list for this. The hint in the simulation description would be helpful.

**Comment by ra3xdh** [comment]
I have fixed the `InitialDC` option description to mention UIC explicitly. I cannot change the option name because it may break schematic load and Qucsator compatibility. 
![image](https://user-images.githubusercontent.com/4920080/230731505-e88f43bd-1830-4453-9370-25009ef9d147.png)
