### ISSUE TITLE
Transformer Library Testing

### ISSUE THREAD

**Issue by tomhajjar** [ra3xdh/qucs_s#228]
I cannot figure out how to use some of the transformer models in Transformers.lib and how to use properly use Cores.lib. 

First issue is the model XSPICEPS1S2 in Transformers.lib. On the Help web page below, it shows two parameters L and A that don't exist in XSPICEPS1S2 in Transformers.lib. The parameters ntp, nts1 and nts2 cannot be known without knowing L and A. 

When I try to use XSPICEPS1S2, it is in saturation as shown below regardless of ntp, nts1 and nts2. (See R5 comments below.)

Also, shouldn't the XSPICE transformer models allow one to choose the core materials mentioned in Cores.lib? How does one use Cores.lib?

Another issue is R5 used in multiple simulations shown on the Help web page below is 2k. No one would use a resistor as large as 2k on the primary. Rp is already in the model.  Does the model only work for small input voltages?

Lastly I created a Bridge Rectifier model that would be useful to some and maybe good as a library item. 

https://qucs-s-help.readthedocs.io/en/latest/SPICEComp.html#two-winding-transformer-model-with-in-phase-primary-and-secondary-voltages-and-winding-resistance

TODO list from @ra3xdh 

- [x] Add L and A parameters for XSPICEPS1 and XSPICEPS1PS2
- [x] Fix warning on missing inductor model

![2023-02-20_174757](https://user-images.githubusercontent.com/102838604/220209203-613da7ba-eafd-4ac1-b5cc-e21147054860.jpg)

![Transformer XSPICE](https://user-images.githubusercontent.com/102838604/220189845-b1384755-827d-4cac-a8c3-7195f89b1c50.jpg)

[Transformer_testing.zip](https://github.com/ra3xdh/qucs_s/files/10788747/Transformer_testing.zip)

**Comment by tomhajjar** [comment]
I looked at Transformers.lib and it seems L and A are fixed for XSPICEPS1S2. This makes the model almost useless. These limits should be mentioned in the Library "Show model" 

.model Steel core length = 0.2 area=2e-4

![2023-02-20_153502](https://user-images.githubusercontent.com/102838604/220194835-71a0aabb-6c87-43d5-a3b8-c8d31af8c0b7.jpg)

**Comment by ra3xdh** [comment]
> I looked at Transformers.lib and it seems L, A and core laminate are fixed for XSPICEPS1S2

Yes, this device should be corrected. The L and A parameters are indeed fixed. 

> Also, shouldn't the XSPICE transformer models allow one to choose the core materials mentioned in Cores.lib? How does one use Cores.lib

It is not possible to specify the model name as the subcircuit parameter. The only way to attach core is to create your own subcircuit as shown in the Qucs-S manual.

**Comment by tomhajjar** [comment]
Can the *.sch files used to create the Help file page be released?

https://qucs-s-help.readthedocs.io/en/latest/SPICEComp.html#two-winding-transformer-model-with-in-phase-primary-and-secondary-voltages-and-winding-resistance

**Comment by ra3xdh** [comment]
I don't own these schematics. The help was written by Mike Brinson around 2016. I am not sure if some schematics are remaining after seven years passed.

**Comment by tomhajjar** [comment]
Mike is going to look. ;-)

**Comment by tomhajjar** [comment]
I'm finding multiple issues with this library. 

Cosmetic issues:

For ease of drawing schematics or substituting one transformer with another, similar transformer types should use the symbol and pin locations. 

The five, two winding transformers use different symbols and pin locations. . 

The two, three winding (center tapped) transformers use different symbols and one pin in each was placed in the wrong location. 

Functional issues:

 XSPICEPS1S2 output polarity is flipped as shown below. As stated above, parameters N and L are missing and the user should know what the core type is. A lot more work needs to be done to confirm the functionality of the model

I'm trying to test the other models for functionality. Waiting for Mike to send the original files.

![XSPICEPS1S2](https://user-images.githubusercontent.com/102838604/220947844-d41494e2-ed8a-4f9d-86c0-a07f6f1eb605.jpg)

**Comment by tomhajjar** [comment]
I made a first cut at new transformer symbols. They are fully symmetrical with pins on the grid. You can substitute a different model, mirror or rotate devices without having to fix the schematic. 

![2023-02-23_120406](https://user-images.githubusercontent.com/102838604/220979204-797880a2-509f-4605-bc56-7271d4d039bd.jpg)

[symbols_transformers.zip](https://github.com/ra3xdh/qucs_s/files/10816243/symbols_transformers.zip)

**Comment by ra3xdh** [comment]
The symbols in the library is not subject of change. The library was fully operational at least until Ngspice-27. And there may be users that designed circuits with old symbols. I don't know how many users used these devices. If we change the symbols in the library, the backward compatibility will be lost and **ALL** existing schematics will require redesign. This may cause a tons of bugreports why the symbols were changed.

**Comment by tomhajjar** [comment]
Understand. People can use the symbols to make new transformer sub circuits.

**Comment by ra3xdh** [comment]
I have attached a TODO list for this issue.

**Comment by ra3xdh** [comment]
I have fixed XSPICE transformers in the library. You can get the latest library from here: https://raw.githubusercontent.com/ra3xdh/qucs_s/current/library/Transformers.lib Closing this as resolved. The solution for #231 will be added separately.

**Comment by tomhajjar** [comment]
It will take a while to confirm all the changes but XSPICEPS1S2 still has an inverted output in the "new" Transformers.lib like it was in the old.
