### ISSUE TITLE
It is time to update Download links on the website

### ISSUE THREAD

**Issue by EricLucife** [ra3xdh/qucs_s#23]

**Comment by EricLucife** [comment]
I hope you can update the Download links. The first time when I visit https://ra3xdh.github.io/ I haven't found Qucs-S-0.0.21. I am learning and thanks for your works.

**Comment by ra3xdh** [comment]
Done, the links are updated by https://github.com/ra3xdh/ra3xdh.github.io/commit/d8199e2cdcebe89cd182330d707ad57edbcd4b77
