### ISSUE TITLE
Transformer library model test schematic fails simulation

### ISSUE THREAD

**Issue by tomhajjar** [ra3xdh/qucs_s#231]
The Full_wave.sch schematic in the TranLibTest.qucs archive done by Mike Brinson has something wrong with it. All the other schematics seem OK. I made a copy of the original file and data and renamed it to "Full_wave_orig" to preserve it. You can see Mike's original data below. I cannot vouch for the accuracy of the data . The turns ratios for TRAN1 looks odd and i(vprd1) looks too low.

When you FIRST open Full_wave.sch, you will see Mike's original data. 

Run a simulation, and the simulation time is truncated to .02 sec as shown in the second jpg. 

Do a "Set on Grid" for R5 and simulation "works" and simulation time is like in Mike's original data.

Do a "Set on Grid" for D1 and the simulation time is truncated. Next do a "Set on Grid" for D2 and the simulation "works"

Do a "Set on Grid" for TRAN1 and simulation time is truncated. 

This made me think the schematic was off the grid, incompatible model or there is a bad character in the file but it doesn't seem to be. 

I redid the entire schematic and replaced the diodes and simulation time is still truncated. 

The transformers symbols are not symmetrical. This isn't a problem except for the primary leads for the two center tapped transformers. They are not in-line as shown below. It could cause confusion.

![Transformer library test](https://user-images.githubusercontent.com/102838604/220798113-a5b4932d-1c66-42ee-9e9a-ca10a41d4a4c.jpg)

![Transformer library test 2](https://user-images.githubusercontent.com/102838604/220798121-04e95ab7-ca48-4072-82b3-442324a4da95.jpg)

![2023-02-22_204353](https://user-images.githubusercontent.com/102838604/220804158-b35a24a3-a2d2-4871-ad5a-7dced4363eae.jpg)

[Test_prj.zip](https://github.com/ra3xdh/qucs_s/files/10809659/Test_prj.zip)

**Comment by ra3xdh** [comment]
This schematic works as expected using Ngspice-27. But doesn't produce a correct result using the latest Nsgpice-39. I suspect something has been changed in Ngspice or XSPICE since the library release. The `Transformers` library need to be fixed to provide compatibility with the latest Ngspice.

**Comment by tomhajjar** [comment]
I'm trying to identify all the issues with the XSPICEPS1S2 transformer in the library. As stated before, the model lacks the ability to change L or A and it's output polarity is inverted. So I decided to recreate the XSPICEPS1S2 the subcircuit as shown in both the online help and Mike Brinson's 2016 paper. 

I can get XSPICEPS1S2 from the library to simulate as shown in XSPICEPS1S2_lib_test.sch. 

I cannot get the subcircuit I made XSPICEPS1S2_sub.sch to simulate in XSPICEPS1S2_sub_test.sch.

As a side note, the Library view of the Cores library has issues. A spurious graphic **{-}** is displayed. 

![Trans_Core_1P_2S](https://user-images.githubusercontent.com/102838604/222812339-c8c99bae-0301-40b8-9087-2cd0dd856ea1.jpg)

![2023-03-03_144622](https://user-images.githubusercontent.com/102838604/222812700-4a7d627d-c9e4-46d9-9492-7c83cfa5e2cb.jpg)

![555-transistor-characteristic-curve-tracer-circuit-diagram](https://user-images.githubusercontent.com/102838604/222812486-6262460d-6be8-4071-9a17-2212e945e94d.png)

[Transformer_sub_Test_prj.zip](https://github.com/ra3xdh/qucs_s/files/10885586/Transformer_sub_Test_prj.zip)

**Comment by ra3xdh** [comment]
I made some investigations on the full-wave rectifier circuit using XSPICE transformer. It seems there is something wrong inside XSPICE magnetic core model itself. It may operate correctly only if sinusoidal voltage applied to it. The summary is the following:

* The Core model works only using Ngspice-27 and only using some specific diode models connected to secondary winding. For example it fails when I replace diodes by 1N400x device from library. 
* The full-wave rectifier simulation always fails to converge when using Ngspice-39

> Maybe you can spot an obvious mistake.

The first line of ICOUPLE devices should be model name. It it SIcouple on attached screenshot. 
![image](https://user-images.githubusercontent.com/4920080/222894007-f70fe70d-688a-4bb2-a0a2-25fbda41e223.png)

**Comment by tomhajjar** [comment]
I cannot see an obvious mistake.

I found an old KiCad (ngspice) netlist using core and lcouple, Trans_Xspice.cir. 

I modified it and used DuSpice/ngspice.  Analysis shows the output **inverted** (probably caused by the output pins 3/4 flipped. I cannot vouch for the accuracy of the data. The core L and A values (area = 1 length =0.01) are not realistic and swapping them causes output data to be weird 

I entered the circuit Trans_Xspice.cir into Qucs-S, 1P1S_XSpice_tran_test.sch. Unfortunately I'm having issues using the XSPICE "core" Component. I cannot figure out how to enter the core data from Trans_Xspice.cir into the XSPICE core block. Every variation I tried cause ngspice errors so I ended up using the Cores Library model "SheetSteel". Again the data is **inverted** and I cannot vouch for the accuracy. 

 versus using a core model from the core Library. I cannot figure out what for mat to use for  

![Trans_Xspice_KiCad](https://user-images.githubusercontent.com/102838604/222986959-40042546-35a8-4a3d-bbf3-7dfef1a6ef63.jpg)

![Trans_Xspice_ngspice](https://user-images.githubusercontent.com/102838604/222986971-48c4415e-c76a-4809-bb76-f3eb65d7ac47.jpg)

![1P1S_XSpice_tran_test](https://user-images.githubusercontent.com/102838604/222987701-cf7af4ac-cb8d-447d-9b30-db6604e4eceb.jpg)

![XSPICE core block](https://user-images.githubusercontent.com/102838604/222987715-9f685491-7787-4e9b-8e50-28076cb5d97a.jpg)

[Trans_Xspice.zip](https://github.com/ra3xdh/qucs_s/files/10893033/Trans_Xspice.zip)

**Comment by tomhajjar** [comment]
I created 3 netlists for use with DuSpice/ngspice to figure out what's going on. I believe Qucs-S is formatting the netlist entry for the generic Core model from Components wrong.

Trans_Xspice.cir is the test netlist I found on  the web. I modified it to plot only in and out. It simulates without error. Data accuracy unknown. 

The following two netlists are generated by 1P1S_XSpice_tran_test.sch.

Trans_1p1s_lib_netlist.cir, uses the SheetSteel Core model from the Core Library

Trans_1p1s_comp_netlist.cir uses the generic Core model from Components, Core. 

Trans_1p1s_lib_netlist.cir - Simulates without error. Data accuracy unknown. 

Trans_1p1s_comp_netlist.cir - Fails to simulate. 

The "ACORE" entry in Trans_1p1s_comp_netlist.cir is missing multiple items like .model ACORE2 core ( ........). Also missing are mode=1 but I believe that is the default for the PWL core.

[Qucs_netlists.zip](https://github.com/ra3xdh/qucs_s/files/10894055/Qucs_netlists.zip)

**Comment by tomhajjar** [comment]
A minor issue is the name and prefix used for the "lcouple". 

In Components -> XSPICES devices, the lcouple is named "Capital eye"couple and the prefix is "_I_"COUPLE.
__

**Comment by tomhajjar** [comment]
Until the XSICE devices Component's Core is fixed I cannot recreate Mike Brinson's 2015 data. The netlist entries for "Core" are missing multiple entries.

![2023-03-14_181159](https://user-images.githubusercontent.com/102838604/225153998-66b76f44-beb5-4d4a-b971-7cf997a9c677.jpg)

**Comment by ra3xdh** [comment]
> The "Core" netlist parameters and data structure is wrong

Ngspice should accept both modelcard card syntax. Both space separated parameters and using parentheses should be allowed. Something may have changed here between Ngspice-27 and the latest Nsgpice.

**Comment by tomhajjar** [comment]
The is a lot of differences between the KiCad/ngspice manual example and what Qucs-S generated. 

Qucs-S is trying to combine the two separate "a" and "core" netlist entries into a single entry. How is this proper?

********************************************************************************************************************************
KiCad netlist Trans_Xspice.cir:

a3 (interNode_1 interNode_2) u1_iron_core
.model u1_iron_core core (H_array = [-1000 -500 -375 -250 -188 -125 -63 0 63 125 188 250 375 500 1000] B_array = [-3.13e-3 -2.63e-3 -2.33e-3 -1.93e-3 -1.5e-3 -6.25e-4 -2.5e-4 0 2.5e-4 6.25e-4 1.5e-3 1.93e-3 2.33e-3 2.63e-3 3.13e-3] area = 0.01 length = 0.01)

********************************************************************************************************************************
Qucs-S generated netlist for Trans_1p1s_comp_netlist.cir:

ACORE2 n1 n2  Length = 1 Area = 0.01
+ H_array = [-1000 -500 -375 -250 -188 -125 -63 0 63 125 188 250 375 500 1000]
+ B_array = [-3.13e-3 -2.63e-3 -2.33e-3 -1.93e-3 -1.5e-3 -6.25e-4 -2.5e-4 0 2.5e-4 6.25e-4 1.5e-3 1.93e-3 2.33e-3 2.63e-3 3.13e-3]

[Qucs_XSpice_Trans_netlists.zip](https://github.com/ra3xdh/qucs_s/files/10992520/Qucs_XSpice_Trans_netlists.zip)

**Comment by tomhajjar** [comment]
Last comment:

Only the Core parameters for H. B, A and L are different for 1P1S_XSpice_test.sch and 1P1S_XSpice_Core.sch. The netlist structures should be the same but 1P1S_XSpice_test.cir and 1P1S_XSpice_Core.cir look NOTHING alike.  

1P1S_XSpice_test.cir uses ".SUBCKT Cores_SheetSteel"

1P1S_XSpice_Core.cir is missing the .SUBCKT entry

[1P1S_XSpice.zip](https://github.com/ra3xdh/qucs_s/files/11033626/1P1S_XSpice.zip)

**Comment by tomhajjar** [comment]
Until Components...XSPICE...core device is fixed, if you need a Core different than in Cores.lib or used in Transformers.lib the only choice is to use a Text Editor and alter the B, H, L and A parameters manually in the .sch file.

XSPICEPS1 and XSPICEPS1S2 need A and L added. Info on Core material would be useful.

XSPICEPS1S2 output is inverted so output nodes need to be swapped. Info on Core material would be useful.

Strangely XSPICEPS1, XSPICEPS1S2, LossyTransformer1 or LossyTransformer2 don't use any of the B/H parameters in Libraries...Cores. I'm unsure where any of the B/H data in Transformer.lib and Core.lib came from. All the more reason to get XSPICE...core working. 

I tested using lcouple and Sheet Steel Core to make a non-linear inductor. AFAIK it works. 

![2023-03-22_204548](https://user-images.githubusercontent.com/102838604/227074310-83e95a83-6f92-47d7-91b3-2a5508d91220.jpg)

![2023-03-22_204612](https://user-images.githubusercontent.com/102838604/227074330-1a2d1e35-1eda-468b-9c26-9412be149552.jpg)
 
[Qucs-S.zip](https://github.com/ra3xdh/qucs_s/files/11046000/Qucs-S.zip)

**Comment by ra3xdh** [comment]
I have tested the provided schematic again. The problem is that you are using the system CORE device wrong. There is not bugs in netlist generator. The attached example shows how to define core model using this device. 
![image](https://github.com/ra3xdh/qucs_s/assets/4920080/8273ce20-0ffa-41b8-a188-92bd5d325195)

**Comment by ra3xdh** [comment]
Here is the schematic file. 

[Core.zip](https://github.com/ra3xdh/qucs_s/files/11830235/Core.zip)

**Comment by tomhajjar** [comment]
I confirmed that the changes to Transformers.lib work however XSPICEPS1S2 still has an inverted output. See my comments in #228

**Comment by ra3xdh** [comment]
I have fixed polarity issue of the XSPICEPS1PS2 device. I have also found modelcard issue that may cause incorrect simulation. See the latest version here: https://raw.githubusercontent.com/ra3xdh/qucs_s/current/library/Transformers.lib

**Comment by tomhajjar** [comment]
I recreated all the Mike Brinson transformer models in the online help. This folder may be useful for someone.

[Transformer_sub_Test_prj.zip](https://github.com/ra3xdh/qucs_s/files/11848239/Transformer_sub_Test_prj.zip)
