### ISSUE TITLE
SPICE SIMULATION ERROR

### ISSUE THREAD

**Issue by sebastianhenaosanta** [ra3xdh/qucs_s#234]
This is more like a question. I'm now trying to use this tools but i'm getting an issue when trying to run the simulation. 
![Selection_999(024)](https://user-images.githubusercontent.com/12094862/221304942-4c06c4ef-4091-42cb-b625-2741305be2a6.png)

If anyone could help, i'll apresiated.

**Comment by ra3xdh** [comment]
The resistor model inside the SPICE subcircuit has the wrong syntax. Ngspice accepts R but not RES. See the chapter 3.3.2 of the Ngspice manual for more details.

**Comment by ra3xdh** [comment]
See also chapter 3.3.5 of the Ngspice manual for valid resistor model example.

**Comment by sebastianhenaosanta** [comment]
Thank you very much,  now is working as you show in the video. I'm not familiarized with spice files. 
 As you said RES is not accepted by NGSPICE and this is what i dit:


*****************************************************************************
* TL431 MACROMODEL ***************3-26-92************************************
* REV N/A ****************************************************************DBB
*****************************************************************************
*              REFERENCE
*              |  ANODE
*              |  |  CATHODE
*              |  |  |
.SUBCKT  TL431 1  2  3
V1  6  7  DC  1.4V
I1  2  4  1E-3
R1  1  2  1.2E6
R2  4  2  RMOD 2.495E3
R3  5  7  .2
D1  3  6  DMOD1
D2  2  3  DMOD1
D3  2  7  DMOD2
E1  5  2  POLY(2)  (4,2)  (1,2)  0  710  -710
.MODEL RMOD **R** (TC1=1.4E-5 TC2=-1E-6)
.MODEL DMOD1 D (RS=.3)
.MODEL DMOD2 D (RS=1E-6)
.ENDS

just change RES by R and now is working

this is the original model:

*****************************************************************************
* TL431 MACROMODEL ***************3-26-92************************************
* REV N/A ****************************************************************DBB
*****************************************************************************
*              REFERENCE
*              |  ANODE
*              |  |  CATHODE
*              |  |  |
.SUBCKT  TL431 1  2  3
V1  6  7  DC  1.4V
I1  2  4  1E-3
R1  1  2  1.2E6
R2  4  2  RMOD 2.495E3
R3  5  7  .2
D1  3  6  DMOD1
D2  2  3  DMOD1
D3  2  7  DMOD2
E1  5  2  POLY(2)  (4,2)  (1,2)  0  710  -710
.MODEL RMOD RES (TC1=1.4E-5 TC2=-1E-6)
.MODEL DMOD1 D (RS=.3)
.MODEL DMOD2 D (RS=1E-6)
.ENDS

**Comment by ra3xdh** [comment]
Please note that TL431 model is presented in Regulators library. You don't need to add it manually. Use the Search text field to find library devices.

**Comment by sebastianhenaosanta** [comment]
Ok, i'll search all components and models that you have implemented.

**Comment by ra3xdh** [comment]
Closing this issue as resolved.
