### ISSUE TITLE
Parametrising square wave source

### ISSUE THREAD

**Issue by 0range0range** [ra3xdh/qucs_s#249]
When I try to set the  TL parameter of the square wave source from spice `.param` section, it does not work properly. But other things like amplitude do. Also in case of sine wave it is working. Am I doing something wrong?

QUCS-s version: 1.0.1, OS: Linux.

![image](https://user-images.githubusercontent.com/95714694/227496692-00e9dea2-e025-4cbe-860f-57e54e79aaa8.png)

**Comment by ra3xdh** [comment]
It is not a bug. The square wave source parameters are different from SPICE specification. SPICE uses period and pulse width but Qucs used TL and TH. The period and pulse width are calculated from TL and TH to form a valid SPICE entry for this source. And the calculation is possible only if the TL and TH are defined as numbers. The parameter definition will not work with this source. You need to use a full SPICE definition as the workaround. Look at the attached screenshot.

![image](https://user-images.githubusercontent.com/4920080/227543285-f22ed5f3-9f24-403d-99da-582424af17fa.png)

**Comment by 0range0range** [comment]
Worked. Thanks.
