### ISSUE TITLE
Support specifying user-defined .spiceinit in the schematic.

### ISSUE THREAD

**Issue by spueblas** [ra3xdh/qucs_s#25]
Hi! I've been using your software, it's been really useful when simulating SPICE models. 

I've run into issues when using PSPICE models. ngspice, in fact, supports PSPICE models, but it requires a setting in .spiceinit (namely "set ngbehavior=ps"). The ngspice simulator class seems to create an empty (when not using xspice) spiceinit each time it runs a simulation, so it does effectively prevent users from overriding ngbehavior.

One possible way would be to have a new component ("SPICEINIT") with a text property containing text to be included in the spiceinit file created by the simulator class. I think this solution fits nicely the use case, because enabling PSPICE behavior should be done on a per-schematic basis, as it depends on which models are included into it.

I'd like to send you a PR if you agree with the general approach. WDYT?

**Comment by ra3xdh** [comment]
Yes, feel free to open PR. I find this feature useful, if it will not break XSPICE usage.
