### ISSUE TITLE
Add tutorial section about parameter sweep

### ISSUE THREAD

**Issue by tinkerbeast** [ra3xdh/qucs_s#260]
Hi,

I am trying a parameter sweep on a simple voltage divider circuit as follows:

![Screenshot from 2023-04-13 14-52-39](https://user-images.githubusercontent.com/1255092/231715382-81b1ee89-9547-46e9-991f-e4e8d0a840fc.png)

However I keep getting the following error:

```
Ngspice started...
Original line no.: 9, new internal line no.: 15:
Undefined number [rsweep]
Original line no.: 9, new internal line no.: 15:
Cannot compute substitute

ERROR: fatal error in ngspice, exit(1)

No compatibility mode selected!


Circuit: * qucs 1.0.1 /home/rishin/temp.sch

 Copies=8 Evals=16 Placeholders=1 Symbols=0 Errors=2
Simulation finished
```
Please tell me why this doesn't work.

I am using Qucs-S-v1.0.1.x86_64.AppImage on Ubuntu-22.04 with ngspice-36.

**TODO** 
- [x] Add tutorial section explaining how to use parameter sweep with Ngspice

**Comment by ra3xdh** [comment]
I have added a TODO list for this. Adding a tutorial section explaining parameter sweep will prevent such issues in the future.

**Comment by ra3xdh** [comment]
Also a side note. AppImage is not recommended for use on Ubuntu. I am providing a normal DEB package. Find the package and installation instructions here: https://software.opensuse.org/download.html?project=home%3Ara3xdh&package=qucs-s

**Comment by tinkerbeast** [comment]
Thanks for the speedy response. I tried what you did in Bug #189, but I am just getting a different error now -

![Screenshot from 2023-04-13 17-06-13](https://user-images.githubusercontent.com/1255092/231746949-785a3fd9-6b82-4053-a095-d82e69456f3b.png)

```
Fatal error: DC Transfer Function: Voltage source, current source, or resistor named "rsweep" is not in the circuit
doAnalyses: no such device

dc simulation(s) aborted
Error(parse.c--checkvalid): Pr1: zero length vector.
```

I could probably figure out what I am doing wrong if I saw the netlist file.

Also, when you add the tutorial, do mention that `.PARAM` section can be added via equations (Took me some time to figure it out).

**Comment by tomhajjar** [comment]
Here is a number of Parameter sweep examples using AC, DC and TRAN analysis. Although I'm using ngspice 40 today, these examples were done a long time ago.

[Parameter Sweep.zip](https://github.com/ra3xdh/qucs_s/files/11227888/Parameter.Sweep.zip)

**Comment by tinkerbeast** [comment]
Thanks for the awesome support.

Also, I am a C++ programmer by trade (though GUI programming isn't my thing). Let me know if I can help you out with something.

**Comment by ra3xdh** [comment]
I have just updated the tutorial. This should prevent similar issues in the future. Closing this as completed.
