### ISSUE TITLE
Не запускается симуляция схемы

### ISSUE THREAD

**Issue by Laimer641** [ra3xdh/qucs_s#269]
**не запускается симуляция**
![image](https://github.com/ra3xdh/qucs_s/assets/116171117/2f623300-724b-4121-b1d8-0905fc0366b7)
![image](https://github.com/ra3xdh/qucs_s/assets/116171117/049ae315-8eb7-440f-b12b-70a297abe373)
![image](https://github.com/ra3xdh/qucs_s/assets/116171117/f7d9bf99-56eb-4fd0-9ad5-2bc8e3d50a3d)

**сам симулятор в консоли запускается**
![image](https://github.com/ra3xdh/qucs_s/assets/116171117/27a28288-53e9-453b-ad56-40bce52354aa)

** настройки путей для симулятора**
![image](https://github.com/ra3xdh/qucs_s/assets/116171117/dc53bac6-9413-4078-9fbe-3104921745ae)

**Не запускается симуляция даже если запустить qucs-s под sudo**
**Система новая. специально установил для чистоты эксперимента. Система стоит на VirtualBox.**

**Comment by ra3xdh** [comment]
Это не баг. На схеме присутствует только моделирование "DC analysis". Оно само по себе не имеет эффекта. Чтобы симуляция заработала, следует задать моделирования AC или Transisent. Показ соответствующего предупреждения пользователю будет исправлен в следующей версии. См. также #267 

И здесь я вижу схему из туториала от старого Qucs. Не надо пользоваться старым туториалом. В Qucs-S что-то может работать иначе. Правильный туториал можно взять здесь: https://ra3xdh.github.io/pdf/qucs_s_tutorial.pdf На него же ведут ссылки в меню Help.

**Comment by ra3xdh** [comment]
Предполагаею, что вопрос решен, поэтому закрываю тикет. См. также #271
