### ISSUE TITLE
Issue exporting monochrome image

### ISSUE THREAD

**Issue by cmat21** [ra3xdh/qucs_s#288]
Hi, there may be a problem exporting the schematic as a monochrome image.
![Schema_grounding_philosopy](https://github.com/ra3xdh/qucs_s/assets/70080894/8aa79cb7-2390-40b2-b47d-8bdf96ec32f7)
![COLOUR_Schema_grounding_philosopy](https://github.com/ra3xdh/qucs_s/assets/70080894/bd3797bc-d686-4fd3-920e-2f8cb3fbd35d)
![MONOCHROME_Schema_grounding_philosopy](https://github.com/ra3xdh/qucs_s/assets/70080894/b60d51f5-cf59-4892-8a55-919e0aef9ff7)

**Comment by ra3xdh** [comment]
This issue is related to the color mapping while converting image in Qt. I can add a Grayscale option. I hope it may help you.

**Comment by ra3xdh** [comment]
I have added a grayscale option in the "Export to image" dialog. This feature will be available since the next release. Closing this.
