### ISSUE TITLE
Qucs-s ignores initial voltage

### ISSUE THREAD

**Issue by denizzzka** [ra3xdh/qucs_s#291]
Just made simple circuit and tried to set initial voltage for wire (label dialog -> more... -> initial voltage), but simulation ignores this value

Version 1.1.0

(I remember that we discussed something about this with @ra3xdh for a long time ago, but I already forgot details)

**Comment by ra3xdh** [comment]
>  initial voltage for wire (label dialog -> more... -> initial voltage)

I didn't know about this feature and never used it :smile: Indeed, this feature is missing if Ngspice is selected. The node voltages specified in this dialog are ignored. You may use `.IC` or `.NODESET` devices instead. These devices could be found at the components pallette  in the *SPICE specific sections* group.

> I remember that we discussed something about this

You may look at the #226 It explains how to set `UIC` option. Initial conditions will be not applied without `UIC` setting

**Comment by ra3xdh** [comment]
I have added a fix for this. The setting of initial conditions using wire labels should be available for Ngspice since the next release.
