### ISSUE TITLE
[ Request ] Update translation files

### ISSUE THREAD

**Issue by antohami** [ra3xdh/qucs_s#292]
Some dialogues are missing translation. But these phrases are not in the translation files.
I also tried turning on the build option -DUPDATE_TRANSLATIONS=ON
This resulted in an error:
`[ 62%] Generating .lupdate/qucs_ar.ts.stamp
cd /usr/src/RPM/BUILD/qucs-s-1.1.0/x86_64-alt-linux/translations && /usr/share/qt5/bin/lupdate @ -ts /usr/src/RPM/BUILD/qucs-s-1.1.0/translations/qucs_ar.ts
QFSFileEngine::open: No file name specified
lupdate error: List file '' is not readable.
gmake[2]: *** [translations/CMakeFiles/translations.dir/build.make:177: translations/.lupdate/qucs_ar.ts.stamp] Error 1
gmake[2]: Leaving directory '/usr/src/RPM/BUILD/qucs-s-1.1.0/x86_64-alt-linux'
gmake[1]: *** [CMakeFiles/Makefile2:896: translations/CMakeFiles/translations.dir/all] Error 2 `
![Screenshot_20230714_152706](https://github.com/ra3xdh/qucs_s/assets/13087750/0ea06703-2c72-4b20-90f7-9153a36ae28f)
![Screenshot_20230714_153026](https://github.com/ra3xdh/qucs_s/assets/13087750/8d7703c1-48d4-4dcb-a53a-548df630deef)
![Screenshot_20230714_153305](https://github.com/ra3xdh/qucs_s/assets/13087750/8c1e974c-1095-497f-943e-6b08da518626)

**Comment by antohami** [comment]
The issue has been fixed in the `current` branch. It is possible to update translations.

**Comment by ra3xdh** [comment]
Russian translations has been updated by #324. Native speaker required for other languages. Closing for now as completed.
