### ISSUE TITLE
Monte-carlo simulation 

### ISSUE THREAD

**Issue by cmat21** [ra3xdh/qucs_s#295]
Hello, is there any example of Monte Carlo simulation in Qucs-s?

**Comment by ra3xdh** [comment]
Look at this example (attached zip) provided by @Radvall It contains MonteCarlo simulation with Nutmeg script and using external processing with Python.

[MonteCarlo.zip](https://github.com/ra3xdh/qucs_s/files/12157436/MonteCarlo.zip)

**Comment by ra3xdh** [comment]
No further news from issue reporter. Assume the problem with MonteCarlo simulation has been resolved. Closing this.
