### ISSUE TITLE
Mistake on the website

### ISSUE THREAD

**Issue by pihie** [ra3xdh/qucs_s#297]
I’m not sure if the website https://ra3xdh.github.io/ relates to this project and if this should be discussed here, but there’s a mistake, it says contibuition guide, instead of contribution guide
![IMG_2632](https://github.com/ra3xdh/qucs_s/assets/75097845/153be0cd-e29e-4dcd-9152-22a492472f61)

**Comment by pihie** [comment]
If anyone can say where I can change it, I can do that myself

**Comment by ra3xdh** [comment]
I have fixed the typo. The HTML source code of the Qucs-S website is located in this repository: https://github.com/ra3xdh/ra3xdh.github.io
