### ISSUE TITLE
Getting Unknown Component errors with a fresh build 

### ISSUE THREAD

**Issue by hatsunearu** [ra3xdh/qucs_s#30]
Hi, maybe I'm missing something dumb but I am having unknown component errors opening the supplied examples. The wilkinson.sch is one of the ones I can't open--it complains that Pac is an unknown component.

Could I get some guidance on what's going on?

I'm using v. 0.0.21 and I compiled it with Ubuntu 19.10, and installed it with a prefix of `$HOME/qucs/`

**Comment by ra3xdh** [comment]
The `Pac` component belongs to S-parameter simulation. This simulation mode is not supported by SPICE kernels. This component is marked as unknown to avoid possible simulation errors. Replace it by the AC source and use AC simulation when using the SPICE kernels.
