### ISSUE TITLE
Add a checkbox in the properties of the "step" parameter

### ISSUE THREAD

**Issue by cmat21** [ra3xdh/qucs_s#314]
Hi, could you consider adding a checkbox in the properties of the "step" parameter?
Greetings
![parameter_sweep_step](https://github.com/ra3xdh/qucs_s/assets/70080894/c275283b-2f84-4dbb-976e-b9ab05ce2e15)

**Comment by ra3xdh** [comment]
The `Step` is a virtual parameter and not saved in the schematic file. It is calculated dynamically based on `Points` and range. The `Points` always has priority on step. That's why the `Step` input filed doesn't have the checkbox like other input fields.

**Comment by cmat21** [comment]
Ok, now I understand the problem, although I think having the step parameter available gives more flexibility to the configuration.
