### ISSUE TITLE
Capital D not allowed in Edit Subcircuit Properties menu Description Entry

### ISSUE THREAD

**Issue by tomhajjar** [ra3xdh/qucs_s#346]
Capital "D" is not allowed anywhere in the Edit Subcircuit Properties Description Entry for the specific file Ideal_LPF2_model.sch. It isn't an issue for Ideal_LPF1_model.sch. 

I cannot enter "DC level". Only "C level" is allowed. I haven't tested every other letter for restrictions. Other menu lines don't seem affected.

![2023-10-30_075850](https://github.com/ra3xdh/qucs_s/assets/102838604/1ad671eb-bc6c-43e1-9046-d3073bfa3f45)
[Ideal_LPF_prj.zip](https://github.com/ra3xdh/qucs_s/files/13204994/Ideal_LPF_prj.zip)

**Comment by ra3xdh** [comment]
Yes, I confirm this bug. It seems the input filed is using wrong validator. The fix will follow.

**Comment by ra3xdh** [comment]
Fixed on `current` branch. Closing.
