### ISSUE TITLE
Qucs-S component graphics

### ISSUE THREAD

**Issue by tomhajjar** [ra3xdh/qucs_s#350]
Found a few issues with truncated Icon graphics.

![2023-11-02_110500](https://github.com/ra3xdh/qucs_s/assets/102838604/897428df-9cd4-45e9-8dfa-71da1ba7c035)

![2023-11-02_110917](https://github.com/ra3xdh/qucs_s/assets/102838604/74595e9e-1bad-4b49-bdc2-66b6e97a37e8)

**Comment by ra3xdh** [comment]
The component icon size is calculated based on component selection box. Some components have wrong selection box. I will add a fix soon.

**Comment by tomhajjar** [comment]
The Icon graphics can be fixed by just moving items. 

"SFFM" can be moved to the same datum as "VTRN"

Icouple can be fixed by moving the in and out components closer together.

**Comment by ra3xdh** [comment]
Fixed by #364
