### ISSUE TITLE
Controlled Sources delay functionality missing in ngspice

### ISSUE THREAD

**Issue by tomhajjar** [ra3xdh/qucs_s#351]
Should the Description for "T" be changed stating it is only used for Qucsator?

![2023-11-02_113736](https://github.com/ra3xdh/qucs_s/assets/102838604/aec91064-3699-4835-b48b-86546b843edc)

**Comment by ra3xdh** [comment]
Yes, the compatibility node should be added for T parameter.

**Comment by ra3xdh** [comment]
Description of the "T" property has been fixed. Closing.
