### ISSUE TITLE
Does AppImage include qucsator?

### ISSUE THREAD

**Issue by r00sta** [ra3xdh/qucs_s#36]
When trying to simulate using the AppImage I get the following error - 

> ERROR: Cannot start qucsator (No such file or directory)

I have installed ngspice but I thought qucsator is bundled with the appimage?

Cheers

**Comment by ra3xdh** [comment]
No, qucsator is  not included in AppImage. This simulation core is developed by another team and I am not responsible for it. You need to build and install qucsator separately. It doesn't depend on Qt4 and could be installed separately from Qucs package.
