### ISSUE TITLE
Lowercase sweep parameter not working

### ISSUE THREAD

**Issue by cmat21** [ra3xdh/qucs_s#380]
Hi, I found out that the lowercase sweep parameter is not working as expected. can you check this? (V 2.1.0 on W10)
![sweeping_issue1](https://github.com/ra3xdh/qucs_s/assets/70080894/89f24f53-0ec2-4f0e-b6e7-525d14232126)
[is_swept_issue1.zip](https://github.com/ra3xdh/qucs_s/files/13445479/is_swept_issue1.zip)

**Comment by ra3xdh** [comment]
Fixed on `current` branch.
