### ISSUE TITLE
Sweep value list not working as expected

### ISSUE THREAD

**Issue by cmat21** [ra3xdh/qucs_s#382]
The sweep values list does not work when I use scientific or engineering notation on the list values. It works without notation, just numbers. Could you check this? It may have been reported before.
![sweep_parameter_list_values](https://github.com/ra3xdh/qucs_s/assets/70080894/dc694534-a95c-4d0d-a99b-0a333d597c12)

**Comment by ra3xdh** [comment]
Fixed on `current` branch. The fix will be available since the next release.
