### ISSUE TITLE
Active Filter Tool confusion

### ISSUE THREAD

**Issue by tomhajjar** [ra3xdh/qucs_s#398]
I found an old issue for the Active Filter Tool for Qucs mentioned by @mhx-gh in the link below.

https://github.com/Qucs/qucs/issues/1076

Capacitors values are in "uF" and Resistors in "kOhm" yet capacitance isn't in "uF" but resistance is in "kOhm". I realize they are correct in the schematic but it is confusing. 

Also the "default" settings are Butterworth with 3dB of Ripple. Ripple would be appropriate for Chebyshev or Cauer but not Butterworth which is “maximally flat”.

I made a few examples a while ago using ngspice math functions in Nutmeg to calculate gain (dB), unwrapped phase (deg) and group delay. They may be useful for examples.

![2023-12-13_141426](https://github.com/ra3xdh/qucs_s/assets/102838604/93e4b3b1-a77b-46df-888e-842a8e892e4e)

![2023-12-13_141636](https://github.com/ra3xdh/qucs_s/assets/102838604/961ca0eb-ed7d-4e8b-b564-6b4bfd5ca027)

![2023-12-13_143943](https://github.com/ra3xdh/qucs_s/assets/102838604/a7eca5de-fc7e-4ab3-b01e-3fc59ee6045d)

[Active_Filters_ngspice_prj.zip](https://github.com/ra3xdh/qucs_s/files/13664903/Active_Filters_ngspice_prj.zip)

**Comment by ra3xdh** [comment]
See #516 for fix of the part table
