### ISSUE TITLE
Update Matching Tool to Qucs 0.0.20 Version

### ISSUE THREAD

**Issue by tomhajjar** [ra3xdh/qucs_s#401]
Any plans to update the Qucs 0.0.19/Qucs-S Matching Tool to the version in Qucs 0.0.20? 

https://github.com/Qucs/qucs/pull/666 

The attached test schematics done by @andresmmera work with qucsator from Qucs 0.0.20. The planned qucsator_rf, should work as well.

![2023-12-19_101858](https://github.com/ra3xdh/qucs_s/assets/102838604/5c372467-f347-41a3-8fa1-320e91b44454)

[Matching_Tool_tests_prj.zip](https://github.com/ra3xdh/qucs_s/files/13717267/Matching_Tool_tests_prj.zip)

**Comment by ra3xdh** [comment]
Yes, I will look how https://github.com/Qucs/qucs/pull/666 could be backported. This would be useful feature.

**Comment by ra3xdh** [comment]
Matching tool backported by #662
