### ISSUE TITLE
Greyed out choices in Spice .Model

### ISSUE THREAD

**Issue by tomhajjar** [ra3xdh/qucs_s#404]
Why is the buttons for the .Model menu disabled? One can't delete or move entries. 

![2023-12-22_114059](https://github.com/ra3xdh/qucs_s/assets/102838604/9ae64aac-3673-453c-a40b-cc3adbb7040c)

**Comment by ra3xdh** [comment]
This is done intentionally. The accidentally moving of the lines up/down on the multiline model  may lead to issues that will be hard to debug.

**Comment by ra3xdh** [comment]
Assume the question is answered. Closing as resolved.
