### ISSUE TITLE
Nutmeg Scripting for Power Amplifier Wingspread Analysis

### ISSUE THREAD

**Issue by tomhajjar** [ra3xdh/qucs_s#405]
I'm trying to recreate a PA "Wingspread" example supplied with ngspice in Qucs-S. The analysis is popular on the diyAudio forum using LTSpice so I recreated the ngspice example using LTSpice. LTSpice will plot the data using a single function, d(v(out)). ngspice seems to require a long script. I'm not having luck getting the ngspice script to work in Qucs-S. Specifically I cannot plot anything since the *.dat.ngspice datasets are blank.

The original ngspice example plots for Rload = 4, 6 and 8 Ohms. I created a version with RLoad = 8 Ohms. 

I created another file with a simplified Nutmeg script based on an old ngspice analysis. Same problem, the *.dat.ngspice datasets are blank.

Qucs-S will not let you name a net +V/-V or use +/- but ngspice does. Any reason?

![ngspice_RL_8](https://github.com/ra3xdh/qucs_s/assets/102838604/331435ab-e09a-446f-b0fe-c4f38c728b6b)

![LTSpice_RL_8](https://github.com/ra3xdh/qucs_s/assets/102838604/259fad26-77ba-48f8-b760-4ce52745ad6e)

![Qucs-S_RL_8](https://github.com/ra3xdh/qucs_s/assets/102838604/3303fe85-61a7-4b78-b4a7-3244b9569d34)

![2023-12-24_235844](https://github.com/ra3xdh/qucs_s/assets/102838604/64b8c5e4-dddc-4cef-8063-424de00f219f)

[Audio_Output_Linearity_prj.zip](https://github.com/ra3xdh/qucs_s/files/13764000/Audio_Output_Linearity_prj.zip)

**Comment by ra3xdh** [comment]
You don't need to use the script to perform this simulation. Everything could be made using the Par.Sweep and equations. The script was needed to emulate parameter sweep that is provided by means of GUI. Look at the attached example.
![image](https://github.com/ra3xdh/qucs_s/assets/4920080/dc90aeea-2688-4eec-abce-fd121f5fd9af)

**Comment by tomhajjar** [comment]
Thanks.

I'm still confused why the *.dat.ngspice data sets are blank. "Data" was being written to the file specified in the script.  I thought I followed what was done in Potentiometer_Nutmeg.sch.

**Comment by ra3xdh** [comment]
> I'm still confused why the *.dat.ngspice data sets are blank.

You are trying to write the variable that is obtained in a loop. The vectors may be reinintialized after each loop operation. You have only to form the custom ouput with `write` and `appendwrite` here. Other combinations will not work.

On the other hands you need not to use the Par.Sweep emulation with loop and script here. I have implemented variable sweep a long time ago. See #189 The potentiometer device itself will be available since the next release See #122

**Comment by ra3xdh** [comment]
Closed as resolved.
