### ISSUE TITLE
Backward schematic compatibility

### ISSUE THREAD

**Issue by tomhajjar** [ra3xdh/qucs_s#407]
When testing different revisions of "Qucs" one is forced to use a text editor to open a "new" schematic in older revisions of "Qucs".

I'm use to editing and converting "Qucs" files in a text editor but others may not be.

**Comment by ra3xdh** [comment]
This is expected and done intentionally. The versioning has only forward compatibility. Qucs-S asks if the circuit could be opened from the newer version. For the most of cases everything should be loaded.  But you cannot open Qucs-S circuit with Qucs. The opposite is possible.

**Comment by ra3xdh** [comment]
I have just checked this. I am able to open Qucs-S v24.1.0 schematic using Qucs-S v1.0.1 after pressing "Yes" in the dialog.

**Comment by ra3xdh** [comment]
There exists "Load documents fro future version" setting. Set this option in the application settings dialog if you need to test different versions. This will load every schematic without version check.
![image](https://github.com/ra3xdh/qucs_s/assets/4920080/63d73214-a398-4786-af59-aa2f33213eba)

**Comment by tomhajjar** [comment]
Thanks.
