### ISSUE TITLE
Schematic Editor: Deactivate/Activate of Blocks Does Not Work Consistent 

### ISSUE THREAD

**Issue by 3813127458** [ra3xdh/qucs_s#408]
Qucs-S 2.1.0

Test_1.sch and Test_2.sch contain same circuit for simulation.
Test_1 has additional deactivated block, which cause a simulation error.

Deactivated blocks should not disturb or impact activated schematics.

[Demo.zip](https://github.com/ra3xdh/qucs_s/files/13772789/Demo.zip)
https://github.com/ra3xdh/qucs_s/assets/75557552/0efe7b8e-d2f3-4c6b-90e8-0e9a49602eed

**Comment by ra3xdh** [comment]
It seems, Nutmeg scripts cannot be deactivated. I will add a fix soon.

**Comment by ra3xdh** [comment]
Fixed on `current` branch. Closing as completed.
