### ISSUE TITLE
Tuner Slider Does Not Handle Numbers and Units in .PARAM Block Correctly

### ISSUE THREAD

**Issue by 3813127458** [ra3xdh/qucs_s#409]
Qucs-S 2.1.0

Problem Demo:

[Demo.zip](https://github.com/ra3xdh/qucs_s/files/13772873/Demo.zip)

**Comment by ra3xdh** [comment]
I cannot reproduce the problem using the build from Git. Everything works as expected. The reported problem was already fixed by https://github.com/ra3xdh/qucs_s/commit/d0b6e74a7aa76ea72cff5e7b8b0800f15430ba5a
