### ISSUE TITLE
Identifying missing Spice model prior to sending netlist to ngspice

### ISSUE THREAD

**Issue by tomhajjar** [ra3xdh/qucs_s#419]
I made a mistake copying files to a new project directory testing using voltage regulators in unconventional circuits. Goal is to better screen voltage regulator Spice models for use in the library.

I forgot one Spice model, LM1084_ADJ.cir used to make LM1084_ADJ.sch. Qucs didn't flag LM1084_ADJ.cir was missing and sent the netlist to ngspice which returned an error. Should Qucs-S flag the model is missing?

![2023-12-29_095942](https://github.com/ra3xdh/qucs_s/assets/102838604/0f124c9b-1f2b-42ab-83cb-330955ab70c9)

![2023-12-29_102751](https://github.com/ra3xdh/qucs_s/assets/102838604/b75d7033-a201-41b7-a3b5-22dd3462f4f6)

[Voltage_Regulator_Amplifiers_prj.zip](https://github.com/ra3xdh/qucs_s/files/13794640/Voltage_Regulator_Amplifiers_prj.zip)

**Comment by ra3xdh** [comment]
Qucs-S tracks missing models only for system devices. It doesn't check if the SpiceFile contains a valid netlist. The library devices are not checked for validity too.
