### ISSUE TITLE
Schematic Editor: Netnames Are Not Moved inside Object Group

### ISSUE THREAD

**Issue by 3813127458** [ra3xdh/qucs_s#422]
Qucs-S 24.1-7df0e3e9

Net names are not moved as member of an object group:

![Move_Net_Names_Inside_Group](https://github.com/ra3xdh/qucs_s/assets/75557552/afaedf8b-8642-46e3-a30e-c88fac28624e)

**Comment by ra3xdh** [comment]
Yes, I confirm this problem. The net names may be not selected by selection rectangle. This appears time to time.
