### ISSUE TITLE
Missing https://download.opensuse.org/repositories/home:/ra3xdh/Fedora_39/

### ISSUE THREAD

**Issue by hlovdal** [ra3xdh/qucs_s#424]
There are Fedora 36, 37 and 38 repos available at https://download.opensuse.org/repositories/home:/ra3xdh/ however there none for the newly made 39 release. I assume this is just a OBS configuration issue of adding a new build (and possibly removing 36 and 37 since they are EOL).

(There were no failures in running `rpmbuild --rebuild https://download.opensuse.org/repositories/home:/ra3xdh/Fedora_38/src/qucs-s-2.1.0-3.1.src.rpm` locally on my Fedora 39 desktop.)

**Comment by ra3xdh** [comment]
I have just added Fedora-39 repository: https://download.opensuse.org/repositories/home:/ra3xdh/Fedora_39/ Closing as completed.
