### ISSUE TITLE
Can't create plot vector from onoise_spectrum

### ISSUE THREAD

**Issue by dwarning** [ra3xdh/qucs_s#430]
I want catch noise current into collector. For that I want take sqrt(onoise_spectrum)/1e6 in an vector Icn for plotting. The log says onoise_spectrum is not available. But it is.

![Bildschirmfoto vom 2024-01-02 18-41-09](https://github.com/ra3xdh/qucs_s/assets/18441932/e7f18562-f955-445b-90b8-00b055fdbe4c)

Pure netlist of this setup works with ngspice on command line.

**Comment by dwarning** [comment]
Perhaps it helps to understand the problem I attached my schematic file. In simulation log window comes that onoise_spectrum is unknown or has zero length.

[bjt_noise_I.zip](https://github.com/ra3xdh/qucs_s/files/13828257/bjt_noise_I.zip)

**Comment by ra3xdh** [comment]
The equations cannot be attached to noise simulation. I will try to provide a fix soon.

**Comment by ra3xdh** [comment]
#463 resolves this issue.

**Comment by tomhajjar** [comment]
On a side note, when you select "View All" on the schematic above the screen looks like below: 

I cannot select the item off-screen causing this.

![2024-01-31_183431](https://github.com/ra3xdh/qucs_s/assets/102838604/e58b1d6d-6350-4c2f-aad0-5ab8c10cee3d)

**Comment by ra3xdh** [comment]
Fixed via #513
