### ISSUE TITLE
Proper Voltage Source Format

### ISSUE THREAD

**Issue by tomhajjar** [ra3xdh/qucs_s#438]
Can you explain why one format of input V "works" and the other doesn't. 

Isn't redundant to use "V=DC 0 AC 1 0 sin(0 1 796k 0 0 0)" versus "V=sin(0 1 796k 0 0 0)"?

![2024-01-07_135813](https://github.com/ra3xdh/qucs_s/assets/102838604/e1ca2c7a-181a-4f64-98d7-c4f7890c1fd3)

![2024-01-07_135935](https://github.com/ra3xdh/qucs_s/assets/102838604/8ff1d45f-2027-487a-910b-692b6e678764)

[Matching_Network.zip](https://github.com/ra3xdh/qucs_s/files/13854616/Matching_Network.zip)

**Comment by ra3xdh** [comment]
> Can you explain why one format of input V "works" and the other doesn't.

It is not a Qucs-S bug. You have wrong SPICE syntax. The AC level is not defined and Ngspice assumes it is zero. And you obtain division by zero error.  TRAN simulation works as expected with this source. The AC level should be always defined explicitly if you are using full SPICE syntax. The blue source defines AC level automatically, but your should define everything by yourself if you decided to use the red source.

**Comment by tomhajjar** [comment]
I'm confused. 

How does my input string "V=sin(0 1 796k 0 0 0)" not define the voltage input as DC offset=0, AC Amplitude=1, F=796k...etc? The string matches the manual as shown below.

How is "V=DC 0 AC 1 0 sin(0 1 796k 0 0 0)" not redundant in specifying DC=0 and AC=1 twice?

![2024-01-08_074931](https://github.com/ra3xdh/qucs_s/assets/102838604/68db03d7-cde1-45ea-a235-fda4d531bf3e)

**Comment by tomhajjar** [comment]
I Grep'd the ngspice examples folder and found many variations of Voltage source syntax including the one I used.

**Comment by ra3xdh** [comment]
There is no Qucs-S error here. The `SIN` defines the model for TRAN only. AC level and TRAN level may be different. Try the following simulation in CLI and you will see that your source produces only zero output on AC. Here is the screenshot. Probably it is Ngspice bug or manual may be read misleading here. 
![image](https://github.com/ra3xdh/qucs_s/assets/4920080/c60162c0-55cc-4636-bd35-c1474bee531f)

**Comment by tomhajjar** [comment]
Changing the string to V=DC 0 AC 1 also works for AC analysis. It was a annoying using such a long string.


![2024-01-08_083542](https://github.com/ra3xdh/qucs_s/assets/102838604/85a53bcb-412f-41b8-9f92-a7075627c2a3)
