### ISSUE TITLE
Rotate Voltage/Current Probe

### ISSUE THREAD

**Issue by edson-acordi** [ra3xdh/qucs_s#44]
Hi, when the voltage/current probe is rotated, it is not possible anymore to connect a wire.
Thank you.

**Comment by thomaslepoix** [comment]
Hi, I already saw it in Qucs with other components than probes, but it happens _sometimes_

**Comment by zcx2020** [comment]
Happens with a lot of components.  To fix select the component, Positioning, Set on Grid OR Ctrl-U.

**Comment by edson-acordi** [comment]
Ok, thank you!
