### ISSUE TITLE
Schematic Editor: Edit Component Properties Remove Bug

### ISSUE THREAD

**Issue by 3813127458** [ra3xdh/qucs_s#440]
"Edit Component Properties" -> "Remove" gives wrong result:
The parameters CPL and CPC should be removed and trin should remain.
But as wrong result CPC remains.

[RTF_N4_master.zip](https://github.com/ra3xdh/qucs_s/files/13865978/RTF_N4_master.zip)

https://github.com/ra3xdh/qucs_s/assets/75557552/374f0078-c9bb-4d8b-95bf-9cf67c91c7b9

**Comment by tomhajjar** [comment]
Sorry I never mentioned this...

This happens on ALL the PARAM, Qucs Formula, Nutmeg Formula...etc forms. Doesn't matter what item/line you select/highlight, the bottom (or is it the top) item/line gets deleted when you click Remove.

The ONLY way I found to get around this is to use the Move UP button (or is it the Move Down button) and move EVERYTHING you DON'T want deleted UP (or is it DOWN) out of the way before you click Remove . 

![2024-01-08_173850](https://github.com/ra3xdh/qucs_s/assets/102838604/36cc01b2-c228-43fb-834b-c4267296f25c)

**Comment by ra3xdh** [comment]
Please test the latest commit on the `current` branch. I have added a fix for this.

**Comment by 3813127458** [comment]
So far it works fine on branch 24.1-6791ef07
I will test it further by using.

Would be nice if it is possible to select multiple items for removal by `Ctrl` + item + item ...
The `Add`, `Move Up` and `Move Down` buttons need to be locked in case multiple items are selected.
However, this behavior is of minor importance... could be skipped or implemented later.
