### ISSUE TITLE
Templates for ngspice

### ISSUE THREAD

**Issue by tomhajjar** [ra3xdh/qucs_s#441]
I'm slowly making a "Template" folder with analysis examples including Nutmeg equations needed to plot data.

![2024-01-09_115406](https://github.com/ra3xdh/qucs_s/assets/102838604/3054a7a1-3622-4d0a-82d4-5adedb6bff3d)

**Comment by tomhajjar** [comment]
I've improved most of the examples in the project. Will be updating it this week.

**Comment by ra3xdh** [comment]
I have uploaded Ngspice templates to `examples/templates_ngspice` subdirectory. Closing as completed. Thanks for the contribution!

**Comment by iwbnwif** [comment]
Thank you, these templates are really useful. A few observations:
1. AC_TRAN_FOUR_OpAmp.sch has the "open data display after simulation" checked even though there are no charts on the .dpl page.
2. genericopa_sub.sch is missing file genericopa.cir
3. Pwr-Amp_wingspread_analysis.sch doesn't appear to have a 'dd' label, thus v(dd) is invalid?
4. S-parameter_file_analysis.sch is missing FL455kHz.s2p

**Comment by ra3xdh** [comment]
> genericopa_sub.sch is missing file genericopa.cir

I have added missing file

> S-parameter_file_analysis.sch is missing FL455kHz.s2p

I excluded this schematic from examples pack. The attached s2p file was about 1Mb size. It's better avoid to keep such large files in git.

**Comment by iwbnwif** [comment]
> "dd" is in the nutmeg equation.
Ah, sorry I see it now. Should the Nutmeg Simulation=SW1 instead of =dc?

**Comment by tomhajjar** [comment]
@ra3xdh 

I redid the s-parameter file example to use the s-parameter file "137MHz_BPF.s2p". 

This is the same filter in S-parameter_passive_analysis.sch so is a better example.

On a side note, 137MHz_BPF.s2p was created by Qucs using qucsconv on the original LC filter. It's a feature Qucs-S doesn't have.

![2024-02-02_134845](https://github.com/ra3xdh/qucs_s/assets/102838604/baa7453d-34f6-4762-a020-e7bab46214e8)

[Templates_ngspice_prj.zip](https://github.com/ra3xdh/qucs_s/files/14144046/Templates_ngspice_prj.zip)

**Comment by iwbnwif** [comment]
@tomhajjar 
Shouldn't this be Simulation=SW1?
![qucs-s](https://github.com/ra3xdh/qucs_s/assets/11036083/815ddf6f-19e0-4cb4-87a4-290df36e5eb9)

**Comment by tomhajjar** [comment]
I created the schematic from the ngspice example, 100W.sp. I simplified the analysis to 8 Ohms.

Vadim wrote the Nutmeg equations and Parameter sweep entries and got it to work. See #405.

https://github.com/ra3xdh/qucs_s/issues/405
