### ISSUE TITLE
Spice model.CIR versus model.cir

### ISSUE THREAD

**Issue by tomhajjar** [ra3xdh/qucs_s#443]
A Spice model with the suffix .CIR is characterized as Others instead of Spice. Rename it to .cir and it's Spice...

![2024-01-08_213723](https://github.com/ra3xdh/qucs_s/assets/102838604/a479a973-6690-417a-9ee0-9f94a16ed5b4)

**Comment by ra3xdh** [comment]
Yes, the project tree was registry dependent. I have just added a fix. Closing as completed.
