### ISSUE TITLE
Add YLIN (s2p) device support for Xyce

### ISSUE THREAD

**Issue by ra3xdh** [ra3xdh/qucs_s#452]
### Discussed in https://github.com/ra3xdh/qucs_s/discussions/450

<div type='discussions-op-text'>

<sup>Originally posted by **michal777** January 12, 2024</sup>
In xyce reference guide (https://xyce.sandia.gov/files/xyce/Xyce_Reference_Guide_7.6.pdf) there's note about component:

_2.3.24. Linear device
The linear (YLIN) device allows an S-, Y-, or Z-parameter model to be used to define an N-port device. It
is mostly commonly used as part of a Harmonic Balance (HB) analysis_

Is it possible to do harmonic balance simulation with touchstone file in qucs-s? I can't find s-parameters file block in components when xyce is selected.</div>

**Comment by tomhajjar** [comment]
Does the QucsXyceLib1.lib done by Mike Brinson in 2021 have any relevance? It has a source called Component port_device_sin.

![2024-01-12_074233](https://github.com/ra3xdh/qucs_s/assets/102838604/e8e4e08a-d0d0-41de-a86a-c01a6a75ffcd)

[QucsXyceLib1.zip](https://github.com/ra3xdh/qucs_s/files/13919173/QucsXyceLib1.zip)

**Comment by ra3xdh** [comment]
I have added the support for YLIN device. It will be available since the next release. It seems that Xyce supports only HB simulation for this device type. Closing as completed.

**Comment by michal777** [comment]
Thanks,
I'm trying to test it. I'm not sure the order of nets is correct. "Ref" node of s2p or s3p is grounded but in the netlist there are no connections to ground.
![image](https://github.com/ra3xdh/qucs_s/assets/8597537/87c2b8a3-d022-47b0-9b59-f95c47e63b81)

**Comment by ra3xdh** [comment]
I have fixed the pins order by the recent commit on `current` branch. Please update.
