### ISSUE TITLE
How to build qucs_s on Windows?

### ISSUE THREAD

**Issue by NoClassDefError** [ra3xdh/qucs_s#454]
Hello, I'm doing some additional development based on qucs_s on Windows. 

After installing the flex and bison dependencies, I attempted to build the project using both the Visual Studio 2019 compiler and the MinGW64 8.1 compiler; however, both attempts resulted in errors. How can I build qucs_s on Windows? Is it necessary to modify the code?

![屏幕截图 2024-01-13 195738](https://github.com/ra3xdh/qucs_s/assets/46603898/9d657ad2-a3ed-4e0f-a53b-4720929b4b32)

**Comment by ra3xdh** [comment]
VisualStudio build is not supported. The using of standalone MinGW installation in principle should work, but is not recommended. The best way is to install MSYS2 https://www.msys2.org/ It provides Unix shell and package manager on the Windows system. The additional CMake options are not required. @zergud is using Windows as the main development platform. Probably he can advice something.

**Comment by NoClassDefError** [comment]
Thanks very much for your help!  I've attempted using MSYS2-mingw64 with multiple source versions, and unfortunately, I encountered a consistent compiling error indicating that a header file, q3scrollview.h, cannot be found, even though it does exist. The error message is provided below:
![屏幕截图 2024-01-14 171943](https://github.com/ra3xdh/qucs_s/assets/46603898/e0347af0-1539-40cb-9c74-cf70da953bf0)



> VisualStudio build is not supported. The using of standalone MinGW installation in principle should work, but is not recommended. The best way is to install MSYS2 https://www.msys2.org/ It provides Unix shell and package manager on the Windows system. The additional CMake options are not required. @zergud is using Windows as the main development platform. Probably he can advice something.

**Comment by ra3xdh** [comment]
I cannot reproduce the mentioned build error. Everything works as expected on my MSYS2 installation. Are you sure you have set the proper Makefile format with "-G" option? Cmake on MSYS2 may require explicit setting of this option. I am using `cmake -G "MinGW Makefiles <source_dir>`

**Comment by NoClassDefError** [comment]
Thanks for your help! By properly setting the cmake generator to MinGW64, I've successfully build and run the qucs-s!
