### ISSUE TITLE
conda install qucs?

### ISSUE THREAD

**Issue by joamatab** [ra3xdh/qucs_s#458]
How can we make a conda-forge package of qucs?

We are exploring [Schematic driven layout ](https://gdsfactory.github.io/gplugins/notebooks/20_schematic_driven_layout.html) for [gdsfactory](https://gdsfactory.github.io/gdsfactory/) using Qucs 

@proppy
@nikosavola

**Comment by ra3xdh** [comment]
Hello, I have a little interest in maintaining conda package for Qucs-S myself. But I will accept if someone will provide a package. Please submit necessary PRs if required.

**Comment by ra3xdh** [comment]
> Qucs

Also what exactly package do you need? Qucs-S, Qucs or Qucsator?

**Comment by ra3xdh** [comment]
Still be no response on this. I am unable to maintain conda package myself. Closing this. May be reopened if someone will take maintenance on conda package.
