### ISSUE TITLE
Simulation -> Show last netlist F6 doesn't show the last netlist

### ISSUE THREAD

**Issue by kmihaylov** [ra3xdh/qucs_s#46]
Hello. Using Qucs-s 0.0.22 with xyce/ngspice. I'm trying some simple schematic and I noticed that Qucs-s doesn't show the correct netlist file.

I changed the default simulator from xyce to ngspice and it still shows me the incorrect one (it is actually a netlist from another project, I have two projects in the Projects tree from the left menu).

I changed the default netlist and simulator output directory, restarted Qucs-s and again the same old netlist.

Last, I removed the project directory that the shown netlist should reside in and despite that F6 still shows me this old netlist and not the latest.

Otherwise the correct netlist file is %workdir%/spice4qucs.cir

**Comment by zcx2020** [comment]
Please see post #41 F6.
