### ISSUE TITLE
Transformers.lib error

### ISSUE THREAD

**Issue by tomhajjar** [ra3xdh/qucs_s#460]
The Transformers.lib I received with Qucs-S 24.1.0 is the older version. I found out during testing of ngspice 42plus...

Attached is the new version done last year and the test suite loosely based on the Qucs-S online Help.

[Transformers.zip](https://github.com/ra3xdh/qucs_s/files/13940422/Transformers.zip)

[Transformer_Lib_Test_prj.zip](https://github.com/ra3xdh/qucs_s/files/13940653/Transformer_Lib_Test_prj.zip)

**Comment by ra3xdh** [comment]
I have uploaded the `Transformer.lib` provided in #367 to the repository in the last week. The demo package that I shared with you doesn't have this version. Do you have a newer version than posted in #367?

**Comment by tomhajjar** [comment]
To be safe I would use the Transformers.lib attached above. 

I checked what I uploaded a while ago and it didn't match what came with Qucs-S 24.1.0...

**Comment by tomhajjar** [comment]
Attached are 4 projects containing various test circuits for Transformers.lib and transformer sub-circuits used to create Transformers.lib. They should be very useful for new users and speed learning.

[Transformer_projects.zip](https://github.com/ra3xdh/qucs_s/files/13942816/Transformer_projects.zip)

**Comment by ra3xdh** [comment]
The library version attached in the first message and the library in the repository differs only by variable registry. The library update is not needed, because Ngspice is not registry dependent. Closing this.
