### ISSUE TITLE
Transformer Netlist and Library wrong

### ISSUE THREAD

**Issue by tomhajjar** [ra3xdh/qucs_s#461]
During ngspice 42plus testing I found an issue with an old project that replicated the work done by Mike Brinson to create Transformers.lib. My versions of the PositiveCouplingPS and NegativeCouplingPS transformers don't work anymore. Qucs flagged "Warning: Unusual leading characters".

The Netlist and Library I created are full of "=" characters. I cannot see what caused this or why the simulation data is wrong.

![Transformer_opposite_coupling](https://github.com/ra3xdh/qucs_s/assets/102838604/6f061996-5a59-4e43-be91-b65ce81281f9)
![2024-01-15_115807](https://github.com/ra3xdh/qucs_s/assets/102838604/290e2e0b-0985-4fcd-b404-9a3182ce164c)
![2024-01-15_120254](https://github.com/ra3xdh/qucs_s/assets/102838604/80f5768a-0ca7-46dc-b415-a028af1aa6f0)
![2024-01-15_120551](https://github.com/ra3xdh/qucs_s/assets/102838604/48f8fd50-2809-4865-88d4-bf984ab67793)
![2024-01-15_121506](https://github.com/ra3xdh/qucs_s/assets/102838604/cfeb48a8-3536-4939-a86c-95cc88f7e2cc)

[Transformer_sub_Test_prj.zip](https://github.com/ra3xdh/qucs_s/files/13941474/Transformer_sub_Test_prj.zip)

**Comment by ra3xdh** [comment]
The inductors are containing the `=` symbols on the continuation lines. You have to delete these symbols manually and the simulation error will be gone. I don't know why the `=` symbols appeared here. I never observed such issues on my schematics containing the red inductors and cannot reproduce this. 
![image](https://github.com/ra3xdh/qucs_s/assets/4920080/a856266f-40c6-4cc6-ae80-d1ee1d76b29f)

**Comment by tomhajjar** [comment]
I tried to open the schematics with Qucs-S 0.0.24 and subcircuit symbols won't load. I don't remember this happening before.

![Qucs-S 0 0 24](https://github.com/ra3xdh/qucs_s/assets/102838604/ce649432-e305-4e64-aa24-86acbf716101)

![2024-01-15_125217](https://github.com/ra3xdh/qucs_s/assets/102838604/f4712797-dfcb-4add-a986-44f17b186035)
