### ISSUE TITLE
License Question: Which one was used by this project, GPL-2.0-only or GPL-2.0-or-later

### ISSUE THREAD

**Issue by CoelacanthusHex** [ra3xdh/qucs_s#464]
I maintain the package of this project in [archlinuxcn](https://github.com/archlinuxcn/repo). Recently, Arch Linux enforced using the SPDX identifier via RFC16[^1]. It differs from GPL-2.0-only and GPL-2.0-or-later. So I need to know which one was used in this project.
Thank You!

[^1]: https://gitlab.archlinux.org/archlinux/rfcs/-/blob/master/rfcs/0016-spdx-license-identifiers.rst

**Comment by ra3xdh** [comment]
I have just added an explicit SPDX license identifier `GPL-2.0-or-later` in the COPYING.

**Comment by CoelacanthusHex** [comment]
Thank you!
