### ISSUE TITLE
F5

### ISSUE THREAD

**Issue by zcx2020** [ra3xdh/qucs_s#47]
Let's say there are two schematics open in two tabs.

The first schematic has a problem which prevents ngspice from producing any useful results.

Press F2 and the Statusbar says Ngspice Warnings in last simulation! Press F5.  Correct.

The second schematic has no problem and is simulated without error.  If I switch to the second tab the Statusbar still displays the warning from the first tab.  Incorrect.

Now press F2 and the Statusbar says Ngspice no warnings.  Correct.
 
Switch back to the first tab and the Statusbar still says Ngspice no warnings.  Incorrect.

Should the warning message and log.txt somehow be local to each tab and preserved if another tab is simulated, so that F5 works correctly across tabs?

**Comment by ra3xdh** [comment]
This behavior is inherited from the basic Qucs project. In principle it could be rewritten in a following manner: every log file is connected to the specific schematic file, but not in the near future.

**Comment by zcx2020** [comment]
Understood.  Thanks anyway.
