### ISSUE TITLE
Qucs-s 2.1.0 doesn't render utf-8 characters correctly anymore

### ISSUE THREAD

**Issue by csrabak** [ra3xdh/qucs_s#471]
In windows 10, I've schematics since version 1.0.2 which employed local characters be it in the text boxes in the schematics, be it in the legends of the plots (saved in the .plt files).

When I open these projects with present 2.1.0 the i18n characters are rendered as a diamond with an interrogation in it!

Is it a regression bug or a new setting that has to be tuned?

**Comment by tomhajjar** [comment]
I'm not having any issues with Win 10. Can you post a schematic and a screen shot of the issue?

**Comment by ra3xdh** [comment]
I cannot reproduce this on Linux and Windows platforms. I have just created schematic in v1.0.1 and opened in the latest development build. The cyrillic UTF-8 letters are loader correctly. Could you post the `*.sch` file example with the broken symbols?

> the plots (saved in the .plt files).

Qucs-S doesn't produce `*.plt` files. Did you mean `*.dpl`?

![изображение](https://github.com/ra3xdh/qucs_s/assets/4920080/e76e00c4-c3f7-40df-81cb-656f2e4b599d)

**Comment by csrabak** [comment]
Yes I did mean `.dpl` 
![image](https://github.com/ra3xdh/qucs_s/assets/10200568/a106da81-2d49-480f-9477-587cbd262a20)
[mfb-bpf.zip](https://github.com/ra3xdh/qucs_s/files/13998251/mfb-bpf.zip)

Win 10 Single Lang Home Ed. Ver 22H2 OS compilation 19045.3930 Windows Feature Experience Pack 1000.19053.1000.0

**Comment by zergud** [comment]
need more investigation: what font do you have in settings?
I changed the text in your file and everything is displayed correctly

![image](https://github.com/ra3xdh/qucs_s/assets/869819/44b7f3cf-139a-4b92-b003-00fa215ec4a9)

**Comment by csrabak** [comment]
FWIW I've never bothered to change the defaults for the fonts, be it in Windows or Linux.

![image](https://github.com/ra3xdh/qucs_s/assets/10200568/6e0480fb-ff9a-4902-839b-da083b9803d2)

Thanks for looking at it.

**Comment by zergud** [comment]
for some reason your file is saved in ANSI encoding
I checked that all new dpl files are saved in utf-8 on my PC
:thinking:
![image](https://github.com/ra3xdh/qucs_s/assets/869819/29e80484-77ea-4e06-b62a-2291dda438a8)

**Comment by tomhajjar** [comment]
Will this program help?

https://github.com/amrali-eg/EncodingChecker

![2024-01-20_174533](https://github.com/ra3xdh/qucs_s/assets/102838604/bd536806-fc5c-4420-b855-5329d93c6b40)

**Comment by csrabak** [comment]
@zergud thanks for finding the suspect!

I cannot understand how that was done, as I am not a hacker of these tools at all, OTOH now the issue has been pinpointed, I think be it manually be it by using the tool @tomhajjar point to, I can go "repairing" the projects on a needed basis.

Thanks to all, as it seems at the moment this is not something epidemic I'm closing the issue.
