### ISSUE TITLE
Spectrum/FFT plot in Qucs versus ngspice

### ISSUE THREAD

**Issue by tomhajjar** [ra3xdh/qucs_s#474]
Wondering why "FFT" of V(out) is bipolar when ngspice plots the data and unipolar when Qucs-S plots it.

![2024-01-20_122439](https://github.com/ra3xdh/qucs_s/assets/102838604/7ce7dfb4-4ac9-40b7-a005-4e3b7b7a9db0)

![2024-01-20_122011](https://github.com/ra3xdh/qucs_s/assets/102838604/ce88eed8-d1ce-42ba-9d18-6cf1aac4179b)

[AC_Tran_Four_FFT_prj.zip](https://github.com/ra3xdh/qucs_s/files/13998690/AC_Tran_Four_FFT_prj.zip)

**Comment by ra3xdh** [comment]
This is related to complex numbers representation. Qucs plotting engine shows the magnitude of the complex number in the plots, but Ngspice plotting engine shows Re/Im part separately. The Im part of the spectrum density may be negative.
