### ISSUE TITLE
Suggestion: localization for diagram objects for ploting

### ISSUE THREAD

**Issue by csrabak** [ra3xdh/qucs_s#477]
Since we've localization for the GUI, I wonder if it is feasible at this point of the project to have the wording for the _diagrams_ objects, so we don't need to tranlate every time "gain", "frequency", etc. ?

**Comment by ra3xdh** [comment]
Qt supports only interface translation. The variable names come from SPICE dataset as is. It cannot be translated by means of Qt. Furthermore the variable names should be kept untouched.

**Comment by csrabak** [comment]
I see. I was not thinking of the variable names, only the strings that make the default legends of the graphs, etc.
