### ISSUE TITLE
Small typo in modal window Portuguese

### ISSUE THREAD

**Issue by csrabak** [ra3xdh/qucs_s#478]
![image](https://github.com/ra3xdh/qucs_s/assets/10200568/4a3b1973-1dac-4f27-83e7-886122b1ec6a)

The word in Portuguese is _transparent_ not "trasparent" (is lacking an 'n') in the tick box of the properties marker for Cartesian plots.

**Comment by ra3xdh** [comment]
Thanks for reporting! Fixed on `current` branch. Closing this.
