### ISSUE TITLE
Nutmeg equations using Fourier results of LM386

### ISSUE THREAD

**Issue by tomhajjar** [ra3xdh/qucs_s#480]
I can't figure out how to plot in dB the Four(v(out)). 

If I drive the LM386 into distortion, the dB FFT plot, S_dB=db(v(out)) clearly shows the distortion while the linear plot of Four(v(out)) does not. The Nutmeg equation menu does allow Four as a "Used simulation" so I chose fft. Another issue is figuring out what "variable" to use.

![2024-01-21_112633](https://github.com/ra3xdh/qucs_s/assets/102838604/9e58adbf-3da9-40fa-9cf3-1a35d119a034)

![2024-01-21_112647](https://github.com/ra3xdh/qucs_s/assets/102838604/0882da6d-db9c-403e-920c-a6a114f736cf)

![2024-01-21_112557](https://github.com/ra3xdh/qucs_s/assets/102838604/5fc383ef-0ef7-4c35-938f-0a80aa1919c5)

![2024-01-21_114118](https://github.com/ra3xdh/qucs_s/assets/102838604/5bc10594-f9b8-4213-a9bf-912c85c78bfc)

[LM386.zip](https://github.com/ra3xdh/qucs_s/files/14002043/LM386.zip)

**Comment by csrabak** [comment]
Just for the sake of dividing and conquering, have you tried a minimum example directly in ngspice?

I'm lost about some results of it alone itself (including the one already reported by you @tomhajjar )

**Comment by tomhajjar** [comment]
Unfortunately out of the 600+ examples provided by the ngspice team only one uses Fourier and I believe it was used in error, 100W.cir

**Comment by ra3xdh** [comment]
#517 should resolve this problem.

**Comment by ra3xdh** [comment]
My comment above was wrong. The attaching of Nutmeg equations is not allowed to FOUR simulation. The variables are only printed in the console or exported to the text file. Ngspice manual recommends to use FFT if the postprocessing with Nutmeg is needed.

**Comment by tomhajjar** [comment]
Vadim can you show how to use Nutmeg to get Four in dB?

Using the "Log left axis grid" setting blanks the screen

[AudioIC_prj.zip](https://github.com/ra3xdh/qucs_s/files/14214000/AudioIC_prj.zip)

**Comment by ra3xdh** [comment]
> Vadim can you show how to use Nutmeg to get Four in dB?

It is not possible by design. The FOUR results could be only printed in terminal. Ngspice manual recommends to use Spectrum analysis (FFT) instead.

**Comment by csrabak** [comment]
Am I doing something absolutely wrong running this example with ver 24.1?

I made two different schematics to circumvent the issue of not allowing FFT and AC in same.

When I run the AC one, the delay calculation doesn't get the older results:

![export-delay](https://github.com/ra3xdh/qucs_s/assets/10200568/07530eac-badb-4108-b5c1-76d6526d86ac)

**Comment by tomhajjar** [comment]
You should attach your files so others can help.

**Comment by HB9GKW** [comment]
I was struggling with the same need of plotting fourier output in dB. As a workaround you could change y axis settings to logarithmic left axis grid and change units to dB. Doing this may result in "invalid data" if fourier results are small negative numbers. Injecting a tiny DC level (1nV) via a choke was for me the solution to keep things running.
