### ISSUE TITLE
Typo or mixed language in file menu for Portuguese 

### ISSUE THREAD

**Issue by csrabak** [ra3xdh/qucs_s#482]
![image](https://github.com/ra3xdh/qucs_s/assets/10200568/0a086aad-c2ed-4b89-a8a6-67139c66730a)

The word should be **Exemplos**

And I submit for the "Refresh Search Path..." a hard to translate, but I've some voting supporting mine[!]:

_Atualizar o Caminho de Busca_...

The "Export as image..." is unanimous _Exportar como imagem_...

TIA

**Comment by ra3xdh** [comment]
Thanks for reporting! I have updated the PT translation.
