### ISSUE TITLE
qucs-s exports to log.txt file "ngspice-40 done" while installed ver is 42

### ISSUE THREAD

**Issue by csrabak** [ra3xdh/qucs_s#484]
In my windows 10 environment where I've not nsgspice (in fact c:\spice64\bin) in the path, nor any other programm which could be confused with,  whose test is in the command line issue `where ngspice_con` which comes empty.

However, in the 2.1.0 installation, after a simulation the line `ngspice-40 done` appears in the log.txt.

Is it spected behaviour?

Also in the properties modal window it seems there is not anymore an entry for ngspice location (I surmised when I saw at first, it could be because ngspice is finicky about its installation directory):

![image](https://github.com/ra3xdh/qucs_s/assets/10200568/a99fba63-954e-4340-a93f-4787477974c1)

**Comment by tomhajjar** [comment]
Here is my Windows configuration. It is user configurable so the specific folders are your choice. This can change in the future.

![2024-01-21_190258](https://github.com/ra3xdh/qucs_s/assets/102838604/eb7b42c1-0604-4625-a72d-01b5101c3d61)

![2024-01-21_190209](https://github.com/ra3xdh/qucs_s/assets/102838604/4767dc49-ad52-4453-a854-c0b7d0498619)

**Comment by ra3xdh** [comment]
> the line ngspice-40 done appears in the log.txt

I have no such line in the source code. Qucs-S doesn't check the Ngspcie version and doesn't report it. Please check you settings and shell variables.

**Comment by csrabak** [comment]
I've just checked and learned that qucs-s 2.1.0 comes with a ngspice executable (in fact two, including ngspice_con.exe) in its own bin directory[^1].

![image](https://github.com/ra3xdh/qucs_s/assets/10200568/c02dd496-6c4a-4745-9feb-8dc297150b01)

It is the ver 40 one!

I might have missed the new feature as the installation document (pointed to  by @tomhajjar) doesn't mention it and for the portable instructs to download and install the spice flavour.

[^1]: Similar technology is being employed by Kicad which ships with a DLL.
