### ISSUE TITLE
Statusbar improvements

### ISSUE THREAD

**Issue by zergud** [ra3xdh/qucs_s#492]
1. show diagram value under mouse poiner
2. remove simulator information from statusbar - duplicate simulator combobox value for now

**Comment by ra3xdh** [comment]
> show diagram value under mouse poiner

Yes, this will implement some sort of cursor measurement. Probably it's need to consider to make it better visible for users. 

> remove simulator information from statusbar - duplicate simulator combobox value for now

Yes, the information on the status bar became redundant after introduction of the simulator combo box.

**Comment by zergud** [comment]
look for PR #493 

![image](https://github.com/ra3xdh/qucs_s/assets/869819/ec8337bf-14be-4551-b1e9-18394eceadad)

one thing left: take aware for engineering/scientific for Axis

**Comment by tomhajjar** [comment]
Will the 0,0 "Datum" AND location of the mouse cursor as indicated in the status bar ever be accurate?

The Datum and object locations as indicated by the mouse cursor in the status bar varies by Zoom and other metrics.

![2024-01-24_090654](https://github.com/ra3xdh/qucs_s/assets/102838604/3d044875-86e2-4c6f-bb7b-e38a161ded18)

[Qucs_Datum.zip](https://github.com/ra3xdh/qucs_s/files/14039463/Qucs_Datum.zip)

**Comment by zergud** [comment]
@tomhajjar yes, cursor position in status shows wrong value
but, this is not relevant to this issue
I suggest opening a new issue for this
p.s. is it really userful to get information about cursor position?

**Comment by iwbnwif** [comment]
> p.s. is it really useful to get information about cursor position?
Not really. It could be shown for debug builds only, but it is also simple enough to use qDebug.

**Comment by tomhajjar** [comment]
When making symbols it can be useful. Also some schematics I've downloaded are placed very far from the Datum it's difficult to find the "0,0" Datum cross (+). Maybe if the + was slightly larger it wouldn't be so hard to find.

**Comment by zergud** [comment]
@tomhajjar fixed!
