### ISSUE TITLE
ngspice VDMOS electro-thermal model using Qucs-S

### ISSUE THREAD

**Issue by tomhajjar** [ra3xdh/qucs_s#498]
@dwarning pointed out ngspice offers a VDMOS "thermal" model while LTspice doesn't. I'm trying to get it to work using Qucs-S but I'm having issues and unsure if it's just me or a limitation in Qucs-S. I haven't figured out how to get a netlist as shown in the following pics with the required space "IRFP240 thermal".

![2024-01-25_015049](https://github.com/ra3xdh/qucs_s/assets/102838604/185b6a0a-1fe9-4355-9215-90fcb5da7128)
![2024-01-25_013103](https://github.com/ra3xdh/qucs_s/assets/102838604/1dd2bad3-8ed3-419d-a738-5dd0d81f2cef)
![2024-01-25_013314](https://github.com/ra3xdh/qucs_s/assets/102838604/80af3132-700a-410f-949b-4889390ca303)
![2024-01-25_013350](https://github.com/ra3xdh/qucs_s/assets/102838604/3e4d1ad8-9d3e-487a-9f77-701a1c2963b2)

**Comment by tomhajjar** [comment]
I've made some limited progress but only by hand editing the netlist and using DuSpice/ngspice. 


![2024-01-25_212248](https://github.com/ra3xdh/qucs_s/assets/102838604/94d126d0-5ebc-43e8-b295-d946d38baf82)

![2024-01-25_211712](https://github.com/ra3xdh/qucs_s/assets/102838604/e9c32c4b-3be0-4f2d-995d-3706142cd417)

![2024-01-25_211541](https://github.com/ra3xdh/qucs_s/assets/102838604/6eb26ece-5150-48a7-b57d-28c14f1491c4)

[VDMOS_thermal_prj.zip](https://github.com/ra3xdh/qucs_s/files/14059673/VDMOS_thermal_prj.zip)

**Comment by dwarning** [comment]
"v(Tj)={Temp}" looks for me more as a misunderstanding. To set device temperature you should use instance parameter temp or dtemp.
Node Tj is more for sensing junction temperature.

**Comment by tomhajjar** [comment]
So the KiCAD example Dual-NMOS-amp.cir is "technically" wrong because it uses: .ic v(Tj1)={envtemp} v(Tj2)={envtemp}

While the KiCAD example mosamp2.cir and ngspice example 100W.sp are correct.

All the examples simulated.

My problem was two fold. I tried to assign Tj and did it wrong...

![2024-01-26_125854](https://github.com/ra3xdh/qucs_s/assets/102838604/8ebec409-e926-4a98-8deb-6c5893b9cd75)

[ngspice_thermal.zip](https://github.com/ra3xdh/qucs_s/files/14068047/ngspice_thermal.zip)

**Comment by tomhajjar** [comment]
Holger pointed out I was running the device too hot and had too high a thermal Z to the heatsink and this was causing my problems. I made changes to Vgs max Rc and the simulations look OK. Once a solution to adding VDMOS thermal is found we should be good. 

Still haven't figured out how to overlay my plots...

[VDMOS_thermal_prj.zip](https://github.com/ra3xdh/qucs_s/files/14073476/VDMOS_thermal_prj.zip)

**Comment by tomhajjar** [comment]
The above simulation used a built-in ngspice device, "VDMOS thermal".

For a GaN simulation where a thermal model exists, Holger created an a symbol, Holger_GaN_T.lib and the simulation called the subcircuit GaN_Pspice_GS66508T_L3V2.lib.  

https://ngspice.sourceforge.io/el-th-images/GaN-test.7z

I will try the same method in Qucs-S.

**Comment by ra3xdh** [comment]
You need to give the `thermal` parameter to the SPICE generic device inside the subcircuit. This device supports passing arbitrary parameter string. After applying these modifications everything works as expected. See the attached screenshots.
![image](https://github.com/ra3xdh/qucs_s/assets/4920080/98bc6c2c-8960-4180-98e7-509f7a200145)
![image](https://github.com/ra3xdh/qucs_s/assets/4920080/5d1c8dbf-f48d-4e57-bdbf-3054c4ef4534)

**Comment by tomhajjar** [comment]
I will confirm when I get new version. This could be of interest to @dwarning

**Comment by tomhajjar** [comment]
With the latest nightly release I was able to finish a number of projects based on the ngspice example 100W.sp. 

The ngspice example does AC, Tran, Four, FFT, thermal and noise analysis. 

The Qucs-S version separates the analysis into AC/Tran/Four/FFT and Tran/thermal.

![47df-b473-c6a91b7f5c5b](https://github.com/ra3xdh/qucs_s/assets/102838604/ebb7baf1-719c-436c-81d5-a33cd956e8e5)

![2024-02-08_155629](https://github.com/ra3xdh/qucs_s/assets/102838604/9ef9a0e3-07c7-4071-9e12-2d939ffa6384)

![2024-02-08_155608](https://github.com/ra3xdh/qucs_s/assets/102838604/27596c21-9c32-41ff-95ab-9b6602915de8)

[Amp_100W_ngspice_prj.zip](https://github.com/ra3xdh/qucs_s/files/14214788/Amp_100W_ngspice_prj.zip)
[Amp_100W_thermal_prj.zip](https://github.com/ra3xdh/qucs_s/files/14214776/Amp_100W_thermal_prj.zip)

**Comment by dwarning** [comment]
Thank you for the examples.
Unfortunately 100W_tran_thermal.sch didn't work. It comes with NaN for the thermal limiting function.
I have no problem with 100W.sp - but no success with the attached netlist.
 
[netlist.cir.txt](https://github.com/ra3xdh/qucs_s/files/14215282/netlist.cir.txt)

**Comment by tomhajjar** [comment]
You have to edit the netlist to find the libraries and generate plots. Also need to comment out all the commands that delete the plots. You can also comment out the statements that generate unneeded files. 

![2024-02-08_173516](https://github.com/ra3xdh/qucs_s/assets/102838604/adee45dc-083c-4753-a750-2e61250e90d0)

[100W_thermal_prj.zip](https://github.com/ra3xdh/qucs_s/files/14215371/100W_thermal_prj.zip)

**Comment by dwarning** [comment]
I must correct me: The problem is not compatibility mode, it is "set skywaterpdk" which was left over from other experiments.

**Comment by tomhajjar** [comment]
@dwarning 

If ngspice would work with more companies spice models, thermal analysis would be more common.,

https://sourceforge.net/p/ngspice/discussion/120973/thread/4721495ffa/
https://sourceforge.net/p/ngspice/discussion/120973/thread/b18b28cdab/
