### ISSUE TITLE
Add qucsator in the AppImage

### ISSUE THREAD

**Issue by alexpacini** [ra3xdh/qucs_s#50]
Do you think it would be possible to include also qucsator in the AppImage?
Compiling qucs core is quite convoluted and requires a bit of time, so I wonder if qucsator could be included to avoid the additional issue of having to build it.

**Comment by ra3xdh** [comment]
Sorry for the delayed answer. I don't consider the adding `qucsators` in AppImage. The combining of executables from two independent projects in one package is not a good idea. The same for Ngspice. Also after the Qt5 port #72 will be completed it will become possible again to build traditional packages (DEB/RPM) for the most of popular Linux distributions. The AppImage will be needed only for testing of new featutres and other non-standard application.
