### ISSUE TITLE
IGBT thermal project status reporting

### ISSUE THREAD

**Issue by tomhajjar** [ra3xdh/qucs_s#508]
Having issues getting an IGBT thermal project fully working. Quite often a transient simulation aborts early.

Should Qucs-S report Simulation successful when this happens? 

- [ ] Update error recognition patterns for Ngspice

![2024-01-29_154727](https://github.com/ra3xdh/qucs_s/assets/102838604/bb52947b-5ec2-46bd-8a10-6f5d15ae0a76)

[IGBT_thermal_prj.zip](https://github.com/ra3xdh/qucs_s/files/14089396/IGBT_thermal_prj.zip)

**Comment by ra3xdh** [comment]
> Should Qucs-S report Simulation successful when this happens?

I will update error status recognition patterns for Ngspice. This message is not recognized as error, because it has another format.

**Comment by ra3xdh** [comment]
Fixed via #511

**Comment by tomhajjar** [comment]
Going to be a lot of work getting most IGBT, MOSFET... thermal models to work in ngspice. 

Rohm has a vast array of devices and provides "Spice" and LTSpice versions of "Standard" and "Thermal" models. ngspice doesn't seem to like any of them...
