### ISSUE TITLE
Thermistor library

### ISSUE THREAD

**Issue by tomhajjar** [ra3xdh/qucs_s#532]
Did two thermistor models. Both have user parameters Resistance@25C and Beta.

1st varies resistance based on Temp. (Getting a nesting sub-circuit warning) 
2nd varies resistance based on a "virtual" voltage input. 0 volts = 0 deg C, 100 volts =100 deg C.

![2024-02-05_225628](https://github.com/ra3xdh/qucs_s/assets/102838604/2edbae52-4906-45bb-bad7-f61104ca4828)
![2024-02-05_225646](https://github.com/ra3xdh/qucs_s/assets/102838604/fb631d92-145e-495a-a36c-5a445354514b)

[Thermistor_prj.zip](https://github.com/ra3xdh/qucs_s/files/14174476/Thermistor_prj.zip)

**Comment by ra3xdh** [comment]
Thermistor library has been added by #538 I have added NTC device that allows to define temperature using parameter. This device will work for all simulators. 
![image](https://github.com/ra3xdh/qucs_s/assets/4920080/999df54f-f414-47d4-a94f-d9ce200f5b89)
