### ISSUE TITLE
Qucs-S crashes doing S-parameter file analysis

### ISSUE THREAD

**Issue by tomhajjar** [ra3xdh/qucs_s#544]
An old Qucs analysis causes Qucs-S to crash unless I disable the S-parameter analysis of file X1.

The analysis compares Spice to S-parameter data.

![2024-02-10_030527](https://github.com/ra3xdh/qucs_s/assets/102838604/4050b3c9-a630-49c8-bf2f-2285b6b54610)

[ATF34143_Amplifier_prj.zip](https://github.com/ra3xdh/qucs_s/files/14228592/ATF34143_Amplifier_prj.zip)

**Comment by ra3xdh** [comment]
The reason of the crash was noise data in the s2p file. I have added a fix for this #546 Now Qucs-S+Ngspice will ignore the noise data and give a warning, but the simulation will continue.

**Comment by tomhajjar** [comment]
I removed the noise data, deleted and replaced the  s2p and Qucs-S still crashes. 

[ATF34143_Amplifier_prj.zip](https://github.com/ra3xdh/qucs_s/files/14229864/ATF34143_Amplifier_prj.zip)

**Comment by ra3xdh** [comment]
Also remove blank lines form the s2p file. Everything is fixed by #546. The fix will be available in the next release.

**Comment by tomhajjar** [comment]
I'm doing something wrong...

![2024-02-10_114349](https://github.com/ra3xdh/qucs_s/assets/102838604/b7d8f193-362f-4fdd-b07f-33a05555a512)

![2024-02-10_114413](https://github.com/ra3xdh/qucs_s/assets/102838604/02f65ab0-3017-405c-8610-bb20ee83e8f2)

**Comment by ra3xdh** [comment]
Please wait for the next release. I will try to prepare a package within the next week.

**Comment by tomhajjar** [comment]
Qucs-S didn't like the CR at end of ATF341430_4v_40ma.s2p. Blank line....

ALSO you must select Polar/Rectangular FIRST then choose the file, ATF341430_4v_40ma.s2p. Since majority of s2p files I've seen are polar form, defaulting to polar might be better. 

Alternatively place polar/rectangular first in the menu and make it mandatory choice?

![2024-02-10_115457](https://github.com/ra3xdh/qucs_s/assets/102838604/65176c41-72d6-41db-b7d5-17a9987832fc)
