### ISSUE TITLE
Varistor library doesn't work....anymore??

### ISSUE THREAD

**Issue by tomhajjar** [ra3xdh/qucs_s#548]
I haven't used the Varistor library in a long time but when making a test folder of DC sweeping devices, the library didn't work. 

I know it worked in the past #92 (2022) but unsure of the details. I recovered the data from an old backup.

The Curve Tracer project might be useful for new users.

![2024-02-10_102544](https://github.com/ra3xdh/qucs_s/assets/102838604/79b0b3a5-6783-45ba-8057-cf202b823bcd)

![2024-02-10_110514](https://github.com/ra3xdh/qucs_s/assets/102838604/547fae58-06f6-4c36-914f-134bd7eab36c)

[2022 backup.zip](https://github.com/ra3xdh/qucs_s/files/14229836/2022.backup.zip)

[Curve Tracer Testing_prj.zip](https://github.com/ra3xdh/qucs_s/files/14229822/Curve.Tracer.Testing_prj.zip)

**Comment by ra3xdh** [comment]
This library doesn't work anymore when using Ngspice-39. If the Ngspice version <= 37 everything works as expected.

**Comment by ra3xdh** [comment]
The `qucs2spice::convert_rcl()` need to be modified. Ngspice requires to wrap variable value in braces to distinguish it from model. 

But the best solution will be to remake the Varistor.lib to provide true SPICE netlist. This task cannot be done in the near future, because the library contains about 100 devices.

**Comment by tomhajjar** [comment]
I will look into available models.

**Comment by ra3xdh** [comment]
I will try to provide a fix of `qucs2spice.cpp` in the next few days.

**Comment by tomhajjar** [comment]
The Epcos/TDK, varistor library is for "block" style varistors which have a much higher current rating than the generic leaded disk varistors used in most products. Not really an issue for varistor simulations where voltage is the primary parameter other than the parasitics being higher. Not sure why this type of varistor was used.

![s-l1600](https://github.com/ra3xdh/qucs_s/assets/102838604/a2287840-5f08-4f87-97a4-999a92805f6c)

[SIOV_Block_HighE.zip](https://github.com/ra3xdh/qucs_s/files/14235026/SIOV_Block_HighE.zip)
