### ISSUE TITLE
Qucs-S is blurry on macOS with retina screen

### ISSUE THREAD

**Issue by AlexPoulsen** [ra3xdh/qucs_s#55]
macOS Mojave 10.14.6
MacBook Pro 15" mid 2014
Qt 4.8.7_6
Qucs-S downloaded an hour ago and compiled

Hi I've just compiled Qucs-S, and it is blurry, but if I switch to another program (or the screenshot utility), it stops being blurry and is instead pixelated. Pixelated text and icons are something I can work with, but blurry text, buttons, window chrome, images, is hard on my eyes and is quite annoying, although ideally retina support would be best. In my cursory research, it appears Qt5 has better support for high dpi screens, but later versions of Qt4 backported some of that. I was unable to get anything to work to fix it, but I have yet to poke around in the code.

**Comment by ra3xdh** [comment]
Hello, the issue with HiPDI screens was already reported.  Qt4 doesn't support HiDPI resolutions. This issue cannot be resolved without porting to the Qt5 that is not expected in the near future.
