### ISSUE TITLE
GaasFET/MESFET use in ngspice

### ISSUE THREAD

**Issue by tomhajjar** [ra3xdh/qucs_s#551]
Although GaasFET/MESFET are rapidly losing favor, hobbyists are still using them. S-parameters are generally available but doing Spice analysis is a challenge not only due to lack of models but almost none work with ngspice. 

Attached is a project that uses Spice models modified to work with the ngspice supported Statz model. The user can use the modified models as templates to make ngspice compatible versions.

[MESFET_prj.zip](https://github.com/ra3xdh/qucs_s/files/14231186/MESFET_prj.zip)

**Comment by ra3xdh** [comment]
I have uploaded examples in #555 Thanks for the contribution!
