### ISSUE TITLE
Text file support

### ISSUE THREAD

**Issue by tomhajjar** [ra3xdh/qucs_s#556]
While not an issue or priority, can ASCII text support in Qucs-S be improved to render special characters and use a slashed 0?

The Consolas Font supports this but altering the settings in Qucs-S didn't render the special characters or use the slashed 0.

Using a separate text editor, I got burned editing a few Qucs-S libraries like "Xanalogue.lib" that contains special characters. The special characters were converted to "?" when the file was saved.

![2024-02-12_114243](https://github.com/ra3xdh/qucs_s/assets/102838604/b9a455cb-a2f7-4cb8-b8e8-8462ec4908be)
![2024-02-12_113920](https://github.com/ra3xdh/qucs_s/assets/102838604/8d4fde57-3efc-4811-84f7-17fe715ac899)

[Text Font Support.zip](https://github.com/ra3xdh/qucs_s/files/14241387/Text.Font.Support.zip)

**Comment by ra3xdh** [comment]
The #541 implements the requested feature. Please wait until the next version will be released.
