### ISSUE TITLE
.Func Name won't let you type in a comma ","

### ISSUE THREAD

**Issue by tomhajjar** [ra3xdh/qucs_s#559]
.Func Name won't let you type in a comma ",". You must use the existing comma.

![2024-02-12_155955](https://github.com/ra3xdh/qucs_s/assets/102838604/9437c1aa-06d1-4515-b7a1-b95ffca5333e)

**Comment by ra3xdh** [comment]
As discussed in #560 I would remove .FUNC device and keep only INLCUDE SCRIPT device.

**Comment by ra3xdh** [comment]
The problem with INCLUDE SCRIPT disabling and wrong Regexp in component dialog are fixed by #563
