### ISSUE TITLE
Qucs current source changed

### ISSUE THREAD

**Issue by tomhajjar** [ra3xdh/qucs_s#575]
I was converting from Qucs formulas to Nutmeg and the original Qucs current source doesn't work anymore for values of "1A" or "1 A". It has to be "1". It has to be a recent change.

![2024-02-17_080427](https://github.com/ra3xdh/qucs_s/assets/102838604/f1b50847-58ea-4ff8-aec7-48770f0ba6bb)
![2024-02-17_081425](https://github.com/ra3xdh/qucs_s/assets/102838604/5691ca25-095e-47e8-97eb-5e8008c5c6fc)

[Impedance Measurements_prj.zip](https://github.com/ra3xdh/qucs_s/files/14318859/Impedance.Measurements_prj.zip)

**Comment by ra3xdh** [comment]
I didn't change anything in the current sources. The `A` means atto and Ngspice is not case sensistive, but Qucsator is case sensistive.

**Comment by tomhajjar** [comment]
Two things changed. 

Polarity is flipped from 0.0.24 -> 24.1+ and "A" now means "Atto". 

I am next going to testing ngspice versions.

![2024-02-17_092916](https://github.com/ra3xdh/qucs_s/assets/102838604/ad09ac2f-08cd-410a-b0f3-10570686e74a)

**Comment by ra3xdh** [comment]
The polarity was fixed by #246 It is correct now.

**Comment by tomhajjar** [comment]
The change in "A" happened in ngspice 42

**Comment by ra3xdh** [comment]
I have just added a fix for amperes unit recognition https://github.com/ra3xdh/qucs_s/commit/92d9a39cb04ed9b18fbabf272e9375401f1af477 Closing as completed.
