### ISSUE TITLE
Specifying voltage source parameters using equation

### ISSUE THREAD

**Issue by Compizfox** [ra3xdh/qucs_s#58]
I have a circuit with a rectangle voltage source of which I would like to specify the period and duty cycle instead of the low and high duration (`TL` and `TH`). My idea was to use a equation, like this:

```
p = 0.004
d = 0.5
h = p*d
l = p*(1-d)
```

Then, set `TL=l` and `TH=h` in the voltage source.

This however does not work. The results are the same as when I leave `TL` and `TH` empty (that is, nonsensical). If I look in the generated netlist, it also appears the parameters are not inserted there:

```
V1 Vctrl 0 DC 0 PULSE( 0  5 0N 1U 1U 0 2e-06)  AC 0
```

Any ideas?

**Comment by ra3xdh** [comment]
Sorry for the delayed answer. The pulse source component is inherited fro Qucs, where it is defined using TL and TH parameters. The SPICE uses another syntax with T1,Tr, Tf parameters. Qucs-S recomputes these parameters in the netlist building time and cannot recompute equations. If you need a parametric definition try to use the SPICE voltage source (red color). It supports full SPICE definition string. But remember that the pulse source is defined is SPICE as a vector and may not support variables in vectors. It also doesn't support parameter sweep. See also #53
