### ISSUE TITLE
Create contributing guidelines

### ISSUE THREAD

**Issue by zergud** [ra3xdh/qucs_s#583]
To clearly understand the development rules, we need to create contributing.md file

**Comment by wawuwo** [comment]
@zergud do you have an outline for contributing guidelines? Recently I was thinking that it would be nice to install some conventions on code formatting, C++ standards, linting tools and rules… Maybe we should put them into `contributing.md` too.

**Comment by zergud** [comment]
I don't have that experience.
I think you need to take a goog example and adapt
any help is welcome

**Comment by ra3xdh** [comment]
The initial contribution guide provided by #585. Closing this as competed.
