### ISSUE TITLE
Failed to Calculate DC bias

### ISSUE THREAD

**Issue by paulmcquad** [ra3xdh/qucs_s#596]
In Qucs-S 2.1.0 you can run Simulate (F2) to Calculate DC bias:

![image](https://github.com/ra3xdh/qucs_s/assets/980002/6f324668-0776-4c3c-8066-c3f5a3648a78)

In Qucs-s 24.1:

You get the following error:

No simulation found. Please add at least one simulation!
Ngspice error...

Workaround:
Calculate DC bias (F8)

**Comment by ivandi69** [comment]
In 24.1 DC is valid simulation that does .OP and stores values in the dataset as any other simulation. There is no DC simulation in 2.1.0, bias calculation (.OP) is done in case no simulation is present in the schematic. In 24.1 if you want to only visualize bias values F8 is the right way to do it.
