### ISSUE TITLE
Warning message from Qucs-s after ngspice simulation

### ISSUE THREAD

**Issue by holvo** [ra3xdh/qucs_s#6]
After simulation (recent Qucs-s 020 on Windows 7) Qucs-s issues the following warning:

[Warning!] C:/Program Files (x86)/Qucs-S/share/qucs/xspice_cmlib/include/ngspice_mathfunc.inc file not found!

The file is there but the search path is wrong!

The correct path should be:

C:\Program Files (x86)\Qucs-S\share\qucs-s\xspice_cmlib\include

Holger

**Comment by ra3xdh** [comment]
Yes, I know about this bug. I have just fixed it this morning and replaced source tarball and binaries. Here is the commit containing fix: https://github.com/ra3xdh/qucs_s/commit/35a21c71b3d71372fd92b7289bb2a71b4e4de69f Please update your installation.
