### ISSUE TITLE
Lossless TLine netlist is wrong in some cases

### ISSUE THREAD

**Issue by tomhajjar** [ra3xdh/qucs_s#602]
The TLine netlist has unneeded entries confusing ngspice. You can't fix the problem setting a parameter value to "0" or " "

T1 1 2 3 4 Z0=50 Td=1ns -> good  - Unfortunately Qucs will add "F=0"/"F=" and "NL=0"/"NL="

T1 1 2 3 4 Z0=50 F=1e9 NL=0.25 -> good - Unfortunately Qucs will add "Td=0"/"Td=" nullifying F and NL

T1 1 2 3 4 Z0=50 F=1e9 -> good - Unfortunately Qucs will add Td and NL nullifying F and NL

T1 1 2 3 4 Z0=50 Td=1ns F=0 NL=0 -> bad - If Td used, F and NL should not be in netlist

T1 1 2 3 4 Z0=50 Td=0 F=1e9 NL=0.25 -> bad - Td=0 will nullify F=1e9 NL=0.25

T1 1 2 3 4 Z0=50 Td=1ns F= NL= -> bad

One solution would be a blank entry would delete the item from the netlist. 

![2024-02-20_192412](https://github.com/ra3xdh/qucs_s/assets/102838604/a448b2b2-b936-427b-a2fb-3d0fb9817717)

![2024-02-20_192432](https://github.com/ra3xdh/qucs_s/assets/102838604/7f352a69-7b0e-470d-bde2-6d89d1aa587f)

![2024-02-20_192449](https://github.com/ra3xdh/qucs_s/assets/102838604/fe79e634-29bd-4969-a672-89ee1979ed16)

[Transmission_Line_prj.zip](https://github.com/ra3xdh/qucs_s/files/14352029/Transmission_Line_prj.zip)

**Comment by dwarning** [comment]
The attached patch file will solve the problems in tline parameter handling.
All examples show reasonable results.

[Tline.patch.txt](https://github.com/ra3xdh/qucs_s/files/14363630/Tline.patch.txt)

**Comment by ra3xdh** [comment]
@dwarning Thanks for providing a patch. I have added your path as a part of #610

**Comment by dwarning** [comment]
@ra3xdh Thank you.
But as mentioned in #601 the patch is only a workaround. qucs-s gui has to work as user of ngspice who take care for the both specification modes of tline: 1. Specify Td (F and Nl omitted) 2. Specify F and Nl (Td is omitted and not(!) given in netlist)

**Comment by tomhajjar** [comment]
1. Specify Td (F and Nl omitted) 
2. Specify F and Nl (Td is omitted and not(!) given in netlist)
3. Specify ONLY F (Td AND NL is omitted and not(!) given in netlist) and ngspice -> NL=0.25

**Comment by tomhajjar** [comment]
I revisited my project above and ngspice TLine is now working with ver 24.2.0.
