### ISSUE TITLE
No data from ngspice simulator?

### ISSUE THREAD

**Issue by ardasevinc** [ra3xdh/qucs_s#61]
I created a very simple DC circuit and simulated it. But on the diagram window dataset is empty.
I don't understand what's wrong.

OS: Arch Linux
Qucs-s (0.0.22), qucs are installed from aur.
ngspice-33, installed from arch linux official repositoriess 

![empty dataset](https://i.imgur.com/cd5vy7C.png)

**Comment by ra3xdh** [comment]
DC simulation has no effect by itself if the Ngspice is selected as default kernel. Add AC or TRAN simulation and you will get the plots. Also try to press F8 or Simulation->Calculate DC bias and ypu will see the operation point of the circuit.

**Comment by ardasevinc** [comment]
> DC simulation has no effect by itself if the Ngspice is selected as default kernel. Add AC or TRAN simulation and you will get the plots. Also try to press F8 or Simulation->Calculate DC bias and you will see the operation point of the circuit.

Thanks, I also combed through the docs and realized DC sim is not implemented as you said. Sorry for this dumb issue :d
