### ISSUE TITLE
AudioIC tda2003 element does not work correctly

### ISSUE THREAD

**Issue by egrast** [ra3xdh/qucs_s#620]
![tda2003-lib](https://github.com/ra3xdh/qucs_s/assets/79281766/c731d980-e7d9-4d55-aa42-f85a219d8542)

**Comment by tomhajjar** [comment]
@ra3xdh

I found three versions Jim Thompsons TDA2003 Spice model. The version in Qucs-S has one change, "5" versus "5A" the version from Jim's website. The version Bordodynov supplies is either older or he modified it.

![2024-02-28_205833](https://github.com/ra3xdh/qucs_s/assets/102838604/3aaec079-4bdd-48d7-9b3e-4f02a6f0b8d2)

**Comment by egrast** [comment]
@tomhajjar

Thank you !   Works !

I tried to create a model based on "Analysis of TDA2003 and TDA2005 Integrated Amplifiers.pdf".
It is not intended for accurate AC analysis.

![tda2003-pdf](https://github.com/ra3xdh/qucs_s/assets/79281766/0563a805-80e8-4049-9cd1-9372783b8af0)

[tda2003-pdf.zip](https://github.com/ra3xdh/qucs_s/files/14449737/tda2003-pdf.zip)

**Comment by tomhajjar** [comment]
Nice work. Jim Thompson was an IC designer for Motorola and many others. He created a lot of Spice models as well. His archived website might not last too long.

https://web.archive.org/web/20180806223743fw_/http://www.analog-innovations.com

https://web.archive.org/web/20180806223743fw_/http://www.analog-innovations.com/subcircuits.html

**Comment by egrast** [comment]
@tomhajjar

Thank's

**Comment by tomhajjar** [comment]
Updated TDA2003. Added LM386, TDA2030 single ended and TDA2030 bipolar.

![2024-02-29_141257](https://github.com/ra3xdh/qucs_s/assets/102838604/1680696e-d6c7-4f87-9d73-d3df4a58b0db)

[AudioIC_prj.zip](https://github.com/ra3xdh/qucs_s/files/14452479/AudioIC_prj.zip)

**Comment by ra3xdh** [comment]
> What is the reason for 5 versus 5A

Ngspice treats this as 5 attoamper. It is near zero.

**Comment by ra3xdh** [comment]
@egrast The description of the TDA2003 device says that the LTspice compatibility setting is required for this model. The compatibility mode could be set using spiceinit: https://github.com/ra3xdh/qucs_s/pull/26 I failed to port this model to pure Ngspice and decided to leave it as is. Please always read the device description.

**Comment by egrast** [comment]
@ra3xdh 

Ok !
Thanks for the answer.

**Comment by ra3xdh** [comment]
@tomhajjar 

> Jim Thompson was an IC designer for Motorola and many others. He created a lot of Spice models 

Thanks for sharing the link. I have grabbed the models from archive to my HDD. It would be nice to wrap some of the models in the Qucs library.
