### ISSUE TITLE
Translation error ...

### ISSUE THREAD

**Issue by egrast** [ra3xdh/qucs_s#622]
In the marker properties change, the words "triangle" and "square" are swapped.
Everything is fine in the English version.

![Translate-err](https://github.com/ra3xdh/qucs_s/assets/79281766/d047febd-0a8c-425b-af11-a40b10622063)

**Comment by egrast** [comment]
The corrected qucs_ru.ts file eliminates the error:
[qucs_ru.zip](https://github.com/ra3xdh/qucs_s/files/14472230/qucs_ru.zip)

**Comment by ra3xdh** [comment]
I have replaced the translation file. Thanks!
