### ISSUE TITLE
AC Trans FFT revisited

### ISSUE THREAD

**Issue by tomhajjar** [ra3xdh/qucs_s#623]
Having issues producing an FFT with a log scale using a Nutmeg equation when doing AC/Trans/FFT. Using a Nutmeg equation isn't working unless I delete the AC analysis.

Using "Logarithmic left Axis Grid" ONLY works if I accidently find the "magic" combination of "settings". "OpAmp_ac_trans_fft.sch" has the magic combination and "LM3886_ac_tran_fft.sch" does not. 

I made "LM3886_ac_tran_fft_test.sch" with the same settings and plots of "OpAmp_ac_trans_fft.sch" but "Logarithmic left Axis Grid" still doesn't work. Other than the circuit, is set "ngbehavior=ltpsa" causing an issue?

![2024-03-01_102302](https://github.com/ra3xdh/qucs_s/assets/102838604/bd1ea381-7636-48b0-9c5e-bbfd26043a49)
![2024-03-01_102239](https://github.com/ra3xdh/qucs_s/assets/102838604/d5b2ae98-2e96-436f-905c-87ad3575bf93)
![2024-03-01_102327](https://github.com/ra3xdh/qucs_s/assets/102838604/107bd36c-7b55-4e00-b5d4-c800f660d88b)
![2024-03-01_103756](https://github.com/ra3xdh/qucs_s/assets/102838604/451fa151-9185-4b26-86ef-1dd72c5bbe8f)

[AC_Tran_FFT_prj.zip](https://github.com/ra3xdh/qucs_s/files/14463243/AC_Tran_FFT_prj.zip)

**Comment by ra3xdh** [comment]
> Using "Logarithmic left Axis Grid" ONLY works if I accidently find the "magic" combination of "settings"

It is not a bug. FFT data from Ngspice may contain negative noise values. This is not allowed for Log axis. I cannot fix this on Qucs-S side.

**Comment by ra3xdh** [comment]
> Using a Nutmeg equation isn't working unless I delete the AC analysis.

Everything should work now. @ivandi69 has recently fixed the AC/FFT.

**Comment by ra3xdh** [comment]
> Using a Nutmeg equation isn't working unless I delete the AC analysis.

You have a wrong syntax in Nutmeg block. Use short syntax `db(v(out))` and everything will work fine.
