### ISSUE TITLE
Regression Xyce parametric sweep

### ISSUE THREAD

**Issue by dwarning** [ra3xdh/qucs_s#624]
I am not able to plot results from Xyce parametric sweeps. This seems a regression because I see from older example file that it was possible in the past.
I made certain experiments with file format std and raw without success.
![Bildschirmfoto vom 2024-03-02 16-19-34](https://github.com/ra3xdh/qucs_s/assets/18441932/b311fa88-2fad-47a2-bee9-f7ad290ceee4)

[BSIM6_xyce_prj.zip](https://github.com/ra3xdh/qucs_s/files/14469866/BSIM6_xyce_prj.zip)

**Comment by tomhajjar** [comment]
Project works with Qucs 0.0.24. Doesn't work for 24.1.0...

![2024-03-02_190948](https://github.com/ra3xdh/qucs_s/assets/102838604/f1ad938b-5367-4b3c-b06a-2577c059197f)
![2024-03-02_191035](https://github.com/ra3xdh/qucs_s/assets/102838604/29d2ab81-f843-4cb5-b477-c50c7ce35b90)

**Comment by dwarning** [comment]
Latest functional version for Xyce parametric sweep simulation is 2.1.0. It's a pity that this interface has gone.

**Comment by ra3xdh** [comment]
Fixed by #627
