### ISSUE TITLE
TRIAC and other non linear components missing

### ISSUE THREAD

**Issue by ombra32** [ra3xdh/qucs_s#63]
Hi,
TRIAC and other non linear components (diac, thyristor, ecc..) are missing in Qucs-s when using Ngspice simulator.
Are presents using Qucsator simulator instead.

Have I missed something?
I'm using Qucs-s 0.0.22 appimage on Ubuntu 20.04.

![triac](https://user-images.githubusercontent.com/75046586/120077264-db871080-c0a9-11eb-9db3-d8498116a796.png)
![triac_no](https://user-images.githubusercontent.com/75046586/120077265-dd50d400-c0a9-11eb-9e48-aad8e2f97cdd.png)

**Comment by ra3xdh** [comment]
Triac and thyristor are SPICE-incompatible. These are unique qucsator devices. That's why these devices are missing when SPICE engine is selected. Probably you may find the SPICE model for the specific thyristor device and attach it using the "SPICE file" component.

**Comment by ombra32** [comment]
> Triac and thyristor are SPICE-incompatible. These are unique qucsator devices. That's why these devices are missing when SPICE engine is selected. Probably you may find the SPICE model for the specific thyristor device and attach it using the "SPICE file" component.

ok, I'll try..many thanks
