### ISSUE TITLE
Spice components oddities

### ISSUE THREAD

**Issue by ivandi69** [ra3xdh/qucs_s#637]
Spice capacitor bounding box is intermittent, sometimes it is correct sometimes like #590.
Same goes for spice diode.
Spice resistor offers 3 pins option but it doesn't work.
There is a R Resistor 3 pin component in Microelectronics tab, but the symbol is 2 pins.
M(NMOS 3 pin) is correct for the first placement, it changes to 4 pin for the next placement.

**Comment by ra3xdh** [comment]
Applying the same fix as #632 will help.

**Comment by ra3xdh** [comment]
See #641 for fix
