### ISSUE TITLE
Passing parameter warnings

### ISSUE THREAD

**Issue by tomhajjar** [ra3xdh/qucs_s#643]
I realize we talked about using SPICE netlist versus SpiceLibComp this multiple times, but is there any way to pass parameters to sub-circuits without generating warnings? Is this purely an ngspice limitation?

For example when doing Digital libraries it would be easier if "parameters" were attached to the models versus requiring a .PARAM statement on the schematic every time. A new user wouldn't know what to put in the .PARAM statement. Also you can't use different libraries on the same schematic if they share the same parameter names

![2024-03-15_113332](https://github.com/ra3xdh/qucs_s/assets/102838604/6beeb362-c6df-4b68-820b-d3b3c5e0d21e)
![2024-03-15_113409](https://github.com/ra3xdh/qucs_s/assets/102838604/b4a58725-c57f-4c98-a7ec-86866b6cf78b)
![2024-03-15_115204](https://github.com/ra3xdh/qucs_s/assets/102838604/9cf4dda4-e5b3-4e99-8f23-d35d2d6c11cd)

[Parameter_Passing_prj.zip](https://github.com/ra3xdh/qucs_s/files/14617707/Parameter_Passing_prj.zip)

**Comment by ra3xdh** [comment]
This feature will be implemented as the subtask of #679. Closing for now.
