### ISSUE TITLE
github says zip files not allowed???

### ISSUE THREAD

**Issue by tomhajjar** [ra3xdh/qucs_s#644]
Is there a reason github recently started warning zip files not allowed? They still upload OK.

![2024-03-16_162201](https://github.com/ra3xdh/qucs_s/assets/102838604/aac47c6b-e682-476a-935e-85a88d1fdf54)

**Comment by ra3xdh** [comment]
It is not repository issue. Probably Github developers decided to not allow ZIP archives by security reasons. Also Github may analyze the contents of the ZIP file and block if it is considered to be suspicious. Use file sharing services like dropbox if Github doesn't allow to attach file.
