### ISSUE TITLE
Cursor doesn't show Line/Column anymore in Text editing mode

### ISSUE THREAD

**Issue by tomhajjar** [ra3xdh/qucs_s#660]
Cursor doesn't show Line/Column anymore in Text editing mode. Indicator is "frozen" to last position in schematic.

Shown is Qucs-S versus Qucs

![2024-03-24_144445](https://github.com/ra3xdh/qucs_s/assets/102838604/73fdd0f2-c1fd-4925-ae77-4b9ba1dc1605)

![2024-03-24_144338](https://github.com/ra3xdh/qucs_s/assets/102838604/0b6669ca-73e8-4965-8f7f-d0a228b579e1)

**Comment by ra3xdh** [comment]
Fixed by #661
