### ISSUE TITLE
Current doesn't work in equations

### ISSUE THREAD

**Issue by lort-Z** [ra3xdh/qucs_s#666]
Windows QUCS-S 24.1
I can get I parameter from current probe, but cant use it in equations.
Voltage works fine.

Simulation console message:
Ngspice started...
Warning from checkvalid: vector pr1 is not available or has zero length.
Error: RHS "pr1" invalid
Warning from checkvalid: vector y is not available or has zero length.

Note: No compatibility mode selected!

Circuit: * qucs 24.1.0  c:/users/lort_z/.qucs/test_prj/test.sch

Doing analysis at TEMP = 27.000000 and TNOM = 27.000000

No. of Data Rows : 200
Reset re-loads circuit * qucs 24.1.0  c:/users/lort_z/.qucs/test_prj/test.sch

Circuit: * qucs 24.1.0  c:/users/lort_z/.qucs/test_prj/test.sch

ngspice-40 done
Simulation finished

![изображение](https://github.com/ra3xdh/qucs_s/assets/165066857/70e13c0f-3960-4e42-a123-a94c3dd800fb)
![изображение](https://github.com/ra3xdh/qucs_s/assets/165066857/f199da47-19b3-480f-ad44-68e0c04d4f36)

**Comment by ra3xdh** [comment]
Everything works as expected. The current probe is represented as the voltage source internally. Use the following syntax.
![image](https://github.com/ra3xdh/qucs_s/assets/4920080/04891b4c-8e33-475f-88fb-43b4daf24037)
