### ISSUE TITLE
Redesign File->Open examples menu

### ISSUE THREAD

**Issue by ra3xdh** [ra3xdh/qucs_s#672]
The *File->Open examples* menu opens file manager window pointing to directory containing examples. The current implementation has many disadvantages. File manager may look very similar to file open dialog on some platforms that may mislead user. Also it is impossible to open Qucs schematics from file manager because `sch` extension is often reserved for other applications. I propose to replace the file manager by open dialog when user click *File->Open examples.

**Comment by tomhajjar** [comment]
In Windows the *.sch extension isn't a problem using either File->Open examples or File->Open.

![2024-04-03_184537](https://github.com/ra3xdh/qucs_s/assets/102838604/dff4fee8-320c-437a-a0d6-3d11f48baaba)
![2024-04-03_184434](https://github.com/ra3xdh/qucs_s/assets/102838604/51ec2aa9-02bb-4253-b027-76f2cd4fa6f5)

**Comment by wawuwo** [comment]
@ra3xdh 
>by open dialog

You mean [QFileDialog](https://doc.qt.io/qt-6.5/qfiledialog.html)? (That's the one used by "Open file")

**Comment by ra3xdh** [comment]
@wawuwo , done

**Comment by ra3xdh** [comment]
Fixed by #674
