### ISSUE TITLE
qucsator not calculating output

### ISSUE THREAD

**Issue by goranmarinkovic** [ra3xdh/qucs_s#680]
I tried to simulate following design and do not get any output.
![image](https://github.com/ra3xdh/qucs_s/assets/86667287/f7f77739-1f61-450c-8187-0250f23e8d54)

The pulse generated is not visible on the out line and as well the cpld line is quiet... this does not look right.
The test files are attached for further investigation.
[breaking_example.zip](https://github.com/ra3xdh/qucs_s/files/14932712/breaking_example.zip)

**Comment by ra3xdh** [comment]
It is not a bug. Qucsator never had transient model for MS lines. The MS lines are considered as zero resistnace for all analysis except SP.

**Comment by ra3xdh** [comment]
The Qucsator from Qucs-0.0.20 gives the same result.

**Comment by goranmarinkovic** [comment]
Sorry I mixed QUCS-S and QucsStudio... there is see:
![image](https://github.com/ra3xdh/qucs_s/assets/86667287/9e0d951d-972a-4bcd-bb92-083d8bb7d37d)

**Comment by ra3xdh** [comment]
QucsStudio is closed source project not related to Qucs-S and may have incompatible extensions.

**Comment by goranmarinkovic** [comment]
It looks like a missing feature... since if it is possible in QucsStudio it should be available as well for Qucs-S.
It would be a pity if such an important feature is missing.

**Comment by ra3xdh** [comment]
Adding transient models for MS lines is technically possible if someone will provide equations.

**Comment by goranmarinkovic** [comment]
... here we need an RF expert. Anyone in the community able and willing to share?

**Comment by ra3xdh** [comment]
I have converted this issue to discussion. Probably someone could look at this and point a solution.
