### ISSUE TITLE
Windows build broken

### ISSUE THREAD

**Issue by zergud** [ra3xdh/qucs_s#686]
Windows build broken after https://github.com/ra3xdh/qucs_s/pull/658

![image](https://github.com/ra3xdh/qucs_s/assets/869819/d2719511-36d1-4e0e-821d-2ae84f5a7dc2)

**Comment by ra3xdh** [comment]
This has appeared after #658  Linux build is not affected. @wawuwo

**Comment by wawuwo** [comment]
Oh! :(
Working on it, will provide a fix soon
