### ISSUE TITLE
Snap or appimage Support

### ISSUE THREAD

**Issue by BearzRobotics** [ra3xdh/qucs_s#7]
I was wondering if you ever though about creating a snap or appimage of the project to make it easier to use on other distros.

**Comment by ra3xdh** [comment]
Yes, we are currently considering adding an AppImage. If you could help with adding AppImage in OBS, you are welcome. @eldarkg has created a SNAP package for Qucs-S once, you can request him to actualize it.

**Comment by ra3xdh** [comment]
I have just added AppImage for 0.0.22 release https://github.com/ra3xdh/qucs_s/releases/download/0.0.22/Qucs-S-0.0.22_x86_64.AppImage It was tested on OpenSUSE live DVD where Qt4 or Qucs were never installed. Simulation using system Ngspice works without problems. This AppImage doesn't include Ngspice!

**Comment by drtrigon** [comment]
The AppImage is brilliant, just "saved my live" as Ubuntu 20.04 seems to drop Qt4 support. Thanks a lot!
