### ISSUE TITLE
Windows Security Complaints

### ISSUE THREAD

**Issue by tomhajjar** [ra3xdh/qucs_s#743]
A long term issue has been Windows Security flagging the "first run" of Qucs-S as being from an "Unknown Publisher". Once I click "Run anyway" the warnings never come back unless I download another version of Qucs-S.

A newer issue is that when I copy the nightly release over existing files in the Qucs-S folder. It triggers multiple Security Scan warnings including trying to get me to do an "Online Scan". Windows "Antimalware" runs in the background hogging resources until it scans every file. 

![Clipboard01](https://github.com/ra3xdh/qucs_s/assets/102838604/62c86b6c-df68-4ce7-afa4-4f13857c89d9)

**Comment by ra3xdh** [comment]
> A long term issue has been Windows Security flagging the "first run" of Qucs-S as being from an "Unknown Publisher". 

The only way to fix this is to buy code signing certificate and sign the executable. I don't consider this option. 

> t triggers multiple Security Scan warnings including trying to get me to do an "Online Scan".

I have just tested a continuous release archive from the latest build and cannot confirm this. Everything works as expected except the "unknown publisher warning". I cannot say what triggers the security scan. Probably we have different UAC settings. I will also try to add stripping debug info step in the build script. Anti-virus software doesn't like debug binaries.

**Comment by tomhajjar** [comment]
These issues might confuse new users. Maybe a warning label at the download location.

My UAC settings are always the lowest. The signing certificate has always been an issue so no big deal. The other warnings are fairly recent. Probably since the nightly releases. Windows Security steals all the resources and it can take a while before all the new files overwrite the existing files in the Qucs-S folder. What's stupid is Windows opens the Edge Browser, goes to an online-scan description page and doesn't seem to do anything. All the while "Antimalware" starts running in the background.

**Comment by ra3xdh** [comment]
@tomhajjar Please check the archive at the following link: https://drive.google.com/file/d/1sUqvtKmHVVjeSqNP8h8GK-ijP8QvPQwX It is built manually and has executables with strupped debug info.

**Comment by ra3xdh** [comment]
Thanks for the feedback. I will use the explicit debug info strip when preparing a release package. I have also added this step to the automated CI script for continuous release preparation. See #782. Please test if the security issues are gone in the latest continuous release.

**Comment by tomhajjar** [comment]
MING??

![2024-06-23_120944](https://github.com/ra3xdh/qucs_s/assets/102838604/ba0f609b-aa30-4969-8638-166cf1b75f09)

**Comment by dsm** [comment]
ucrt64 is fine for win10 and win11 and better than mingw64 and snapshot builds doesn't give warning for me on win11 and I didn't merge two different version. defender gives false positive and snapshot build less download count compare to release build, I think issue related to this and you merge qt5 and qt6 build into one.

**Comment by tomhajjar** [comment]
I can overwrite files without issue.

Windows is still doing the first time opening warning for qucs-s.exe. Is this to be expected because of the lack of a security certificate?
![Clipboard01](https://github.com/ra3xdh/qucs_s/assets/102838604/2b0703c3-383e-4e16-a3f2-72e6a257abff)

**Comment by ra3xdh** [comment]
Yes, the warning on the first start cannot be resolved without purchasing a security certificate. I don't consider this option.
