### ISSUE TITLE
Sub-circuit Text Displayed 

### ISSUE THREAD

**Issue by tomhajjar** [ra3xdh/qucs_s#765]
Sub-circuit symbol text is not displaying properly when the sub is placed on a schematic. The text looks correct when creating the symbol but wrong when symbol placed in the schematic. Text is rotated 90 deg and is wrong font or size.

![2024-06-17_211224](https://github.com/ra3xdh/qucs_s/assets/102838604/f3ec4e85-8857-450f-88f2-9b9aefb5a1fb)

![2024-06-17_211257](https://github.com/ra3xdh/qucs_s/assets/102838604/81cecc78-6bb7-42c7-a7f0-678c157b7975)

[Photo_Voltaic_Isolators_prj.zip](https://github.com/user-attachments/files/15878987/Photo_Voltaic_Isolators_prj.zip)

**Comment by ra3xdh** [comment]
To make the issue more clear, it is about graphics text object inside subcircuit drawing. The `ID_text` object is not affected. This may be another  consequence of #723

**Comment by ra3xdh** [comment]
The library devices also seems to be affected. The issue was unnoticed, because the most of library devices don't use the rotated text inside symbol.

**Comment by wawuwo** [comment]
Hi guys, sorry for the silence; it has been a bit stressful in recent days. I've prepared a fix for the problem. Please let me know if it breaks something else while fixing the problem :)

**Comment by ra3xdh** [comment]
Fixed by #777

**Comment by tomhajjar** [comment]
Font size is smaller when placed in the schematic than the original sub-circuit.

![2024-06-21_075603](https://github.com/ra3xdh/qucs_s/assets/102838604/f1f23861-5389-4c0e-adb2-a71921a0291e)
![2024-06-21_075635](https://github.com/ra3xdh/qucs_s/assets/102838604/482e44ce-2036-44de-bef2-0288f7b61a8e)

**Comment by ra3xdh** [comment]
The font size requires an another fix. Please wait for the next patch. @wawuwo is aware about font size problems in some devices.
