### ISSUE TITLE
Fill blue devices parameters from SPICE model

### ISSUE THREAD

**Issue by ra3xdh** [ra3xdh/qucs_s#786]
This is follow-up for #679. It would be good to add a possibility to convert the SPICE model to unified nonlinear device parameters from the GUI. I propose to add a special button like *Fill from SPICE model* in the component dialog. The user can press this button and insert the SPICE modelcard `.MODEL` code. The device properties will be filled automatically. This button should be available for the following devices:  Diode, BJT, MOSFET, JFET

**Comment by tomhajjar** [comment]
How would you handle parameters not used by ngspice or extra info used by LTspice like "mfg=xxx". Would you just ignore these items?

Another issue is units used. Would you use 1e-9 or 1n as is? Leading 0? 0.01  versus .01

**Comment by ra3xdh** [comment]
> How would you handle parameters not used by ngspice or extra info used by LTspice like "mfg=xxx"? 

The only option is to ignore such model parameters. Qucsconv also ignores them. 

> Another issue is units used. Would you use 1e-9 or 1n as is? Leading 0? 0.01 versus .01

It is possible to apply the units conversion. Qucs-S parser accepts both notation. It should be possible to implement a checkbox like *Convert number notaiton* in the model import dialog.

**Comment by ra3xdh** [comment]
The proposed feature implemented by #795

**Comment by ra3xdh** [comment]
Here is a new look of the component properties dialog and new SPICE model import window. 
![image](https://github.com/ra3xdh/qucs_s/assets/4920080/1768d7da-49bc-4518-8982-7a809ad3b3c6)
![image](https://github.com/ra3xdh/qucs_s/assets/4920080/46183232-a569-492d-a239-260046ee759e)

**Comment by ra3xdh** [comment]
The feature implemented by #795. Closing this.

**Comment by tomhajjar** [comment]
If leading zero is missing does it add it?

**Comment by ra3xdh** [comment]
No, it currently cannot handle missing leading zero. I am not sure if Ngspice allow such notation. I may add a patch implementing this conversion.

**Comment by tomhajjar** [comment]
Another issue was some Spice models using the Greek µ instead of u. ngspice doesn't like µ

**Comment by ra3xdh** [comment]
> Another issue was some Spice models using the Greek µ instead of u. ngspice doesn't like µ

I cannot do anything with this. Ngspice doesn't support Unicode.

**Comment by tomhajjar** [comment]
I downloaded the latest and don't understand how to get this function to work. The Fill from SPICE Model is grey'd out. What is the procedure for loading the data or a file? 

Also shouldn't this be called Fill "Red" devices...

![2024-07-05_195757](https://github.com/ra3xdh/qucs_s/assets/102838604/704a9e33-cd51-4dc1-b4d3-34596e4f9f79)
![2024-07-05_200601](https://github.com/ra3xdh/qucs_s/assets/102838604/2e635b61-aef1-4ebf-882f-956f0cdb7b02)

[2N5109.zip](https://github.com/user-attachments/files/16114419/2N5109.zip)
