### ISSUE TITLE
Qucs legacy equation: not editable

### ISSUE THREAD

**Issue by mtupinie** [ra3xdh/qucs_s#793]
![image](https://github.com/ra3xdh/qucs_s/assets/17676159/5ab875c5-97fa-4bc0-ac7b-a44cfc32f0d2)

Version: Qucs-s 24.2.0
Issue: 4 buttons Add, rempove, move up and move down are not operational
Consequence; not possible to add extra equation

**Comment by ra3xdh** [comment]
Sorry, I cannot reproduce this. Everything works as expected on my machine. 

[Screencast_20240702_141614.webm](https://github.com/ra3xdh/qucs_s/assets/4920080/a39a0c2d-1a9f-422d-8839-7c2eec346eb5)

**Comment by ra3xdh** [comment]
The Windows version works as expected too.

**Comment by mtupinie** [comment]
Hello, bad configuration from my side, works fine know, thanks
