### ISSUE TITLE
Dark theme and rendering issue on windows

### ISSUE THREAD

**Issue by dsm** [ra3xdh/qucs_s#818]
Hi, Qt added new theming for win11 named Windows11 style beginning Qt 6.7. This theme can automatically switch dark and light mode. In dark mode editing component color of the value is white. And some rendering artifact. I add some pictures. @wawuwo

Problem 1:

![image](https://github.com/ra3xdh/qucs_s/assets/41967334/abcef82a-f2ae-4dba-a19d-2e14fc0052a3)

Problem 2:

![image](https://github.com/ra3xdh/qucs_s/assets/41967334/9a08c6e2-1851-4ba3-9e92-85063ab9018f)

Problem 3:

![image](https://github.com/ra3xdh/qucs_s/assets/41967334/da1e7e7f-fa5b-4fc4-bbd3-30d46f005f07)

edit from @ra3xdh : Added **TODO** list

- [x] When property value is being edited, value text is misplaced
- [x] When property value is being edited and QT theme is switched to dark mode, value text has white color and is barely visible
- [x] When property value is being edited, value text is visible only partially
- [x] Connections to component ports are rendered incorrectly; if port has only one connection is has to be rendered as a little filled square

**Comment by ra3xdh** [comment]
I have also recently noticed that the dots on device pins are disappeared after schematic rendering refactoring. 
* Old 
![image](https://github.com/ra3xdh/qucs_s/assets/4920080/f3f336b4-6cc3-48cd-9ca6-2b1d0b6222bb)
* New -- no dots
![image](https://github.com/ra3xdh/qucs_s/assets/4920080/bff09661-a3c1-4a9c-a903-6ece668bf648)

**Comment by wawuwo** [comment]
Hi guys!

Here is a checklist of problems to check that I've understood them well and to control the progress. Please correct me if I'm wrong:

- [ ] When property value is being edited, value text is misplaced
- [ ] When property value is being edited and QT theme is switched to dark mode, value text has white color and is barely visible
- [ ] When property value is being edited, value text may is visible only partially
- [ ] Connections to component ports are rendered incorrectly; if port has only one connection is has to be rendered as a little filled square

**Comment by dsm** [comment]
The application is already in dark theme, but when the value is changed, there is a white background and white text in windows11, but in macOS, this does not happen in the dark theme, it is white text on a black background. In problem 2, there is also a residue of the value that normally appears on the white background, which should not be there.

**Comment by ra3xdh** [comment]
The #820 resolves the problem with nodes rendering. I have added TODO list for this issue.

**Comment by wawuwo** [comment]
@dsm I made a patch which uses different approach to control colours when property values is being edited, but unfortunately I don't have a windows-based machine to try it out. Could you please try the patch to check if it fixes the problem №2?

**Comment by dsm** [comment]
Yes this patch is fixed Problem 2.

**Comment by ra3xdh** [comment]
The full fix provided by #842 Closing as completed.
