### ISSUE TITLE
Improve converter tool GUI

### ISSUE THREAD

**Issue by ra3xdh** [ra3xdh/qucs_s#826]
I propose the following improvements for converter  tool GUI (accessible from *Tools->Data files converter*)

- [x] Add possibility to define the library name: https://github.com/ra3xdh/qucsator_rf/issues/11
- [x]  Add possibility to select data variable from drop-down list instead type-in manually

**Comment by tomhajjar** [comment]
Presently to create/repair/update a library with the same name as an existing one, the existing one has to be deleted/renamed.

Will Qucs-S now allow overwriting libraries in usr_lib? 

Will Qucs-S now allow creating libraries in usr_lib that have the same name as a library in C:\QUCS-S 24.2.0\share\qucs-s\library?

Th reason I ask is the library filename is also embedded throughout the file. Renaming the library doesn't work. You have to replace every filename instance throughout the library.

**Comment by ra3xdh** [comment]
The proposed improvements implemented by #841
