### ISSUE TITLE
Switch DEB/RPM packages to Qt6

### ISSUE THREAD

**Issue by ra3xdh** [ra3xdh/qucs_s#857]
The Qt6 build is stable enough and has some HiDPI support features not available for Qt5 version. It makes sense to switch the DEB/RPM packages to Qt6 by default. The Ubuntu-20.04 is EOL next year and its support may be dropped.

**Comment by ra3xdh** [comment]
I have switched the Debian/Fedora packages to Qt6, but the OpenSuse build fails with the following message:

~~~
[   32s] -- Could NOT find Qt6LinguistTools (missing: Qt6LinguistTools_DIR)
[   32s] -- Check if linker can resolve circular dependencies - FALSE
[   32s] CMake Error at CMakeLists.txt:42 (find_package):
~~~

Here are the dependencies from SPEC:
~~~
BuildRequires:  gcc-c++
%if 0%{?suse_version}
BuildRequires:  qt6-base-devel
BuildRequires:  qt6-tools-devel
BuildRequires:  qt6-tools-linguist
BuildRequires:  qt6-svg-devel
BuildRequires:  qt6-tools
BuildRequires:  flex
BuildRequires:  bison
BuildRequires:  gperf
BuildRequires:  dos2unix
BuildRequires: cmake
Requires: qt6-base
Requires: qt6-svg
Requires: qt6-tools
Requires: ngspice
%else
BuildRequires:	qt6-qtbase-devel, cmake, qt6-qtsvg-devel, qt6-qttools-devel, flex, bison, gperf, dos2unix
Requires: qt6-qtbase, qt6-qttools, qt6-qtsvg, ngspice
%endif
~~~


The `qt6-tools-linguist` is listed in the dependecies. I don' understand what the Cmake wants. 

I would ask OpenSUSE users to suggest what dependencies are missing.

**Comment by ra3xdh** [comment]
I have found the missing package: `qt6-linguist-devel` But the OpenSUSE build still failing. The build VM installs GCC v7.5.0 by unknown reason. The Leap15.5 should contain GCC-13.

**Comment by ra3xdh** [comment]
I have just tried this. This didn't work. The package manger still install three GCC versions and CMake picks the oldest GCC. It's need to find a way to specify a GCC version without distribution version check for every OpenSUSE distribution.

**Comment by ra3xdh** [comment]
Yes, this will work but will require to handle explicitly three OpenSUSE versions in SPEC. Every version has different newest GCC version. I will use this method, if no other way will be found. There should exists an automatic method for OpenSUSE.

**Comment by dsm** [comment]
I never work on opensuse but I will try in VM maybe I find a way

**Comment by ra3xdh** [comment]
Here is the RPM spec: https://build.opensuse.org/projects/home:ra3xdh/packages/Qucs-S/files/qucs-s.spec

**Comment by ra3xdh** [comment]
I have resolved the problem with openSUSE build. It should use `%cmake_qt6` macro instead of `%cmake`

**Comment by ra3xdh** [comment]
Closing this as completed. All DEB/RPMs are switched to Qt6 now.

**Comment by dsm** [comment]
Will you continue to use OBS for deb/rpm or other linux package release ? In github ci we can use docker for other os and there are some ci action to build arm64 linux build basically it's based on qemu.
