### ISSUE TITLE
Windows application after install doesn't start - libbz2-1.dll error

### ISSUE THREAD

**Issue by I-AM-ENGINEER** [ra3xdh/qucs_s#862]
Windows 10 IoT Enterprise LTSC 21H2 19044.4529
Program version: qucs-s-24.3.0-setup.exe
![image](https://github.com/user-attachments/assets/7dc31672-c0ea-468d-b4ee-a19f31799473)

Fix: just add libbz2-1.dll in folder with app

**Comment by ra3xdh** [comment]
I have reuploaded the Windows installer today and added a missing library. Please check the new installer.

**Comment by ra3xdh** [comment]
Installer file has been replaced. Closing this.
