### ISSUE TITLE
Component windows items looks blury version 24.3

### ISSUE THREAD

**Issue by dsm** [ra3xdh/qucs_s#863]
Hi in new release 24.3 items looks blury but nothing blury in schematics , you can look difference in above image res is full hd, on HiDPI no issue.

![image](https://github.com/user-attachments/assets/bd77d6d7-3c16-4be4-a85b-59131e007a68)

**Comment by wawuwo** [comment]
@dsm could you please build with [this](https://github.com/ra3xdh/qucs_s/blob/dedcd59bf4b5e60801484d24703b747149d76230/qucs/components/component.cpp#L326) line commented out and check if it makes any difference in icons appearance?

**Comment by dsm** [comment]
Hi, I'm disabling 326 and 327 both or not nothing changed so I changed renderhints nothing changed and give worst results.

**Comment by wawuwo** [comment]
Well, I ran out of ideas for now 🤔

**Comment by ra3xdh** [comment]
I noticed some blur, but I thought it was Wayland issue. 

> Well, I ran out of ideas for now

If it is not clear how fix, the things may be kept as is.

**Comment by wawuwo** [comment]
There are some devices/elements which use SVG-images as their icons. Do they look blurry too? For example, simulations or paintings

**Comment by dsm** [comment]
there is no diff between simulation icons looks same.

**Comment by ra3xdh** [comment]
I believe the things could be kept as is and this issue may be closed.
