### ISSUE TITLE
installation dependencies

### ISSUE THREAD

**Issue by oe2lsp** [ra3xdh/qucs_s#866]
some dependencies in the install documentation are old, mostly towards qt6.

- in the build instructions there is still a reference to qt5
- when installing using the link to "https://software.opensuse.org/download.html?project=home%3Ara3xdh&package=qucs-s" on ubuntu 22.04 i end up with some unmet dependencies. this results in qucs-s not starting.

`Warning: Could not find the Qt platform plugin "xcb" in "" (:0, )
Fatal: This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.    
 (:0, )    
Aborted (core dumped) 
`
 
Reinstalling didn't help. 
I have solved the issue by hitting it with the hammer and installed all of them "ngspice build-essential git cmake qt6-base-dev qt6-tools-dev-tools libqt6svg6 flex bison gperf dos2unix" now it is working again. 
Sorry for the bad and unspecific report.

**Comment by ra3xdh** [comment]
I have added the `qt6-qpa-plugins` as the dependency in the repository. The `apt` doesn't install it by default. The dependencies in Debian distribution is madness. Please install this package to fix the installation or update from repository.
