### ISSUE TITLE
add ASCO to MacOS release.

### ISSUE THREAD

**Issue by dsm** [ra3xdh/qucs_s#870]
Hi, adding ASCO to MacOS release will be good, linux and windows has asco.

Can we build vanilla or asco_qucs_s package for macos ?

**Comment by ra3xdh** [comment]
ASCO seems to be already packaged for MacOS: https://ports.macports.org/port/asco/ Inclusion it in the Qucs-S package may lead to package conflict.

**Comment by ra3xdh** [comment]
The installation of the vanilla ASCO version from the MacPorts seems to be preferable. Closing this.
