### ISSUE TITLE
Add spectrum analysis simulation for Nsgpice

### ISSUE THREAD

**Issue by ra3xdh** [ra3xdh/qucs_s#88]
Currently the FFT analysis is possible using the Nutmeg scripting https://qucs-s-help.readthedocs.io/en/latest/ASim.html#spectrum-analysis-with-ngspice-and-nutmeg-scripting It would be more user-friendly way if we add a special simulation type that generates this Nutmeg script automatically. 

- [x] Add FFT analysis component
- [x] Add simulation examples

**Comment by ra3xdh** [comment]
The attached screenshot illustrates the concept of the new FFT simulation. This simulation type is available on the `current` branch.
![image](https://user-images.githubusercontent.com/4920080/168095618-779f93d7-ba60-402f-96a8-8ba9ce494735.png)

**Comment by tomhajjar** [comment]
I have never gotten the example in Figure 5.8 to work using the following Nutmeg script. No data is generated. 

tran 1n 10u 0
linearize v(out)
fft V(out)
let S = db(v(out))

This new method will save time as well. 
![mixer](https://user-images.githubusercontent.com/102838604/182972575-17d4ee16-0685-4c69-9d08-4be7473e81c6.png)

**Comment by ra3xdh** [comment]
Hello Tom, the schematic from the manual works on my machine as expected. Probably you have something wrong with the Nutmeg script setting. Please check the following attached schematic: 
[Mixer.zip](https://github.com/ra3xdh/qucs_s/files/9267342/Mixer.zip)

**Comment by tomhajjar** [comment]
When I copy your Nutmeg script and tran statement into my schematic, it still didn't work. The only difference I found was my schematic name has spaces in it. Changing name to remove spaces fixed it. Not sure why this happens. I have many schematics with names using spaces. 

Changed:
Double Balanced Diode Mixer 7-15MHz.sch

To:
DBM_Mixer.sch

Your schematic has two different tran statements. I assume using Nutmeg script this is allowed?

**Comment by ra3xdh** [comment]
Yes, I can reproduce this bug now. The space in the schematic name breaks the custom simulation and produce the string like this in the netlist:
~~~
write Mixer 1_custom.txt V(out) S
~~~
The `write` command become invalid. I will fix this bug in the next release. As workaround you may save your schematic using scripting simulation without the space in the file name. Other simulation types are not affected.

**Comment by ra3xdh** [comment]
I have created a separate issue #129 instead of writing to the closed issue.
