### ISSUE TITLE
DC Block, DC Feed

### ISSUE THREAD

**Issue by tomhajjar** [ra3xdh/qucs_s#889]
Any reason DC Block, DC Feed are not enabled for ngspice? I have a number of old Qucs projects that use them.

**Comment by ra3xdh** [comment]
These devices cannot be exactly simulated with SPICE. The DC feed is represented as ideal short circuit for AC, but as inductance for TRAN. The similar is for DC feed. Ngspice cannot determine what simulation is applied and substitute the required model. I can only represent these devices as the static L or C.

**Comment by ra3xdh** [comment]
Fixed by #891
