### ISSUE TITLE
Strange issues as well as "Ghost" data points when plotting

### ISSUE THREAD

**Issue by tomhajjar** [ra3xdh/qucs_s#892]
The past week I noticed a number of old projects didn't work the same anymore and there are "ghost" data points being plotted in areas they shouldn't be in. Files updated 8/19/24

Update:

I retraced my steps and redid a number of sub-circuits in the project (cosmetic changes) and cannot get the "bad data" issue to reoccur.  "Ghost" data points are still present as shown in attached screen shots

The goal of the project is to make more RF "TLine" components that work under ngspice. So far TLines, Lossless Directional Coupler and a 90 deg Hybrid coupler working.

![2024-08-16_190822](https://github.com/user-attachments/assets/bb40468d-eb80-4743-9f44-2942e70819c6)
![2024-08-16_190803](https://github.com/user-attachments/assets/d90d66f9-3d36-4dae-b361-02de9d4073b0)

[Transmission_Line_prj.zip](https://github.com/user-attachments/files/16662627/Transmission_Line_prj.zip)

**Comment by ra3xdh** [comment]
I confirm this problem. The virtual point at (0,0) is always rendered. All *point-type* plots are affected. I will provide a fix soon. The most probably I will prepare v24.3.1 release in September containing this fix, because the reported bug is critical.

**Comment by ra3xdh** [comment]
Fixed by #897
