### ISSUE TITLE
ngspice compatible Library of Transmission Line components

### ISSUE THREAD

**Issue by ra3xdh** [ra3xdh/qucs_s#896]
### Discussed in https://github.com/ra3xdh/qucs_s/discussions/895

<div type='discussions-op-text'>

<sup>Originally posted by **tomhajjar** August 19, 2024</sup>
I've been working on some Transmission Line components that will work with ngspice. Most of the components use the Spice TLIne. I also found a lossless directional coupler that I made into a subcircuit, 

Attached is the project and the Library

![2024-08-19_115707](https://github.com/user-attachments/assets/1c7b7070-dbde-4097-ae03-64607cb96acc)
![2024-08-19_115634](https://github.com/user-attachments/assets/73e6046f-eb79-4bf4-a1df-76227e1aabe4)
![2024-08-19_115617](https://github.com/user-attachments/assets/7a9efe77-4826-4887-9b66-019e303dd50a)

[Transmission_Line_Lib_prj.zip](https://github.com/user-attachments/files/16662657/Transmission_Line_Lib_prj.zip)
[Transmission_Line_prj.zip](https://github.com/user-attachments/files/16662655/Transmission_Line_prj.zip)</div>

**Comment by ra3xdh** [comment]
The library uploaded by #1019

**Comment by tomhajjar** [comment]
@ra3xdh 

I updated Transmission_Line.lib on 10/25/24

Added 180 deg Hybrid Coupler and added better descriptions of the devices.

![2024-10-25_153046](https://github.com/user-attachments/assets/863c9753-0500-4b2c-bb3c-e65353a5bd5a)

[Transmission_Line_prj.zip](https://github.com/user-attachments/files/17526801/Transmission_Line_prj.zip)
