### ISSUE TITLE
Github CI improvements for MacOS .

### ISSUE THREAD

**Issue by dsm** [ra3xdh/qucs_s#898]
Hi, @ra3xdh 

I'll update github CI for to support older macos release.

I forget to add CMAKE_OSX_DEPLOYMENT_TARGET flag to set minimum target version so our release probably only run macos-14-arm64 and macos-12-intel. 

Mac release uses latest Qt 6.7.2 and this version support Mac OS 11 as minimum but Qt 6.2 LTS support MacOS 10.14 as minimum but Qt 5.15 LTS support 10.13 so we decided we will support 10.13 or 10.14 minimum.

And also I add universal binary both x86_64 and arm64 version as single app. Maybe we can remove intel and arm CI just use universal one if everthings works as expected.

**Comment by dsm** [comment]
I want to build universal one using latest Qt6 but legacy one Qt 5.15 or Qt 6.2 LTS.

**Comment by ra3xdh** [comment]
I would restrict the minimum supported Qt version to 6.2.4. This version is used also by Ubunut-22.04. The Ubuntu-20.04, which has no Qt6 package, will be EOL next year.

**Comment by dsm** [comment]
Hi, then I would prepare two version one is universal and support Mac OS 11 to latest, other one is intel and support 10.14 minimum and build against Qt 6.2.4.

**Comment by ra3xdh** [comment]
Yes, submit the PR when ready.
