### ISSUE TITLE
Qucs_S Windows crashes when renaming missing sub-circuits

### ISSUE THREAD

**Issue by tomhajjar** [ra3xdh/qucs_s#902]
I renamed some sub-circuits and when I try to update the original schematic with the new sub-circuit names, Qucs-S Windows crashes.

Deleting the "old" sub-circuit and replacing with the "new" is not desirable since all the original sub-circuit parameters are lost.

The schematic works if I hand edit it with a Text Editor

I don't remember entering a new name for a sub-circuit being an issue before.

![2024-08-23_141009](https://github.com/user-attachments/assets/37fe10bd-7812-4304-bb8f-89345fd20052)
![2024-08-23_141030](https://github.com/user-attachments/assets/dedc54bc-eafc-4bbe-8536-6041656d3678)
![2024-08-23_141046](https://github.com/user-attachments/assets/0b7d0779-a85f-43de-88b9-50fa3924c974)
![2024-08-23_142752](https://github.com/user-attachments/assets/61c49465-6c9b-4bf9-bd07-2b88d9b52e89)

[BFP193W_amplifier_prj.zip](https://github.com/user-attachments/files/16732412/BFP193W_amplifier_prj.zip)

**Comment by ra3xdh** [comment]
I confirm this bug. I will provide a fix soon.

**Comment by tomhajjar** [comment]
Any idea why the gain of your original circuit is soo low? It should >20dB not <7dB.

![2024-08-24_120411](https://github.com/user-attachments/assets/9cdb5913-27c7-4698-a864-50ae1e1b2637)

**Comment by ra3xdh** [comment]
> Any idea why the gain of your original circuit is soo low? It should >20dB not <7dB.

I cannot remember where I took this schematic. Maybe the microstrips has a wrong design.

**Comment by ra3xdh** [comment]
Fixed by #918
