### ISSUE TITLE
Qucs-S displaying ngspice progress

### ISSUE THREAD

**Issue by tomhajjar** [ra3xdh/qucs_s#904]
We discussed Qucs-S displaying ngspice progress like DuSpice does. Presently "Reference value" is presented by ngspice for transient analysis. DuSpice displays this as 0-100%. Would this be more useful for users for very long analysis?

T=0 -> 0%
T=Max -> 100%

![2024-08-23_153309](https://github.com/user-attachments/assets/e71d2b5a-f081-40ba-ab0d-521baea63280)
![2024-08-22_110814](https://github.com/user-attachments/assets/acc9c13f-7906-4c7b-b17b-fd3ff15b4db4)

**Comment by ra3xdh** [comment]
The Simulation dialog will be switched to the dock console in the long perspective #235. I will consider adding progress bar as the part of #235. I have no intention to add/remove something in the existing dialog.
