### ISSUE TITLE
Simulation fails after adding a matching network 

### ISSUE THREAD

**Issue by tomhajjar** [ra3xdh/qucs_s#908]
After adding a matching network a BFP193W amplifier simulation fails. The device gets no collector voltage from the Bias-T and I cannot see what is causing the issue. Error warnings point at the junction of R1/BFP193W.

The BFP193W amplifier without the matching network simulates OK.

Bias-T is 1F and 1H...

![2024-08-24_102146](https://github.com/user-attachments/assets/a17bd40c-e10a-4a55-81b2-35ace4d6b207)
![2024-08-24_101931](https://github.com/user-attachments/assets/d405c1a1-0837-4c1d-8d52-bcda7f99687a)
![2024-08-24_101743](https://github.com/user-attachments/assets/abf454e8-b400-464c-9f11-eb902fe97c8b)

[BFP193W_amplifier_prj.zip](https://github.com/user-attachments/files/16736937/BFP193W_amplifier_prj.zip)

**Comment by ra3xdh** [comment]
It is not Qucs-S bug. The R1 resistor has no DC path to ground and Ngspice DC OP simulation fails. The schematic works as expected after adding 1Meg resistor between R1 and ground. Unfortunately Ngspice error message doesn't help to debug the schematic. 
![image](https://github.com/user-attachments/assets/f18ccfee-708d-4d3c-b975-23999b000d9f)

**Comment by tomhajjar** [comment]
Vc being wrong threw me off...
