### ISSUE TITLE
Qucsconv_rf issues

### ISSUE THREAD

**Issue by tomhajjar** [ra3xdh/qucs_s#910]
It's been a long time since you made the new version of Qucsconv #647. 

I thought I tested exporting s-parameters but I cannot get the Touchstone file to have all 4 parameters, S11, S21, S12, S22. I can only choose 1. 

Am I missing something?  I made a simple test file "BFP193W_stable_spar.sch" which only generates s-parameters.

Qucsconv_rf will also export all data including formulas but again only 1 item at a time. "BFP193W_spar_stable_analysis.sch' shows this.

Qucsconv_rf supports multiple output file formats but one must add the suffix since the files generated won't have one.

For reference is a screenshot of Qucsconv in Qucs 0.0.20. By default it only outputs the s-parameters not the other data like Group Delay. Unsure what the "Output Data" line is used for. Qucsconv automatically appends .dat to every file which is wrong. One has to edit it.

**TODO**

- [x] Disable data variable selection list if exporting from DAT to SnP

![2024-08-24_154207](https://github.com/user-attachments/assets/d5595113-5bdb-402f-b2d8-4b44ceac4223)
![2024-08-24_160107](https://github.com/user-attachments/assets/c5978220-d7f1-4f0b-9f3b-b038ecb38738)
![2024-08-24_162804](https://github.com/user-attachments/assets/b95ca637-e098-4d53-9cb1-592d6242d53f)

[BFP193W_amplifier_prj.zip](https://github.com/user-attachments/files/16743458/BFP193W_amplifier_prj.zip)

**Comment by ra3xdh** [comment]
Fixed by #916.
