### ISSUE TITLE
Qucs-S GUI improvements

### ISSUE THREAD

**Issue by ra3xdh** [ra3xdh/qucs_s#92]
I have recently received some feedback from Qucs-S users and the following GUI improvements were proposed:

- [x] Implement exact marker position setting on plots. Currently the marker position could be exactly set only with arrow button. It would be good to add some input field in the marker properties dialog to set an exact X-axis position;
- [x] Add dB output for the Y-axis to avoid using of the equations to get the dB output. 
- [x] Add possibility to define scale for X-axis (like 1k, 1M, 1G, etc.) See also https://sourceforge.net/p/qucs/mailman/message/35975391/
- [x] Set default path when open file to `$HOME`
- [x] User request: automatically align device by grid after rotation #399 
- [x] Correct MOSFET symbols appearance #93 (low priority)

**Comment by tomhajjar** [comment]
It would be nice to be able to set the format of the X scale. I've tried the trick below but it has issues. This was an old request for Qucs.

https://sourceforge.net/p/qucs/mailman/message/35975391/

**Comment by ra3xdh** [comment]
@tomhajjar Yes, I will consider a way how to add units like 1k, 1M, etc. for X-axis. The slight modification of the diagram properties will be required.

**Comment by ra3xdh** [comment]
I have just implemented the numeric marker position setting. The screenshot illustrates how it looks like. This feature is available on the ´current´ branch now. 
![image](https://user-images.githubusercontent.com/4920080/173306224-3fc2794c-6983-451e-9fe8-f67e834f8d89.png)

**Comment by ra3xdh** [comment]
I have added a switch to enable engineering notation (1k, 1M, 1G etc.) for numbers on diagrams. Attached screenshot illustrates how it looks now. This feature is available on `current` branch.
![image](https://user-images.githubusercontent.com/4920080/177045350-884b96af-88fb-40a9-ae32-19fc9dde6f7f.png)
![image](https://user-images.githubusercontent.com/4920080/177045380-de7bc105-3481-4a7d-a299-c7acece93558.png)

**Comment by ra3xdh** [comment]
I have just added a possibility to set dB units for Y-axis if logarithmic scale is selected. The new feature is available on `current` branch.
![image](https://user-images.githubusercontent.com/4920080/178518827-fd4a32ac-6b07-4233-a880-c0a33c7abce9.png)
![image](https://user-images.githubusercontent.com/4920080/178519083-85ebc167-b7b2-40dd-b573-19587400bd0b.png)

**Comment by ra3xdh** [comment]
I have noticed the following problems with dB units on Y axis:
* The marker values still be in absolute units while the axis is set as dB
* It is impossible to set limits and grid step because limits still be in absolute units
* Grid step setting is locked for log axis but should be unlocked for dB log axis

**Comment by tomhajjar** [comment]
Qucs/Qucs-S are lacking when one tries to choose items in the library or you want info on a placed device. There is zero info on the devices unless you use the Library Tools. Try to pick a varistor from the lengthy list.

It would be nice if the Main dock showed a components "Info" after a mouse click.

Show a placed devices "Info" via a new choice after a mouse right button click. Edit properties shows little info.

![2022-08-15_135005](https://user-images.githubusercontent.com/102838604/184688445-7abcabf9-3447-4c63-b59f-3d87f0ffed85.jpg)
![Qucs-S library view](https://user-images.githubusercontent.com/102838604/184686894-a13b8d7b-361a-4dcb-8832-6fc2891de23d.jpg)
![QucsStudio library view](https://user-images.githubusercontent.com/102838604/184686895-2748e1b0-e0a3-4a5b-882e-f744c7d4e133.jpg)

**Comment by ra3xdh** [comment]
Yes, the library tree on the left panel may benefit from suggested improvement. I was also considering such addition. I will implement symbol and device info preview in one of the next releases.

**Comment by ra3xdh** [comment]
I have created a separated task #135 for library tree improvement.

**Comment by ra3xdh** [comment]
I have fixed setting limits and marker issue when the dB units are selected for axis. The remaining issues is the manual step setting for logarithmic dB axis.

**Comment by ra3xdh** [comment]
I have noticed application crash when adding a curve to Smith diagram. This is related to newly introduced dB axis units.

**Comment by dsm** [comment]
I tested app on windows 10 same issue here

**Comment by ra3xdh** [comment]
@dsm , Yes, I can reproduce this bug. I will provide a fix. I have crated a special dedicated issue #187

**Comment by dsm** [comment]
Let's make the necessary arrangements to compile the application with qt6 to support and maintain it for a longer period of time. I know priority lower than usability, add new feature and make it more robust app and I know this needs so many code clean up maybe rewrite so many code but we need well clean code base for good maintainability for future release

**Comment by ra3xdh** [comment]
I didn't try to compile Qucs-S on Qt6 yet, but the adding support of Qt6 should be much more smooth that Qt3->Qt4 migration. Qt6 doesn't contain changes breaking backward compatibility. If the application compiles on Qt5.15 without deprecation warnings, it should be compiled on Qt6 too. I have done some works in this direction like removing deprecated QtScript dependency. See the #75 and #77.

**Comment by ra3xdh** [comment]
I have created a special issue dedicated Qt6 portability. See #190

**Comment by ponyatov** [comment]
It would be great to have rich scripting facilities (Python?) to making more or less complex things in the running QUCS instance.

At least, I want to use QUCS as a schematic frontend via bidirectional data interchange with PCB making software such as KiCAD, Specctra and TopoR.

**Comment by ra3xdh** [comment]
@ponyatov Yes, the adding of the Python scripting features were discussed for old Qucs around six years ago. Currently we only provide a Python package to load Qucs dataset and plot the diagrams. Something like Python extensions in Klayout may be useful. But it is totally unclear how to proceed with adding Python. Currently I have more high-priority tasks likes implementing of the microstrip devices and reverting back the digital simulation. So, don't expect adding Python integration in the near future.

**Comment by eldaravt** [comment]
> I have just added a possibility to set dB units for Y-axis if logarithmic scale is selected. The new feature is available on `current` branch. ![image](https://user-images.githubusercontent.com/4920080/178518827-fd4a32ac-6b07-4233-a880-c0a33c7abce9.png) ![image](https://user-images.githubusercontent.com/4920080/178519083-85ebc167-b7b2-40dd-b573-19587400bd0b.png)

![Screenshot from 2023-06-19 10-01-00](https://github.com/ra3xdh/qucs_s/assets/129725327/d3f7c56e-04f6-4f00-8941-589ec687d0c6)
Incorrect:
- left view use log. left axis (-6dB at cutoff freq.)
- right view Nutmega eq (-3dB at cutoff freq.)

**Comment by ra3xdh** [comment]
@eldaravt I have just added a fix for this. 
![image](https://github.com/ra3xdh/qucs_s/assets/4920080/6a2947f6-7e9f-40a8-ba86-7d9a1f5574a5)

**Comment by johndoespiced** [comment]
Sorry if this is the wrong place. But it would be neat if Qucs-S could have as solver engines the ones only available through Wine, like QucsStudio, QSpice and LTSpice. I think there are command line executables for these.

**Comment by ra3xdh** [comment]
> Qucs-S could have as solver engines the ones only available through Wine, like QucsStudio, QSpice and LTSpice

Adding support for Windows-only proprietary simulation backends is not considered. Qucs-S supports only open-source cross-platfrom simulation kernels.

**Comment by SmallJoker** [comment]
> User request: automatically align device by grid after rotation

I have run into the same issue after rotating a generic LED or transistor. Clicking "Snap to grid" did fix the alignment issue for the selected component. Is there any particular reason why this alignment function cannot be run after rotating the part?

PS: Thank you for continuing the Qucs project. Much appreciated.

**Comment by tomhajjar** [comment]
In #203 I asked if Rotate "Right" could be added.

I noticed that using Rotate "Left" multiple times caused the selected items to jump off the grid. Adding Rotate "Right" would mean both less mouse clicks and minimize grid misalignment.

**Comment by ra3xdh** [comment]
> Is there any particular reason why this alignment function cannot be run after rotating the part

I cannot say why the developers of the schematic widget didn't add align to grid after rotation. I have tried to fix this issue recently, and this was not a straightforward task. Need to dig into the legacy code. I will try to provide a fix for this by the next release.

**Comment by ra3xdh** [comment]
I have just added a fix for device rotation. Now the device should be aligned on grid if it was rotated. This fix is available on `current` branch. I cannot reproduce the rotation issues anymore after the patch has been applied. I would kindly ask to test it before release if the issue still present.

**Comment by ra3xdh** [comment]
The recent attempt to add an automatic set on grid after rotation made the things worse. Now the device always falls out of grid after the copy/paste from clipboard. I will retract the recent commit if the solution will not be found.

**Comment by tomhajjar** [comment]
Adding Rotate "Right" would mean less mouse clicks and minimize grid misalignment... ;-}

**Comment by ra3xdh** [comment]
@tomhajjar The adding "Rotate right" may be harder than fix the rotation. It's need to dig into the legacy code to implement this. I cannot exactly say what is the reason of grid misalignment. This bug is hard to reproduce and appears time to time. I cannot determine exact steps to reproduce it. It appears on Windows more often than on Linux. It seems it depends on the platform and screen resolution.

**Comment by tomhajjar** [comment]
If you rotate the tunnel diode symbol 3 times, the 45 deg lines jump off grid.

![2023-12-16_092025](https://github.com/ra3xdh/qucs_s/assets/102838604/ca447ed0-e647-44cc-b4fd-21edb13d49a0)

[symbols_rotate.zip](https://github.com/ra3xdh/qucs_s/files/13692832/symbols_rotate.zip)

**Comment by ra3xdh** [comment]
> If you rotate the tunnel diode symbol 3 times, the 45 deg lines jump off grid

This is not related to device rotation bug. The painting rotation works differently. And it cannot be fixed by adding rotate right function. The painting rotation was fixed by #397 , but the device grid misalignment still appear time to time.

**Comment by iwbnwif** [comment]
> I have just implemented the numeric marker position setting. The screenshot illustrates how it looks like. This feature is available on the ´current´ branch now. ![image](https://user-images.githubusercontent.com/4920080/173306224-3fc2794c-6983-451e-9fe8-f67e834f8d89.png)

I think it is relatively simple to add a small square or triangle to the end of the marker leader line. I have a test version working and it is helpful, especially with the very awesome new tuning function. Would it be preferable to include an option in the marker dialog for example "Marker indicator:" "Off" / "Square" / "Triangle"?
I am happy to provide a PR if this is of interest.

**Comment by ra3xdh** [comment]
@iwbnwif , Yes, please open a PR. This will make marker position more visible. One marker indicator type would be sufficient.

**Comment by iwbnwif** [comment]
> @iwbnwif , Yes, please open a PR. This will make marker position more visible. One marker indicator type would be sufficient.
I have submitted a PR which has both square and triangle as options. The reason is that I find the square more useful on return loss graphs, but the triangle more useful on most other graphs.

**Comment by tomhajjar** [comment]
Qucs can export a Touchstone formatted s-parameter file using qucsconv.exe. This can be useful for some users. 

qucsconv converts the s-parameter data in filename.dat. Oddly qucsconv defaults to naming it to filename.dat instead of filename.s2p. 


![2024-02-02_142122](https://github.com/ra3xdh/qucs_s/assets/102838604/147c38c4-a816-485c-8629-dcec94ce474e)

**Comment by ra3xdh** [comment]
> Qucs can export a Touchstone formatted s-parameter file using qucsconv.exe

This feature will be returned after implementing #370 Qucsconv has a deep dependency on Qucsator and cannot be divided from Qucsator. The full qucsconv will be returned after adding `qucsator_rf` as a submodule.

**Comment by dsm** [comment]
maybe switch qt 6.7 or future lts 6.8 default for windows it's looks nice on win11 with new windows11 style on dark theme.

![Screenshot 2024-04-12 153555](https://github.com/ra3xdh/qucs_s/assets/41967334/3bab6628-1ee7-4a6d-b60e-25258ff2cb3d)

**Comment by ra3xdh** [comment]
This issue still be opened since 2022 and I decided to close this with the following resolution on remaining tasks:

* Adding wattmeter is not straightforward task. The experiments with the SPICE netlsit has showed that the power calculation may be not reliable for all analyses cases. Some analyses require adding multiplier on schrmatic, but something works only using postprocessing scripts. Let's postpone this task for now.
* Automatic enumeration of the devices may be implemented in the future. I will open another ticket when this task will be planned for the next release.
