### ISSUE TITLE
qucs-s for OSX 10.14

### ISSUE THREAD

**Issue by bnilsson11** [ra3xdh/qucs_s#921]
In qucs-s 24.3.0 for MacOS 10.14, the Delete command using keyboard Delete or Backspace is not working.
Delete using mouse right-click is working.

**Comment by dsm** [comment]
I'll fix this issue, normally delete shortcut is QKeySequence::Delete but delete button not working for macbook m3 pro so I changed QKeySequence::Delete to QKeySequence::Backspace but in qt 6.2 Meta+H is backspace but Qt 6.7 Meta+H or backspace is KeySequence::Backspace. So in your mac Mata+H should work it qt says. but I'll added QKeySequence::Backspace and QKeySequence::Delete both for delete. can you test it ?

**Comment by bnilsson11** [comment]
This Mac is at my old work place, and I am there every Monday morning to after lunch time.
So it will take a week before I can test it.

**Comment by dsm** [comment]
Ok I'll add directly backspace and delete key and I don't use QKeySequence and I'll test it both macos and logi mx keys keybords as soon as I get home.

**Comment by dsm** [comment]
I pushed a commit that solve this issue, I tested backspace and delete keys both works under mac, some mac keyboards don't have delete key so backspace added for this reason.

**Comment by ra3xdh** [comment]
Fixed by https://github.com/ra3xdh/qucs_s/commit/13e920915358bb7b56ff30f1fc6917b6921b01ef Closing as completed.

**Comment by bnilsson11** [comment]
Where can I find the release for MacOS 10.14 with working Delete/Backspace?

**Comment by dsm** [comment]
You can download latest 24.3.1 macosx release in release section

**Comment by bnilsson11** [comment]
Thanks, now working fine. 
Good work.
