### ISSUE TITLE
Relative user library path requested

### ISSUE THREAD

**Issue by bnilsson11** [ra3xdh/qucs_s#922]
When working on the same project from different sites, it would be convenient to use the same user_lib/libraries.
However, the library device symbol is using full path, and this is usually not same for different workplace sites.
So a circuit with a user lib device defined at one workplace is broken as seen from another workplace.
Allowing paths relative to qucs_s home would solve this.

**Comment by bnilsson11** [comment]
I cannot get it to work.
Where should I place my project libs?

**Comment by ra3xdh** [comment]
Place the library inside the project directory. You should create the project first. The projects are located by default in `$HOME/QucsWorkspace` (new installations) or `$HOME/.qucs` (old installations).

**Comment by ra3xdh** [comment]
I have just checked this feature (#567). Everything works on my machine.

**Comment by bnilsson11** [comment]
Ok, it is working, I forgot to open the project first.

Back to relative paths, just interested:
Search of user_lib relative to qucs home, was it ever implemented?

**Comment by ra3xdh** [comment]
The libraries from `$HOME/QucsWorspace/user_lib` always share absolute path, because the system and user libraries may have the same name. The introduction of the project libraries with relative path is sufficient for sharing libraries with projects and schematics.

**Comment by ra3xdh** [comment]
The `$HOME/QucsWorkspace` is the default project directory path since v24.2.1. Closing this issue as completed.
