### ISSUE TITLE
qucs-s windows uses old icon mac uses new one

### ISSUE THREAD

**Issue by dsm** [ra3xdh/qucs_s#929]
Hi, this is the difference mac and windows icon and qucs-s.exe normally uses different icon but innosetup changed icon to old icon but not visible in explore it's strange. We should set app icon using Qt API and CMake. I created new.ico based on qucs-s.svg in qucs/bitmaps .

![image](https://github.com/user-attachments/assets/0fbb8f4c-6d58-4675-b02d-c152dd851d02)

**Comment by ra3xdh** [comment]
It's need to replace icons in `contrib/InnoSetup/misc` It still use 64x64 icons. Maybe switch to higher resolution or vector icon if supported.

**Comment by dsm** [comment]
256x256 looks good on Full HD screen i changed in innosetup locally and build exe, Qt page says convert icon to ico file, i think svg not supported.

**Comment by dsm** [comment]
ico file can store multiple resoultion icons in a single file using

magick convert 16.png 32.png 48.png 128.png 256.png -colors 256 icon.ico

**Comment by dsm** [comment]
I sent a PR #932 to fixed windows icon but app title icon not changed it needs to be changed in Qt code
App icon:
![image](https://github.com/user-attachments/assets/0c5b6510-212b-4b41-9369-604f07f62cd2)

title icon:
![image](https://github.com/user-attachments/assets/4190a1f5-e3dd-4f1f-b6d8-9ca8ca3e0da9)

**Comment by dsm** [comment]
#ifndef __APPLE__
  setWindowIcon (QPixmap(QString(":/bitmaps/hicolor/scalable/apps/qucs.svg")));
#else

I tested this usage and succesfully render svg. about diolog also used 256x256 png maybe this one can be used there.

**Comment by dsm** [comment]
```cpp
#ifndef __APPLE__
  setWindowIcon (QPixmap(QString(":/bitmaps/hicolor/scalable/apps/qucs.svg")));
#else
```

I tested this usage and succesfully render both app and title svg icon. about diolog also used 128x128 png maybe this one can be used there. Why you think the existing icon should remain (big.qucs.xpm) generally app and title icons are same.

**Comment by ra3xdh** [comment]
> I tested this usage and succesfully render both app and title svg icon. about diolog also used 128x128 png maybe this one can be used there.

Yes, this one could be accepted.
