### ISSUE TITLE
.INCLUDE statement - manually editing Filename or Browse doesn't work - altermod usage

### ISSUE THREAD

**Issue by tomhajjar** [ra3xdh/qucs_s#948]
Having two issues:

1) .INCLUDE statement manually editing Filename or using Browse doesn't work anymore. I tried manually editing the Spice filename and file info goes blank. I then tried using Browse and again file info goes blank. You can do all the steps, click "Apply" and everything looks good but when you click "OK" all fields go blank. In fact make no changes and click "OK" and all the fields go blank. I have to use a text editor to make the changes or repair the file.

For simplicity, I decided to shorten the filename "hicumL2V2p40_model_card.lib" -> "hicumL2V2p40.lib" and found the issue.

2) I wanted to reproduce the data in the ngspice netlist "hic2_ib_ic_thermal.sp" and can't figure out how to get the line 
"altermod @hicumL2V2p40[flsh]=1" to work in Qucs. The last pic is the ngspice plots for hic2_ib_ic_thermal.sp.

![2024-09-15_184709](https://github.com/user-attachments/assets/8173d758-028d-4e98-9d77-9edc30ff01a0)
![2024-09-15_192034](https://github.com/user-attachments/assets/a0976e34-c9a5-49a0-88c3-517d1f972e80)
![2024-09-15_203855](https://github.com/user-attachments/assets/7b4ab662-60f3-4155-af71-7746c92dd1af)

[HICUM2_prj.zip](https://github.com/user-attachments/files/17007937/HICUM2_prj.zip)

**Comment by ra3xdh** [comment]
> INCLUDE statement manually editing Filename or using Browse doesn't work anymore. 

I confirm this bug. There is no workaround. This bug is critical. I will prepare v24.3.2 release containing the fix as soon as possible.

**Comment by tomhajjar** [comment]
I will use the text editor work-around.

Can you show how to get "altermod @hicumL2V2p40[flsh]=1" in the ngspice netlist "hic2_ib_ic_thermal.sp" to work in Qucs?

**Comment by ra3xdh** [comment]
> Can you show how to get "altermod @hicumL2V2p40[flsh]=1" in the ngspice netlist "hic2_ib_ic_thermal.sp" to work in Qucs?

There is no way except composing a custom Nutmeg script. I have deprecated the explicit `SweepModel` property of the Parameter sweep. See #839 But I didn't take into account that the model may be defined outside schematic in the library file using `.include`. There is not way to substitute the variable for model defined in the external file.

**Comment by tomhajjar** [comment]
I took the easy way out and made a 2nd Spice model file with "thermal" enabled.

![2024-09-18_205522](https://github.com/user-attachments/assets/b10e44af-ae76-4131-ac18-c542bfb96bf0)

[HICUM2_prj.zip](https://github.com/user-attachments/files/17051938/HICUM2_prj.zip)

**Comment by ra3xdh** [comment]
The both issues are fixed on this branch https://github.com/ra3xdh/qucs_s/tree/release/24.3.2  I will try to prepare the 24.3.2 update in the next few days. I have added model sweep pattern recognition. 

![image](https://github.com/user-attachments/assets/40719e63-c78e-443b-860f-53f2d2d7fed9)

**Comment by tomhajjar** [comment]
Will it work for both cases like xyce?

![2024-09-19_123700](https://github.com/user-attachments/assets/d0d4f908-e7b8-4f99-8d30-4070bb5ebb1a)
![2024-09-19_123646](https://github.com/user-attachments/assets/92b855b5-d839-4204-ae70-94dfcf795558)

[BJT_Beta_sweep_xyce.zip](https://github.com/user-attachments/files/17062987/BJT_Beta_sweep_xyce.zip)

**Comment by ra3xdh** [comment]
Fixed by #955

**Comment by tomhajjar** [comment]
Does the latest nightly fix the Beta sweep of a Red BJT?
