### ISSUE TITLE
Spice netlist versus .INCLUDE Issues

### ISSUE THREAD

**Issue by tomhajjar** [ra3xdh/qucs_s#951]
Discussion #950 has found a few more issues. Attached are two schematics showing the issues. 

1) The SB5100.lib diode Spice model doesn't work. See SB5100_recovery.sch. The model does work if it is made into a sub-circuit using "Spice netlist". See SB5100_sub_recovery.sch.

2) When making the subcircuit SB5100_sub.sch, the 1ST time you make it the filename has the entire PATH. When you place this sub in the schematic, the simulation fails and you find the "Spice netlist" is missing. You have to re-open SB5100_sub.sch, place another "Spice netlist" and Browse again for SB5100.lib. I made SB5100_sub_1st.sch to show the problem.

**TODO** list:

- [x] Convert path to  relative only if schematic belongs to project or saved.  

![2024-09-17_235825](https://github.com/user-attachments/assets/778335fa-3913-4a16-8e5e-4a74e3f13fb0)
![2024-09-17_235803](https://github.com/user-attachments/assets/7463de6e-2771-4354-96f8-b308e21bf991)
![2024-09-18_001529](https://github.com/user-attachments/assets/d3b26d30-c476-4337-8b74-e92c386aca99)
![2024-09-18_003044](https://github.com/user-attachments/assets/90db4918-2805-47ad-8819-8f7ef94a631d)

[Rectifiers_prj.zip](https://github.com/user-attachments/files/17038353/Rectifiers_prj.zip)
[LTspice SB5100.zip](https://github.com/user-attachments/files/17043291/LTspice.SB5100.zip)

**Comment by ra3xdh** [comment]
The SB5100 diode model works on my machine. See https://github.com/ra3xdh/qucs_s/discussions/950#discussioncomment-10682790 

> the 1ST time you make it the filename has the entire PATH. When you place this sub in the schematic, the simulation fails and you find the "Spice netlist" is missing. 

The application applies relative path conversion after #640 The path is set relatively to project directory or containing schematic directory. This may be fixed as the following:

* If the schematic doesn't belong to the project set absolute path
* If schematic belongs to project set relative path

**Comment by tomhajjar** [comment]
Still having the issue in item #2 above. I have to redo the sub-circuit twice to get rid of the extended path. I didn't document it this time.

**Comment by ra3xdh** [comment]
I will implement the path setting policy proposed here: https://github.com/ra3xdh/qucs_s/issues/951#issuecomment-2358983233 in the next release.

**Comment by ra3xdh** [comment]
Fixed by #1018
