### ISSUE TITLE
Hide microstrip filters when Ngspice is selected

### ISSUE THREAD

**Issue by darkstar007** [ra3xdh/qucs_s#96]
If I create I filter as show 
![here](https://user-images.githubusercontent.com/1486685/176998703-a623e6b2-6ce4-4ac4-b125-450b817e7bdf.png)
and then click 'calc and put into clipboard' and then paste into the main window,it generates lots of pop-up warnings as shown 
![here](https://user-images.githubusercontent.com/1486685/176998781-8790093a-e190-4b9c-8b0b-4c858ea9166a.png)
which have to be individually dismissed by clicking on them - its rather annoying and possibly broken?

Thanks,
Matt

**Comment by ra3xdh** [comment]
The microstrip devices are SPICE-incompatible and set hidden if the Ngspice is selected as the primary simulation kernel. See also #94 The solution may be to hide the microstrip filters from the filter design tool if the SPICE mode is active to prevent such errors in the future.

**Comment by darkstar007** [comment]
OK, thanks - setting the simulator to Qucsator and the issue go away.

I'd recommend greying the filters out (**and a tooltip to say why they are greyed out**) when ngspice is selected as the simulator would be a good approach.

Thanks,
Matt

**Comment by ra3xdh** [comment]
Fixed on `current` branch. The incompatible filters are greyed now.
