### ISSUE TITLE
MOSFET Libraries qucsator issues

### ISSUE THREAD

**Issue by tomhajjar** [ra3xdh/qucs_s#970]
I was trying to convert some ngspice audio MOSFET power amplifier projects over to work with qucsator. I can get AC and DC simulations to work but Trans does not.

I then tried using MOSFETs from the built in "Qucs" Libraries in simple Tran circuits and cannot get any device to work with qucsator even after removing the inductor and capacitor. Are the MOSFET Libraries marginal under qucsator?

![2024-09-28_131245](https://github.com/user-attachments/assets/7402fbb2-be00-480b-b7ba-0631e72eb943)
![2024-09-28_131637](https://github.com/user-attachments/assets/13a72e0a-cf82-4c9b-9ff7-1de44811b35a)

[MOSFET_test_qucs_prj.zip](https://github.com/user-attachments/files/17175655/MOSFET_test_qucs_prj.zip)
[Amp_100W_qucs_prj.zip](https://github.com/user-attachments/files/17175667/Amp_100W_qucs_prj.zip)

**Comment by ra3xdh** [comment]
Qucsator has very poor time-domain performance. It is not Qucs-S GUI issue. See https://github.com/Qucs/qucsator/issues/19 Switch simulaiton may fail even without LC elements. The MOSFET device in the library contains the parasitic elements inside which may cause convergence issues with Qucsator.  The fixing of this is not a straightforward task. The help from simulation algorithms experts is highly appreciated.

**Comment by ra3xdh** [comment]
The MOSFET libraries and qucsator interaction from the GUI side remains untouched since the 0.0.19 version. Also I didn't change the TRAN computation algorithm in the QucsatorRF. All known TRAN simulation issues of Qucsator still be inherited by QucsatorRF.
