### ISSUE TITLE
VirusTotal reports potential issues with the Windows version: Qucs-S-24.3.2-setup.exe

### ISSUE THREAD

**Issue by dvnicolasdh** [ra3xdh/qucs_s#978]
It seems that VirusTotal reports potential issues with the Windows version: Qucs-D-24.3.2-setup.exe
see: https://www.virustotal.com/gui/file/e9809f908719fa38b9df08a2c47adf4800a8d1bedf23141704e4855996edd541
![image](https://github.com/user-attachments/assets/bf28c70b-2cde-4ccc-8b26-9359a5796cdf)

**Comment by ra3xdh** [comment]
It is false positive report. The Windows packages are generated automatically using Github (Microsoft) infrastructure. You can see the workflow script here: https://github.com/ra3xdh/qucs_s/blob/current/.github/workflows/deploy.yml This report probably may be related that the binaries are not signed. See also: https://hackerdose.com/malware/w32-aidetectmalware-bkav-pro/
