### ISSUE TITLE
S-Parameter can't switch on Noise simulation

### ISSUE THREAD

**Issue by dwarning** [ra3xdh/qucs_s#993]
Using the windows binary version 24.3.2 I can't switch on Noise calculation in the S-Parameter property box. Anytime after pressing "Take over" the value jumps back to "no". Same behaviour for the other items e.g. saveCVS.
Self build linux binary 24.3.2 works as expected.

**Comment by ra3xdh** [comment]
This issue has been already reported and fixed. See #968 This will be available since the next release (planned by the end of month). Build the application from git to get the fixed version. Closing this.
