### ISSUE TITLE
Plot scientific/engineering notation does work on second Trans plot

### ISSUE THREAD

**Issue by tomhajjar** [ra3xdh/qucs_s#996]
During Q&A in #994, I found plot scientific/engineering notation does work on second Trans plot on data display page.

![2024-10-16_121134](https://github.com/user-attachments/assets/84e42f7a-f57b-45fd-b921-25aed62fc4a1)
![2024-10-16_121147](https://github.com/user-attachments/assets/7e0d0ca6-5d18-4714-b3a3-ba26d241d8b7)

[Amp_MFA1_prj.zip](https://github.com/user-attachments/files/17399590/Amp_MFA1_prj.zip)

**Comment by ra3xdh** [comment]
Everything works as expected. You have a value `5.002` It cannot be converted to engineering notation without number truncation.  The Qucs-S doesn't have the setting to define the number precision on the plots.
